### ISSUE TITLE
Alternating 'error' and 'nil' responses across commands with errors, in consecutive executions

### ISSUE THREAD

**Issue by ashishsonamm** [DiceDB/dice#1006]
## Steps to reproduce

`GET key1 key2`
execute the above command (or any command which would throw err) multiple times 

## Expected output

The expected output when the above set of commands (maybe when run on Redis)

![Screenshot From 2024-10-08 14-14-24](https://github.com/user-attachments/assets/166923e9-b19b-4ff7-b1ef-257fd74449d3)

## Observed output

The observed output when the above set of commands when run on DiceDB

![Screenshot From 2024-10-08 14-16-01](https://github.com/user-attachments/assets/159417f4-eebc-4936-9a33-46f9d30f48c7)

## Expectations for resolution

This issue will be considered resolved when the following things are done

1. changes in the [`dice`](https://github.com/dicedb/dice) code to meet the expected behavior
3. addition of relevant test case to ensure we catch the regression

You can find the tests under the `integration_tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [setup DiceDB locally](https://github.com/dicedb/dice)
- [setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [setup DiceDB CLI](https://github.com/dicedb/dice)

**Comment by ashishsonamm** [comment]
hi @lucifercr07 @JyotinderSingh I would like to work on this, please assign this to me

**Comment by JyotinderSingh** [comment]
> hi @lucifercr07 @JyotinderSingh I would like to work on this, please assign this to me

Assigned

**Comment by ashishsonamm** [comment]
fix got merged in a different pr
