### ISSUE TITLE
Command Migration: ('DEL', 'EXISTS', 'PERSIST', 'TYPE')

### ISSUE THREAD

**Issue by AshwinKul28** [DiceDB/dice#1015]
This issue tracks the migration of the mentioned commands - ('DEL', 'EXISTS', 'PERSIST', 'TYPE') to make them compatible across the three protocols supported by the Dice database: RESP, HTTP, and WebSocket.
DiceDB now supports more than one protocols (Resp/http/websocket). We don't want eval operation of each command to be strictly bound with any of the protocols. Currently eval function return statements of each command is bounded to the RESP protocol. 

*The migration is required because:*

- The current implementation is specific to the RESP protocol
- Evaluation functions of each command must be refactored to ensure protocol-agnostic behavior.
- Evaluation functions should return raw responses instead of protocol specific responses.

The goal is to make the command logic protocol-independent, allowing all three protocols to call the same core functionality seamlessly.

### Requirements

- Refactor the evaluation function of `[Command Name]` to be generic.
- Ensure the evaluation function does not include protocol-specific logic.

### Migration Steps

1. **Analyze Current Implementation**
   - Review the current codebase to understand how the command logic is implemented.

2. **Refactor Return Logic**
   - Create a new function with the function definition as `evalXXX(args []string, store *dstore.Store) *EvalResponse` under the file `/internal/eval/store_eval.go`
   - Analyse return statements of the eval and modify them to send raw types without encoding
   - Use errors in the return statements from `/errors/migrated_errors.go` file
   - Use perdefined responses from `/internal/clientio/resp.go` file as RespType variables

3. **Command/Worker specific Changes**
   - Make `IsMigrated` flag to true in the commands information under `/internal/eval/commands.go` file.
   - Use the newly written eval function against the `NewEval` parameter in the same command structure.
   - Delete the old eval function from the `/internal/eval/eval.go` file.
   - Add the migrated command to the `/internal/worker/CommandsMeta` map and make it's type as `SingleShard`

4. **Update Unit Tests**
   - Refactor existing unit tests to accommodate the new implementation.
   - Add new unit tests if necessary to cover all possible cases.

5. **Integration Tests**
   - Run all integration tests to ensure successful migration.
   - Ensure that each protocol (RESP, HTTP, WebSocket) works correctly after migration.

### Checklist

- [ ] Migrated the evalXXX function with the latest definition
- [ ] Update or add unit tests for the new implementation.
- [ ] All unit tests pass successfully.
- [ ] Ensure all integration tests pass successfully.

### Additional Notes

- Describe any edge cases that need to be handled in the generic function.
- Mention any protocol-specific optimizations required in wrappers.
  
If there are any questions or concerns about this migration, please mention them here.

### Related Issues/PRs

- Sample implementation for the Get, Set, GetSet and SetEx can be found in [this Pull Request.](https://github.com/DiceDB/dice/pull/766)

**Comment by parzival272000** [comment]
Hi,
Can you assign this to me ?
Regards,
Mayank Jha

**Comment by AshwinKul28** [comment]
Thanks @parzival272000 go for it. 🚀

**Comment by mohit-nagaraj** [comment]
@parzival272000 whts the status?

**Comment by AshwinKul28** [comment]
HI @parzival272000 , I hope you are doing well. Do you happen to have any updates on this? If you've any doubts please let us know on the discord.

**Comment by parzival272000** [comment]
Hi @AshwinKul28 couldn't progress with this yet. You can allot it to someone else, am preoccupied with some stuff

**Comment by AshwinKul28** [comment]
Sure thanks @parzival272000 ,

**Comment by AshwinKul28** [comment]
@mohit-nagaraj if you are still interested, go for it! 🚀

**Comment by mohit-nagaraj** [comment]
Sure thanks on it

**Comment by soumya-codes** [comment]
@mohit-nagaraj hope you are doing well. Any updates on the progress? We are targeting these issues little aggressively as we maintaining the commands across two separate servers is getting very cumbersome.

**Comment by mohit-nagaraj** [comment]
hey i do get it raising a pr tmr

**Comment by mohit-nagaraj** [comment]
Hey i need to ask a few doubts before raising a pr
How to contact one of u guys

**Comment by apoorvyadav1111** [comment]
Hey, you can reach out to us here or on the discord community.

**Comment by mohit-nagaraj** [comment]
so while writing test cases how should i write it, could u give a brief overview, i am following this pr https://github.com/DiceDB/dice/pull/1097/files#diff-3941f5aad18919b2441c1d32cc30a869cb791fd4709ff27d8f34b61f0c4c0455

should i just follow it to make the test cases like them? i am little new to writing test cases so..... Wht modifications should i do

**Comment by mohit-nagaraj** [comment]
Btw i saw prs updating even internal/server/cmd_meta.go 

should i also update it

**Comment by mohit-nagaraj** [comment]
@apoorvyadav1111 
![image](https://github.com/user-attachments/assets/cd41a63a-f0eb-4f23-98e4-b34a6fb7441e)
Theres this issue with naming convection for type

**Comment by JyotinderSingh** [comment]
> so while writing test cases how should i write it, could u give a brief overview, i am following this pr https://github.com/DiceDB/dice/pull/1097/files#diff-3941f5aad18919b2441c1d32cc30a869cb791fd4709ff27d8f34b61f0c4c0455
> 
> 
> 
> should i just follow it to make the test cases like them? i am little new to writing test cases so..... Wht modifications should i do
> 
> 

You mostly just need to move the existing tests from async folder to resp folder. Then check if those tests already also exist inside HTTP and websockets folder. If they do, well and good, otherwise, add the same tests in these folders (in HTTP/websocket format, refer to existing tests for these).

A good idea is to see the different PRs already submitted (go to PRs tab, and replace the `is:open` filter with `is:closed`) and gather inspiration from them.

**Comment by JyotinderSingh** [comment]
> Btw i saw prs updating even internal/server/cmd_meta.go 
> 
> 
> 
> should i also update it

Yes

**Comment by mohit-nagaraj** [comment]
> > so while writing test cases how should i write it, could u give a brief overview, i am following this pr https://github.com/DiceDB/dice/pull/1097/files#diff-3941f5aad18919b2441c1d32cc30a869cb791fd4709ff27d8f34b61f0c4c0455
> > should i just follow it to make the test cases like them? i am little new to writing test cases so..... Wht modifications should i do
> 
> You mostly just need to move the existing tests from async folder to resp folder. Then check if those tests already also exist inside HTTP and websockets folder. If they do, well and good, otherwise, add the same tests in these folders (in HTTP/websocket format, refer to existing tests for these).
> 
> A good idea is to see the different PRs already submitted (go to PRs tab, and replace the `is:open` filter with `is:closed`) and gather inspiration from them.

Sure thanks for this info

**Comment by AshwinKul28** [comment]
HI @mohit-nagaraj anything specific did you observe on the "memory leak" please mention it here, since it has not happened before migration, I'm curious to know what's the exact issue.  It would be great if you could explain it here or on the discord, and we can try to find some solution to it, so you will be unblocked. We need to move little faster now in the migration work, so please reach out to us for any blockers on discord. Thanks a lot!
