### ISSUE TITLE
Command Migration: ('APPEND', 'GETRANGE')

### ISSUE THREAD

**Issue by AshwinKul28** [DiceDB/dice#1018]
This issue tracks the migration of the mentioned commands - ('APPEND', 'GETRANGE') to make them compatible across the three protocols supported by the Dice database: RESP, HTTP, and WebSocket.
DiceDB now supports more than one protocols (Resp/http/websocket). We don't want eval operation of each command to be strictly bound with any of the protocols. Currently eval function return statements of each command is bounded to the RESP protocol. 

*The migration is required because:*

- The current implementation is specific to the RESP protocol
- Evaluation functions of each command must be refactored to ensure protocol-agnostic behavior.
- Evaluation functions should return raw responses instead of protocol specific responses.

The goal is to make the command logic protocol-independent, allowing all three protocols to call the same core functionality seamlessly.

### Requirements

- Refactor the evaluation function of `[Command Name]` to be generic.
- Ensure the evaluation function does not include protocol-specific logic.

### Migration Steps

1. **Analyze Current Implementation**
   - Review the current codebase to understand how the command logic is implemented.

2. **Refactor Return Logic**
   - Create a new function with the function definition as `evalXXX(args []string, store *dstore.Store) *EvalResponse` under the file `/internal/eval/store_eval.go`
   - Analyse return statements of the eval and modify them to send raw types without encoding
   - Use errors in the return statements from `/errors/migrated_errors.go` file
   - Use perdefined responses from `/internal/clientio/resp.go` file as RespType variables

3. **Command/Worker specific Changes**
   - Make `IsMigrated` flag to true in the commands information under `/internal/eval/commands.go` file.
   - Use the newly written eval function against the `NewEval` parameter in the same command structure.
   - Delete the old eval function from the `/internal/eval/eval.go` file.
   - Add the migrated command to the `/internal/worker/CommandsMeta` map and make it's type as `SingleShard`

4. **Update Unit Tests**
   - Refactor existing unit tests to accommodate the new implementation.
   - Add new unit tests if necessary to cover all possible cases.

5. **Integration Tests**
   - Run all integration tests to ensure successful migration.
   - Ensure that each protocol (RESP, HTTP, WebSocket) works correctly after migration.

### Checklist

- [ ] Migrated the evalXXX function with the latest definition
- [ ] Update or add unit tests for the new implementation.
- [ ] All unit tests pass successfully.
- [ ] Ensure all integration tests pass successfully.

### Additional Notes

- Describe any edge cases that need to be handled in the generic function.
- Mention any protocol-specific optimizations required in wrappers.
  
If there are any questions or concerns about this migration, please mention them here.

### Related Issues/PRs

- Sample implementation for the Get, Set, GetSet and SetEx can be found in [this Pull Request.](https://github.com/DiceDB/dice/pull/766)

**Comment by bhima2001** [comment]
Hey @AshwinKul28, I would like to work on this.

**Comment by AshwinKul28** [comment]
Thanks @bhima2001 ! Go for it! 🚀

**Comment by AshwinKul28** [comment]
HI @bhima2001 , I hope you are doing well. Do you happen to have any updates on this? If you've any doubts please let us know on the discord.

**Comment by bhima2001** [comment]
@AshwinKul28  Hey, sorry for the delay. I am working parallelly on another issue on JSON.STRLEN. Will give you an update on this as soon as possible.

**Comment by AshwinKul28** [comment]
Thanks for the update @bhima2001 . If you are occupied already and don't have a bandwidth, let me know, we can reassign this to someone else.

**Comment by bhima2001** [comment]
Hey, GET RANGE should return string right? I am getting the following error "interface conversion: interface {} is string, not []uint8" is there something i am missing.  Because the value at the return step is as expected and is similar to the one in eval.go but I am getting this error.
