### ISSUE TITLE
Command Migration: ('LPUSH', 'RPUSH', 'LPOP', 'RPOP', 'LLEN')

### ISSUE THREAD

**Issue by AshwinKul28** [DiceDB/dice#1019]
This issue tracks the migration of the mentioned commands - ('LPUSH', 'RPUSH', 'LPOP', 'RPOP', 'LLEN') to make them compatible across the three protocols supported by the Dice database: RESP, HTTP, and WebSocket.
DiceDB now supports more than one protocols (Resp/http/websocket). We don't want eval operation of each command to be strictly bound with any of the protocols. Currently eval function return statements of each command is bounded to the RESP protocol. 

*The migration is required because:*

- The current implementation is specific to the RESP protocol
- Evaluation functions of each command must be refactored to ensure protocol-agnostic behavior.
- Evaluation functions should return raw responses instead of protocol specific responses.

The goal is to make the command logic protocol-independent, allowing all three protocols to call the same core functionality seamlessly.

### Requirements

- Refactor the evaluation function of `[Command Name]` to be generic.
- Ensure the evaluation function does not include protocol-specific logic.

### Migration Steps

1. **Analyze Current Implementation**
   - Review the current codebase to understand how the command logic is implemented.

2. **Refactor Return Logic**
   - Create a new function with the function definition as `evalXXX(args []string, store *dstore.Store) *EvalResponse` under the file `/internal/eval/store_eval.go`
   - Analyse return statements of the eval and modify them to send raw types without encoding
   - Use errors in the return statements from `/errors/migrated_errors.go` file
   - Use perdefined responses from `/internal/clientio/resp.go` file as RespType variables

3. **Command/Worker specific Changes**
   - Make `IsMigrated` flag to true in the commands information under `/internal/eval/commands.go` file.
   - Use the newly written eval function against the `NewEval` parameter in the same command structure.
   - Delete the old eval function from the `/internal/eval/eval.go` file.
   - Add the migrated command to the `/internal/worker/CommandsMeta` map and make it's type as `SingleShard`

4. **Update Unit Tests**
   - Refactor existing unit tests to accommodate the new implementation.
   - Add new unit tests if necessary to cover all possible cases.

5. **Integration Tests**
   - Run all integration tests to ensure successful migration.
   - Ensure that each protocol (RESP, HTTP, WebSocket) works correctly after migration.

### Checklist

- [ ] Migrated the evalXXX function with the latest definition
- [ ] Update or add unit tests for the new implementation.
- [ ] All unit tests pass successfully.
- [ ] Ensure all integration tests pass successfully.

### Additional Notes

- Describe any edge cases that need to be handled in the generic function.
- Mention any protocol-specific optimizations required in wrappers.
  
If there are any questions or concerns about this migration, please mention them here.

### Related Issues/PRs

- Sample implementation for the Get, Set, GetSet and SetEx can be found in [this Pull Request.](https://github.com/DiceDB/dice/pull/766)

**Comment by ankkyprasad** [comment]
Hi Ashwin, I'd like to work on this issue, Can you please assign this to me?

**Comment by AshwinKul28** [comment]
HI @ankkyprasad , I hope you are doing well. Do you happen to have any updates on this? If you've any doubts please let us know on the discord.

**Comment by ankkyprasad** [comment]
Hey @AshwinKul28, I'll start working on it from tonight. Didn't get time this weekends.

**Comment by AshwinKul28** [comment]
Hi @ankkyprasad hope you are doing well, can you please update the current progress on this task? If you have any blockers feel free to discuss here or on the discord.

**Comment by ankkyprasad** [comment]
Hey @AshwinKul28, I'm working on unittest cases. Will be done by this weekend...

**Comment by mohit-nagaraj** [comment]
Hey @ankkyprasad whts the update

**Comment by ankkyprasad** [comment]
Hey @mohit-nagaraj, you can take this up. I won't be unable to work on this due to some issues.

**Comment by Aditya-Chowdhary** [comment]
Hi, if this issue is available, I would like to work on it.

**Comment by apoorvyadav1111** [comment]
Hi @Aditya-Chowdhary, thank you for taking this on! Please proceed with the migration steps. Go for it!
