### ISSUE TITLE
Add support for `STACKREF`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#102]
Similar to `QREF`, let's implement `STACKREF` having commands to

- push `STACKREFPUSH`,
- pop `STACKREFPOP`,
- peek `STACKREFPEEK`, and
- length `STACKREFLEN`

Similar to`QREF`, `STACKREF` will also be based on the ByteList and will hold references to other keys in the store.

**Comment by JyotinderSingh** [comment]
Hi, I will like to take this up.
