### ISSUE TITLE
Implement Leaderboard Functionality

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#104]
**Is your feature request related to a problem? Please describe.**
Add Leaderboard functionality, similar to what redis does. Needs to be highly space efficient.

**Describe the solution you'd like**
Should be functionally similar to [Redis Leaderboard Overview](https://redis.com/solutions/use-cases/leaderboards/)

**Comment by JyotinderSingh** [comment]
Assigning this to myself.

**Comment by arpitbbhayani** [comment]
a beautiful sunset 🌥️ 

![Ticker_2](https://github.com/DiceDB/dice/assets/4745789/6635d3d5-2902-4106-b1d6-ab0327b95b25)

**Comment by moiz-frost** [comment]
> a beautiful sunset 🌥️
> 
> ![Ticker_2](https://user-images.githubusercontent.com/4745789/263437410-6635d3d5-2902-4106-b1d6-ab0327b95b25.png)

very beautiful

**Comment by Vsareen0** [comment]
Hey @JyotinderSingh , is this closed or open ?

**Comment by JyotinderSingh** [comment]
> Hey @JyotinderSingh , is this closed or open ?

This is deprioritized for now.

**Comment by arpitbbhayani** [comment]
![Recording 2024-09-06 013901](https://github.com/user-attachments/assets/327792c7-d788-47d4-a767-ef2c478d75cb)

**Comment by AshwinKul28** [comment]
This can be closed now @arpitbbhayani .
