### ISSUE TITLE
Inconsistent `JSON.STRLEN`: Error message inconsistent when no path is provided

### ISSUE THREAD

**Issue by apoorvyadav1111** [DiceDB/dice#1060]
Please note this issue is created while reviewing #1049 which resolves #777.

The error message needs to be formatted according to the type of the object.

Expected:
```bash
127.0.0.1:6379> json.set user:99 $ '{"name":"Bhima", "age":10}'
OK
127.0.0.1:6379> json.strlen user:99 
(error) WRONGTYPE wrong type of path value - expected string but found object

```

## Observed output

The observed output when the above set of commands when run on DiceDB

```bash
127.0.0.1:7379>  json.set user:99 $ '{"name":"Bhima", "age":10}'
OK
127.0.0.1:7379> json.strlen user:99 
(error) WRONGTYPE wrong type of path value - expected string but found integer
```

## Expectations for resolution

This issue will be considered resolved when the following things are done

1. changes in the [`dice`](https://github.com/dicedb/dice) code to meet the expected behavior
2. addition of relevant test case to ensure we catch the regression

You can find the tests under the `integration_tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [setup DiceDB locally](https://github.com/dicedb/dice)
- [setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [setup DiceDB CLI](https://github.com/dicedb/dice)

**Comment by bhima2001** [comment]
@apoorvyadav1111  Assign it to me i am anyway working on the docs too
