### ISSUE TITLE
Doc

### ISSUE THREAD

**Issue by nagkumar** [DiceDB/dice#1066]
![Screenshot_2024-10-11-19-25-12-66_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/2fe77c72-23fb-436e-81e0-a9e7e49d0799)

The benchmark doc says about redis but commands used are diceDB..is it doc error

**Comment by JyotinderSingh** [comment]
Redis benchmark refers to the memtier benchmark by Redis.
