### ISSUE TITLE
Windows OS compatibility to DiceDB

### ISSUE THREAD

**Issue by ambi88dex** [DiceDB/dice#108]
Being a windows user, I find it hard to start contribution to this project.
As a middle ground to development, I feel if we dockerize this project it might make it easier for the open source community in general to contribute irrespective of which OS they have.

We can use "bind mount" option to link to local files which are then compiled in the dockerized linux environment so that one doesn't has to do a different setup to make the code work in a different OS.

Alternative, solution is to create a new workflow with respect to project building for windows from scratch.

**Comment by JyotinderSingh** [comment]
Docker images are now available for the project.
