### ISSUE TITLE
Port taking too long to free after a connection

### ISSUE THREAD

**Issue by ayo-ajayi** [DiceDB/dice#109]
**Describe the bug**
Server takes very long time to free connection port.

**Expected behavior**
I want to run test files one after the other. The second test doesn't even start at all

**Additional context**
2023/09/16 15:56:22 starting an asynchronous TCP server on 0.0.0.0 8379
--- FAIL: TestSetAndGet (0.00s)
panic: dial tcp 127.0.0.1:8379: connect: connection refused [recovered]
	panic: dial tcp 127.0.0.1:8379: connect: connection refused

**Comment by AbhilashMallikarjuna** [comment]
When creating a socket in a server application, and the socket is closed, the operating system will put the socket in a TIME_WAIT state. During this TIME_WAIT state, the previous socket's address and port are reserved, and attempting to bind a new socket to the same address and port may result in an "Address already in use" error.

To immediately free the socket when the server is shutdown, we have to set one flag (SO_REUSEPORT).
`err = syscall.SetsockoptInt(fd, syscall.SOL_SOCKET, syscall.SO_REUSEPORT, 1)`

you can also refer to this solution
https://stackoverflow.com/questions/74066155/syscall-so-reuseport-not-available-in-net-package

**Comment by arpitbbhayani** [comment]
Fixed in #134. Thanks for pointing it out.
