### ISSUE TITLE
Inconsistent `KEYS`: Does not support patterns

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#1092]
## Steps to reproduce

```sh
redis> MSET firstname Jack lastname Stuntman age 35
"OK"
redis> KEYS *name*
(empty array)
redis> KEYS a??
(empty array)
redis> KEYS *
(empty array)
```

## Expected output

Should return all keys in the db.
```sh
redis> MSET firstname Jack lastname Stuntman age 35
"OK"
redis> KEYS *name*
1) "lastname"
2) "firstname"
redis> KEYS a??
1) "age"
redis> KEYS *
1) "lastname"
2) "age"
3) "firstname"
```

## Observed output

The observed output when the above set of commands when run on DiceDB

```sh
redis> MSET firstname Jack lastname Stuntman age 35
"OK"
redis> KEYS *name*
(empty array)
redis> KEYS a??
(empty array)
redis> KEYS *
(empty array)
```

## Expectations for resolution

Add pattern matching support to `KEYS` command

This issue will be considered resolved when the following things are done

1. changes in the [`dice`](https://github.com/dicedb/dice) code to meet the expected behavior
2. addition of relevant test case to ensure we catch the regression

You can find the tests under the `integration_tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [setup DiceDB locally](https://github.com/dicedb/dice)
- [setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [setup DiceDB CLI](https://github.com/dicedb/dice)

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh can i pick this issue?
> 
> 

Sure, assigned.

**Comment by apoorvyadav1111** [comment]
Hi @JyotinderSingh , Is this issue specific to dice-cli? I have this output when I am using redis-cli:
<img width="495" alt="image" src="https://github.com/user-attachments/assets/b8835a03-2c45-431f-b172-5007f6e78c23">
Please confirm if this is expected.
Thanks

**Comment by vanshavenger** [comment]
@apoorvyadav1111 yep i also got the correct results via redis-cli

**Comment by apoorvyadav1111** [comment]
@vanshavenger Thanks for confirming this.

**Comment by swarajrb7** [comment]
![Screenshot from 2024-10-15 11-40-53](https://github.com/user-attachments/assets/c8159972-382f-4460-bb16-1aa767f7dc5a)
![Screenshot from 2024-10-15 11-39-25](https://github.com/user-attachments/assets/775f1eba-8618-4de7-992c-92eab33e051d)
this is the output  i am getting

**Comment by swarajrb7** [comment]
@apoorvyadav1111 @JyotinderSingh

**Comment by swarajrb7** [comment]
![Screenshot from 2024-10-15 12-53-36](https://github.com/user-attachments/assets/e65ceaec-bfeb-415a-ad69-94f3f8409d98)
@apoorvyadav1111

**Comment by swarajrb7** [comment]
@JyotinderSingh 
i didn't understand how you got this output on dice-cli

redis> MSET firstname Jack lastname Stuntman age 35
"OK"
redis> KEYS *name*
(empty array)
redis> KEYS a??
(empty array)
redis> KEYS *
(empty array)

i am getting on different output on  dice-cli

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh 
> 
> i didn't understand how you got this output on dice-cli
> 
> 
> 
> redis> MSET firstname Jack lastname Stuntman age 35
> 
> "OK"
> 
> redis> KEYS *name*
> 
> (empty array)
> 
> redis> KEYS a??
> 
> (empty array)
> 
> redis> KEYS *
> 
> (empty array)
> 
> 
> 
> i am getting on different output on  dice-cli

What are you getting? I had got this output using redis cli, assumed it would be same for dice too

**Comment by swarajrb7** [comment]
This is the output i got on redis
![Screenshot from 2024-10-15 16-17-58](https://github.com/user-attachments/assets/6d3f621b-c982-47aa-aaa1-c649cf5028b2)

and this is the output i got on diceDB
![Screenshot from 2024-10-15 12-53-36](https://github.com/user-attachments/assets/d32544d3-3ba1-4f69-b5bc-1735bb6ef872)
@JyotinderSingh

**Comment by tren03** [comment]
![2024-10-15-211657_1260x1034_scrot](https://github.com/user-attachments/assets/ae17ee0a-3606-4558-bade-77c367012760)

I was not able to recreate the issue too
the left side is the dicedb cli and the right side is the redis cli
@JyotinderSingh

**Comment by swarajrb7** [comment]
@JyotinderSingh 
Not a issue

**Comment by JyotinderSingh** [comment]
Turns out this is only happening because I was testing it in multi-threaded mode since the command is not yet well supported there. This is expected and will be fixed as a separate issue. Thanks everyone for chipping in.
