### ISSUE TITLE
Inconsistent `TTL`: DOCS 

### ISSUE THREAD

**Issue by vanshavenger** [DiceDB/dice#1106]
## Steps to reproduce

SET newkey "value"
 TTL newkey value
 

## Expected output In the DOCS

```
(error) ERROR syntax error
```

## Observed output in the CLI

```
(error) ERR wrong number of arguments for 'ttl' command
```

## Expectations for resolution

This issue will be considered resolved when the following things are done

1. changes in the docs to (error) ERR wrong number of arguments for 'ttl' command, to make it consistent with the DOCs.

I found this, when i was lookinf for the commands which output golang error.

**Comment by apoorvyadav1111** [comment]
Hi @vanshavenger , Is this available for others to pick up? please let me know if you would like to work on this.
Thanks

**Comment by vanshavenger** [comment]
@apoorvyadav1111 Making changes in the DOCs, You can assign it to me.

**Comment by apoorvyadav1111** [comment]
Assigned 🚀
