### ISSUE TITLE
Inconsistent `BF`: Bloom Filter commands are inconsistent with Redis output 

### ISSUE THREAD

**Issue by apoorvyadav1111** [DiceDB/dice#1110]
Found while working on #1031 

## Steps to reproduce

```
127.0.0.1:7379> bf.add k 1
(integer) 0
127.0.0.1:7379> bf.info k
name: k, error rate: 0.010000, capacity: 1024, total bits reserved: 10344, bits per element: 9.585058, hash functions: 7
```

## Expected output

The expected output when the above set of commands (maybe when run on Redis)

```
127.0.0.1:6379> bf.info k
 1) Capacity
 2) (integer) 100
 3) Size
 4) (integer) 240
 5) Number of filters
 6) (integer) 1
 7) Number of items inserted
 8) (integer) 1
 9) Expansion rate
10) (integer) 2
```

## Observed output

The observed output when the above set of commands when run on DiceDB

```
127.0.0.1:7379> bf.info k
name: k, error rate: 0.010000, capacity: 1024, total bits reserved: 10344, bits per element: 9.585058, hash functions: 7
```

## Expectations for resolution

This issue will be considered resolved when the following things are done

1. changes in the [`dice`](https://github.com/dicedb/dice) code to meet the expected behavior
2. addition of relevant test case to ensure we catch the regression

You can find the tests under the `integration_tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [setup DiceDB locally](https://github.com/dicedb/dice)
- [setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [setup DiceDB CLI](https://github.com/dicedb/dice)

**Comment by vpsinghg** [comment]
@apoorvyadav1111 can I pick this up ?

**Comment by apoorvyadav1111** [comment]
Hi @vpsinghg, Thank you for your interest to close this issue. However, this issue is part of another issue I an assigned to and I created this for tracking purposes.
