### ISSUE TITLE
Docs: Improve HTTP and Websocket documentation

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#1113]
The HTTP and WebSocket documentation on dicedb.io needs to include some example curl requests to make it easier for users to follow along and try these features.

The documentation page should include corresponding curl requests for each of the examples. Also specify the expected output of each of these commands to these curl requests.

**Comment by JP-sDEV** [comment]
Hi @JyotinderSingh, could I be assigned this issue?

**Comment by JyotinderSingh** [comment]
> Hi @JyotinderSingh, could I be assigned this issue?

It looks like @vanshavenger already raised a PR for this. So I am assigning it accordingly.

@vanshavenger, thanks a lot for the PR. However, it is always a good practice to comment on an issue first and wait for it to be assigned to you before beginning to work on it. This can prevent duplicate work from being done by more people.

**Comment by vanshavenger** [comment]
@JyotinderSingh sure, my bad. I saw the issue and started working on it. 

@JP-sDEV If you want you can do the changes in the WebSocket Docs. I have made changes in the HTTP Docs

**Comment by JP-sDEV** [comment]
@vanshavenger sounds good, thanks! Will review your PR to follow your doc styling.
