### ISSUE TITLE
Fix unreachable code in stormSet function

### ISSUE THREAD

**Issue by Thedarkmatter10** [DiceDB/dice#113]
**Describe the bug**
The bug is related to unreachable code in the function `stormSet`.

**To Reproduce**
1. Call the `stormSet` function.
2. Observe the "unreachable code" error.

**Expected behavior**
The function `stormSet` should execute without any errors, and all code within the function should be reachable and functional.

**Additional context**
This issue occurs because the `conn.Close()` statement is unreachable due to a preceding `return` statement. To fix the issue, we need to rearrange the code or use `defer` to ensure proper cleanup of resources.

**Comment by divyansh2375** [comment]
i want to work on this issue @Thedarkmatter10  can you please assign it to me

**Comment by Rajan-226** [comment]
@Thedarkmatter10 @JyotinderSingh This seems to be already closed.
