### ISSUE TITLE
Inconsistent ZRANK: When WITHSCORE is used with ZRANK the score should be returned as string rather than integer

### ISSUE THREAD

**Issue by shashi-sah2003** [DiceDB/dice#1165]
## Steps to reproduce
```bash
ZADD myzset 1 "one"
ZADD myzset 2 "two"
ZADD myzset 3 "three"
ZRANK myzset "three"
ZRANK myzset "four"
ZRANK myzset "three" WITHSCORE
```

## Expected output

![image](https://github.com/user-attachments/assets/53bb6021-9586-4010-8fd0-900491d24bde)

The expected output when the above set of commands when run on Redis

## Observed output

![image](https://github.com/user-attachments/assets/4a5998a5-f6c2-4963-a64a-aae97b0ddec4)

The observed output when the above set of commands when run on DiceDB

The steps to run the test cases are mentioned in the README of the [dice-tests repository](https://github.com/AshwinKul28/dice-tests).

## Expectations for resolution

This issue will be considered resolved when the following things are done

1. changes in the [`dice`](https://github.com/dicedb/dice) code to meet the expected behavior
8. Successful run of the tcl test behavior

You can find the tests under the `tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [setup DiceDB locally](https://github.com/dicedb/dice)
- [setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [setup DiceDB CLI](https://github.com/dicedb/dice)

**Comment by shashi-sah2003** [comment]
@JyotinderSingh @lucifercr07 I would like to take this  !!

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh @lucifercr07 I would like to take this  !!

Assigned, this might require you to make some changes in the SDK as well (check if the results for the `.WATCH` variant of this command in zrangewatch_test.go file are still correct, if not then please make the changes there as well)

**Comment by apoorvyadav1111** [comment]
Hi @JyotinderSingh @shashi-sah2003 ,  In redis, scores are stored as strings. We might need to ensure we either store them as strings after validating the float64 or we might to ensure each command parses it when withscores is used.
`
The score values should be the string representation of a double precision floating point number. +inf and -inf values are valid values as well.


`

**Comment by shashi-sah2003** [comment]
@JyotinderSingh @lucifercr07 pls review this PR https://github.com/DiceDB/dice/pull/1166
