### ISSUE TITLE
Refactor Websocket server parser to support space char in values

### ISSUE THREAD

**Issue by lucifercr07** [DiceDB/dice#1191]
## Description

- Ref: https://github.com/DiceDB/dice/issues/1029#issuecomment-2435065742
- For string value with a space (e.g., "name":"New York"), the command parsing and argument splitting in the command parser for websocket server, does not handle this scenario correctly.
- Refactor parser to handle such scenarios
- We can refer to httpServer parser for references.

## Tasks
- Refactor websocket server command parser to support space char as key values.
- Add tests for the given scenario.

**Comment by ayushsatyam146** [comment]
I can take this up @lucifercr07

**Comment by helios2003** [comment]
Hi @lucifercr07, I am new to the community and would love to take up this issue. Can you assign it to me?

**Comment by vpsinghg** [comment]
@helios2003 let me know incase any details are required for recreating this issue.

**Comment by helios2003** [comment]
I have a small question here: Should the key and value both be able to handle in-between spaces or is it only for the value?
