### ISSUE TITLE
websocket integration tests missing for Command Docs

### ISSUE THREAD

**Issue by sa-k-shore** [DiceDB/dice#1192]

**Comment by sa-k-shore** [comment]
@lucifercr07  created new issue for missing tests

**Comment by sa-k-shore** [comment]
@lucifercr07  i havn't worked on this will work on this weekend

**Comment by sa-k-shore** [comment]
hi @lucifercr07  what type of IT in websocket should i add for command docs it is just a retrieval command

**Comment by sa-k-shore** [comment]
I have added other IT in http and async . so i want to know if i should do something in websocket as i believe it would be a simple call just like async and http

**Comment by sa-k-shore** [comment]
@lucifercr07  can you review #1323

**Comment by sa-k-shore** [comment]
@lucifercr07  i think i dont understand complete architecture for this project should i just read architecture of redis , can you guide me on that part to understand what to look into , thanks

**Comment by lucifercr07** [comment]
Closing, merged as part of https://github.com/DiceDB/dice/pull/1323
