### ISSUE TITLE
Enhancement: `Append` to support other datatypes

### ISSUE THREAD

**Issue by apoorvyadav1111** [DiceDB/dice#1193]
Hi team,

Command `Append` has recently been migrated and missed support for all available datatypes. We need to make it consistent with Redis. For more context, please go through #1095 comments and unresolved review comments. 

Requirements:

- [ ] All datatypes are supported and error handling must be consistent. 
- [ ] updating unit tests to cover new enhancement
- [ ] updating all integration test to test new enhancement
- [ ] documentation updates with new enhancement

Thanks

**Comment by shashi-sah2003** [comment]
@apoorvyadav1111 if noone is assigned on this then I would like to take this
thanks

**Comment by apoorvyadav1111** [comment]
Thanks for picking this up @shashi-sah2003.

**Comment by shashi-sah2003** [comment]
@apoorvyadav1111 the command `APPEND` works only with string datatype and it will throw error when used with other datatype
you want me to check for all the other datatypes if it's throwing error or not?

**Comment by apoorvyadav1111** [comment]
Hi @shashi-sah2003 , yes please, we need to handle all datatypes which should be stringified. We need to be consistent with redis, hence, please check the behavior on redis.

**Comment by shashi-sah2003** [comment]
![image](https://github.com/user-attachments/assets/55d8c84e-c892-4c89-98b4-2f4027ae3df4)
@apoorvyadav1111 when I'm trying to append in sorted set then it should give relevant error but the server is being closed immediately and the below error is appeared on terminal, rest all other datatypes is giving relevant error/output
![image](https://github.com/user-attachments/assets/b367de06-cca3-401b-8488-a8127d9efac8)

**Comment by shashi-sah2003** [comment]
@apoorvyadav1111 I have created draft PR for the above issue with `APPEND` command pls review it https://github.com/DiceDB/dice/pull/1233
thanks

**Comment by c-harish** [comment]
> @apoorvyadav1111 I have created draft PR for the above issue with `APPEND` command pls review it #1233 also how should I go about fixing this issue or from where it is arising from? thanks

Hi @shashi-sah2003. Are you working on this panic exit? If not, I can raise a fix for it.

**Comment by apoorvyadav1111** [comment]
Hi @shashi-sah2003 , I ll take a look today afternoon and we can move ahead from there.

Thanks,
Apoorv

**Comment by shashi-sah2003** [comment]
> > @apoorvyadav1111 I have created draft PR for the above issue with `APPEND` command pls review it #1233 also how should I go about fixing this issue or from where it is arising from? thanks
> 
> Hi @shashi-sah2003. Are you working on this panic exit? If not, I can raise a fix for it.

Hey @c-harish I have been assigned this issue and working on it. Instead it would be helpful if you can give your insight on solving this issue?
