### ISSUE TITLE
Enhancement `GETRANGE` to support all available datatypes

### ISSUE THREAD

**Issue by apoorvyadav1111** [DiceDB/dice#1194]
Hi team,

Command `GETRANGE` has recently been migrated and missed support for all available datatypes. We need to make it consistent with Redis. For more context, please go through #1095 comments and unresolved review comments. 

Requirements:

- [ ] All datatypes are supported and error handling must be consistent. 
- [ ] updating unit tests to cover new enhancement
- [ ] updating all integration test to test new enhancement
- [ ] documentation updates with new enhancement

Thanks

**Comment by c-harish** [comment]
@apoorvyadav1111 Can i pick this up?

**Comment by apoorvyadav1111** [comment]
Hi @c-harish, Thanks for picking this up.
