### ISSUE TITLE
Machine freezes after hiting GET curl request

### ISSUE THREAD

**Issue by gods-mack** [DiceDB/dice#12]
1. I cloned your repo
2. ran `go run main.go`
3. and, just for curiosity, did `curl HTTP://0.0.0.0:7379`
 after that machine freezes ( htop stats showing 80% RAM consumed by `go-build`)

**Comment by rohanverma94** [comment]
Redis protocol aka RESP is TCP based. **HTTP/HTTPS has no role to play in this**. ``curl`` allocates the predefined memory for a standard set of protocols and RESP/TCP is not one of them.

``curl HTTP://0.0.0.0:7379`` **is invalid in the first place.**

However high memory usage could come either from DB or curl itself. Try profiling DB with **pprof**,  you might be able to bifurcate the cause of heap allocation.

**Comment by rohanverma94** [comment]
I can reproduce the issue, this is due to "Cross Protocol Scripting", redis already have hardened server implementation to block cross-protocol application.  The leaked allocation happens only outside of golang's runtime. And within golang's runtime, there is no leaked memory as shown below -

![image](https://user-images.githubusercontent.com/8470490/195981571-d713e1da-e84f-43ac-adbc-68ede368f42a.png)

So to block "Cross Protocol Scripting", you'd have to close the file descriptor(FD) after knowing that the connection is not coming from any redis-client i.e. you have to add fields in ``type Client struct`` to uniquely identify the redis-compatible client.

**Comment by rohanverma94** [comment]
@arpitbbhayani I've written a patch to "Disable Cross Protocol Scripting" here https://github.com/rohanverma94/dice/commit/ce29fa5acbba9e02ca6abbc43e82a353c5e7a8d6

Now curl behaves like following
```
curl -v -f http://0.0.0.0:7379
*   Trying 0.0.0.0:7379...
* Connected to 0.0.0.0 (127.0.0.1) port 7379 (#0)
> GET / HTTP/1.1
> Host: 0.0.0.0:7379
> User-Agent: curl/7.82.0
> Accept: */*
> 
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server
```

And server shows the following log-
```
2022/10/16 04:32:01 Possible SECURITY ATTACK detected. This is likely due to an attacker attempting to use Cross Protocol Scripting to compromise your instance. Connection aborted.
```

Please review.

**Comment by shubham-chhimpa** [comment]
@gods-mack  I tried locally in docker container (inside a window machine)

```(printf 'CMD1CMD2CMD3';) | nc localhost 7379```

the above command freezes the machine and then the container closes.

```(printf '*1\r\n$4\r\nPING\r\n*3\r\n$3\r\nSET\r\n$1\r\nk\r\n$1\r\nv\r\n*2\r\n$3\r\nGET\r\n$1\r\nk\r\n';) | nc localhost 7379```

This command works fine.

![image](https://user-images.githubusercontent.com/38981756/196020028-9b41d060-12c4-426d-8faf-1c0ba87abf77.png)



cc : @rohanverma94 @arpitbbhayani

**Comment by rohanverma94** [comment]
> @gods-mack I tried locally in docker container (inside a window machine)
> 
> `(printf 'CMD1CMD2CMD3';) | nc localhost 7379`
> 
> the above command freezes the machine and then the container closes.
> 
> `(printf '*1\r\n$4\r\nPING\r\n*3\r\n$3\r\nSET\r\n$1\r\nk\r\n$1\r\nv\r\n*2\r\n$3\r\nGET\r\n$1\r\nk\r\n';) | nc localhost 7379`
> 
> This command works fine.
> 
> ![image](https://user-images.githubusercontent.com/38981756/196020028-9b41d060-12c4-426d-8faf-1c0ba87abf77.png)
> 
> cc : @rohanverma94 @arpitbbhayani

Yes, already confirmed the issue. This patch solves it .

**Comment by gods-mack** [comment]
> 

Hi @rohanverma94 
I tried your version, I ran it via Docker in Mac M1.
still, it's running like Volcano. I think there is something wrong with MM or maybe parallelism (idk)
<img width="366" alt="Screenshot 2022-10-16 at 6 06 22 PM" src="https://user-images.githubusercontent.com/31279522/196035728-71414f4f-caf5-48f6-b818-44082f50f675.png">

**Comment by rohanverma94** [comment]
Nope, perfectly working fine for me. May be you're applying the patch the wrong way.
Do this -
```
git clone https://github.com/rohanverma94/dice.git
cd dice
git checkout develop
```
Then usual go build

**Comment by gods-mack** [comment]
> 

Yeah, Its working fine now,
great

**Comment by rohanverma94** [comment]
As @gods-mack validated the fix. @arpitbbhayani can you review it - https://github.com/DiceDB/dice/issues/12#issuecomment-1279848727

**Comment by arpitbbhayani** [comment]
@rohanverma94 patch looks solid. Can you raise a PR?

**Comment by rohanverma94** [comment]
@arpitbbhayani Fine I'll raise a PR

**Comment by arpitbbhayani** [comment]
Thanks @gods-mack for raising and @rohanverma94 for fixing 🍻
