### ISSUE TITLE
Supporting wildcard FROM, ORDER BY $value and LIMIT in DSQL

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#120]
Each client connected to DiceDB will do two things

1. Keep emitting its score into the key `match:<mid>:user:<uid>` and the score is an integer, say `92`
2. Imagine end users playing, and doing some activity, and this leads to incr in score by one, and in DiceDB the score of individual users is stored encapsulated within the match.

```
match:100:user:A ----> 92
match:100:user:B ----> 99
match:100:user:C ----> 82
```

3. Each backend client `QWATCH`es to `DSQL` which gives them the top `5` KV pairs in the descending order of `$value`. The `QWATCH` command each backend client would fire will be

```
> QWATCH 'SELECT $key, $value FROM match:100:* ORDER BY $value DESC LIMIT 5;'
```

Note: `$key` and `$value` are special variables that the clients can refer to when they want to access key and value in the resultset.

The output of the above command will be the list of projected columns (`$key`, and `$value` in this case) sent as list of tuples in RESP encoded form. The JSON equivalent of the response is

```json
[
    ["match:100:user:B", 99],
    ["match:100:user:A", 92],
    ["match:100:user:C", 82]
]
```

**Comment by JyotinderSingh** [comment]
Done in #124
