### ISSUE TITLE
New fixes in the CI

### ISSUE THREAD

**Issue by kitarp29** [DiceDB/dice#1260]
As discussed here: https://github.com/DiceDB/dice/pull/1116#issuecomment-2455390991
I am opening a new issue for these two changes in the CI
- Conditional triggering of linting and Testing pipeline when changes are done to only .go file (This can change if the project ever changes/includes anything other than go)
- Caching setup for the linting job as well

Please make it open for all, since it's a simple change for beginners. If no one does it in a week or so.
I will make a PR against it

cc: @JyotinderSingh

**Comment by bhima2001** [comment]
Hey I can take this up.

**Comment by kitarp29** [comment]
I am not the maintainer or the repo, but I suggest you work on the changes. They should not take more than an hour (see the changes I made earlier).

**Comment by bhima2001** [comment]
@kitarp29 Hey, Is there any way I can test the workflow locally? Thanks

**Comment by kitarp29** [comment]
Make a fork of this project on your account.
On your clone:
1. Have the CI changes in main branch
2. Make a branch out of this branch. Make commits on that branch it would help you to test the changes in the fashion you wish to.

If satisfied make a PR with the main branch of your fork
