### ISSUE TITLE
Linking Docs & Similar commands

### ISSUE THREAD

**Issue by apoorvyadav1111** [DiceDB/dice#1324]
Hi team,

Currently, if we mention another command in one command's documentation, it is not hyperlinked, hence user has to look up and go to the page manually. We would like to have all such mentions linked to each other via links for improved user experience. The scope of the issue is all the commands. For example:

<img width="784" alt="image" src="https://github.com/user-attachments/assets/d6817d38-cfe0-46df-9c38-6e3672691000">
In BITFIELD_RO, we mention BITFIELD  but it is not a link. A link  would have improved the experience. There are many such mentions.

Acceptance Criteria:
- All such commands, except those not documented but mentioned, are linked to each other via relative URLs.
- Any command having another command which have same functionality, for example, HMSET, HSET, are mentioned under **Notes** section. 

This might be a widely scoped task so please reach out to us on Discord if you have any questions.

**Comment by pankajjs** [comment]
@apoorvyadav1111 Could you assign this ticket to me?
