### ISSUE TITLE
GETRANGE doc not present in dicedb.io

### ISSUE THREAD

**Issue by Arijit6258** [DiceDB/dice#1326]
Documentation of the GETRAGNE command is not present in [dice db commands](https://dicedb.io/commands/getrange) .

I want to work on this - 

1. Adding the documentation.
2. Implementing the command in dice db.

I am new to contributing here. Will you please assign this and help me with the next steps @arpitbbhayani @JyotinderSingh @apoorvyadav1111 

![Screenshot 2024-11-24 at 12 44 00 PM](https://github.com/user-attachments/assets/66d2c081-3aa4-4a63-9610-9e8dc6df3d31)

**Comment by apoorvyadav1111** [comment]
Hi Arijit, thanks for finding this issue. Please note that DiceDB does support GETRANGE but misses the documentation, Please follow the templates present in docs folder or any documentation of the command.
