### ISSUE TITLE
Remove usage of `validator` function in `eval_test.go`

### ISSUE THREAD

**Issue by lucifercr07** [DiceDB/dice#1387]
## Issue:
- We've migrated all the commands to new eval format, however we still have few unit test cases still using old output format.
![image](https://github.com/user-attachments/assets/ac6119a4-216f-4172-a2c0-c3b827b8fdf0)

As part of this issue:
1. Analyse the references of `validator      func(output []byte)` in `evalTestCase` struct.
2. Remove the reference and update the test cases to implement `newValidator   func(output interface{})`
3. If all the references are removed, we can delete the `validator      func(output []byte)` from `evalTestCase` struct.

**Comment by c-harish** [comment]
@lucifercr07, Can i pick this up?

**Comment by lucifercr07** [comment]
@c-harish assigned, thanks for contributing.

**Comment by ChetanNagane** [comment]
Hi @c-harish  i believe you already have issue in your hand [#1250 ](https://github.com/DiceDB/dice/issues/1250) can you please let me take up this issue.

**Comment by c-harish** [comment]
> Hi @c-harish i believe you already have issue in your hand [#1250 ](https://github.com/DiceDB/dice/issues/1250) can you please let me take up this issue.

Hi, @ChetanNagane. I have a blocker on #1250. So went ahead with his one.
