### ISSUE TITLE
Incorrect format verb used in function AcceptConnectionRequests

### ISSUE THREAD

**Issue by Ashishkapil** [DiceDB/dice#1398]
## Steps to reproduce
Run the application in Debug mode and try to log error in default case of AcceptConnectionRequests() (please see screenshot)

![image](https://github.com/user-attachments/assets/8934fdf5-c519-4a7e-8e7d-df8782f2dbe2)

## Expected output

The output should be a clear error log message

## Observed output

Please see attached screenshot

## Expectations for resolution

This issue will be considered resolved when the following things are done

1. The error message logs a clear human readable message

**Comment by lucifercr07** [comment]
@Ashishkapil assigned, thanks for contributing.
