### ISSUE TITLE
Groundwork for DiceDB load tests and memtier benchmark

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#140]
One `Make` target will run the [memtier benchmark](https://github.com/RedisLabs/memtier_benchmark) on a cloud VM and capture the report. Look at the tunables of the benchmark, and infrastructure configuration and expose them as parameters that we can pass while running the script.

Also, let's define a a set of tests that we always run for some common presets.

**Comment by Dev79844** [comment]
Hello @arpitbbhayani!
I would like to work on this issue. Please assign it to me

**Comment by Dev79844** [comment]
Hello @arpitbbhayani!
I would like to work on this issue. Please assign it to me

**Comment by arpitbbhayani** [comment]
@Dev79844 we already have a primitive Pulumi script ready, you can build on top of that.

**Comment by Dev79844** [comment]
Hello @arpitbbhayani!
Created  a PR for this issue #323

**Comment by AshwinKul28** [comment]
Thanks for the contribution, Closing this.

Status - shipped 🚀
