### ISSUE TITLE
Add support for `AUTH` command

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#141]
Add support for the `AUTH` command in DiceDB similar to [Redis' `AUTH` Command](https://redis.io/docs/latest/commands/auth/). Please refer to how `AUTH` is implemented in [Redis](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by manosriram** [comment]
Can i work on this @arpitbbhayani ?

**Comment by gauravsarma1992** [comment]
## Redis functionality
Prior to Redis 6, authentication for a connection was enabled by passing in `requirepass` in the redis.conf or while starting the redis server. If the above config is set, prior to any command, the authentication has to be by running the following command:
```
AUTH '<password>'
```

After Redis 6, the concept of ACLs was introduced which allowed users to define a combination of users with multiple passwords per user. ACLs also provided the ability to restrict usage based on Commands, Channels, Keys, etc.

Some ACL functionalities from the [Redis documentation](https://redis.io/docs/latest/operate/oss_and_stack/management/security/acl/) can be found here :
- Enable and disallow users
- Allow and disallow commands
- Allow and disallow certain keys and key permissions
- Allow and disallow Pub/Sub channels
- Configure valid passwords for the user
- Configure selectors for the user

## Implementation phases
The implementation for the AUTH should be broken down into the following phases:
1. Allow users to define Username/Password(s) combination and perform authentication on the configured input
2. Provide authorisation actions on different objects using ACLs.

**Comment by gauravsarma1992** [comment]
I created a WIP PR for to support the AUTH command based on the Redis authentication parameters. https://github.com/DiceDB/dice/pull/179

**Comment by gauravsarma1992** [comment]
@arpitbbhayani @JyotinderSingh Please assign this task to me.

**Comment by JyotinderSingh** [comment]
> @arpitbbhayani @JyotinderSingh Please assign this task to me.

Assigned

**Comment by romanchechyotkin** [comment]
hello, can u assign me for this task

**Comment by hanshal101** [comment]
I can work on this !!!

**Comment by gauravsarma1992** [comment]
@JyotinderSingh Looks like I will not be able to spend much time on this issue this week. You can assign the issue to someone else if it's required a little earlier.
For others, there is a draft PR that you may want to take up https://github.com/DiceDB/dice/pull/179

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh Looks like I will not be able to spend much time on this issue this week. You can assign the issue to someone else if it's required a little earlier.
> 
> For others, there is a draft PR that you may want to take up https://github.com/DiceDB/dice/pull/179

You already have significant progress on the issue, Gaurav. I would recommend you stick with it. No rush to complete this, please take your time.

However, if you do want to give up this issue, let me know.

**Comment by gauravsarma1992** [comment]
Thanks @JyotinderSingh , I will continue on the same and will try to have a reviewable PR by the weekend

**Comment by soumya-codes** [comment]
I can take this up...

**Comment by romanchechyotkin** [comment]
but u can publish PR in order to other guys can continue this task

**Comment by gauravsarma1992** [comment]
@JyotinderSingh can you assign it to me?

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh can you assign it to me?

Assigned

**Comment by arpitbbhayani** [comment]
https://github.com/DiceDB/dice/pull/179

**Comment by VipinRaiP** [comment]
@gauravsarma1992 Are you going to support ACL  in the same PR?
