### ISSUE TITLE
Add support for byte array as a datatype

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#142]
We need a way to support long byte arrays as native type in DiceDB and for this, we need to converge on a good way to implement it including the storage, access, and modify.

Note: This issue is not about implementing all the commands, but rather a way to support the long binary arrays.

Hence, we need to do the following

1. figure out the best way to implement long bye arrays (not growable)
2. the underlying storage layer should support bit manipulation
3. it should be easier to restore the entire byte array, get the byte array

Here's a [quick prototype](https://gist.github.com/arpitbbhayani/b5a01b12bfac08bd618e7f6801b912e0) that shows that we cannot do an in-place bit manipulation of string in Go.

**Comment by yashs360** [comment]
@arpitbbhayani @JyotinderSingh Could you assign this to me, i'd like to spend some time taking a stab at it.

**Comment by arpitbbhayani** [comment]
@yashs360 Done. Let us know once you build an understanding.

**Comment by yashs360** [comment]
This can be closed.
