### ISSUE TITLE
 Add support for `COMMAND` command

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#144]
Add support for the `COMMAND` command in DiceDB similar to the [`COMMAND` command in Redis](https://redis.io/docs/latest/commands/command/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by kakdeykaushik** [comment]
I would like to work on it. Can you please assign this issue to me ?

**Comment by maniSHarma7575** [comment]
@kakdeykaushik Are you still working on this? Or I can pick it up?

**Comment by kakdeykaushik** [comment]
@maniSHarma7575 i'm working on it

**Comment by rohithputha** [comment]
Hey @kakdeykaushik, are you still working on this or is it done?

**Comment by kakdeykaushik** [comment]
you can work on it @rohithputha

**Comment by rohithputha** [comment]
I would like to work on this, can this be assigned to me?

**Comment by aashraybhandar1** [comment]
Hey @rohithputha  are you working on it?

**Comment by AshwinKul28** [comment]
@rohithputha thanks for picking this up. Can you please add any latest updates on this? Let us know if you have any blockers on this we can discuss this over the discord. 
if user is inactive and @aashraybhandar1 wants to work on it, we can assign it.

cc @JyotinderSingh

**Comment by rohithputha** [comment]
Hey. I am currently not working on this. you can assign this to @aashraybhandar1 
cc @AshwinKul28 @JyotinderSingh

**Comment by JyotinderSingh** [comment]
> Hey @rohithputha  are you working on it?

Assigned to you.

**Comment by AshwinKul28** [comment]
Hello @aashraybhandar1 Hope you are doing well, any updates on this?

**Comment by aashraybhandar1** [comment]
Hey @AshwinKul28 working on the issue, will have a PR sometime this week

**Comment by aashraybhandar1** [comment]
Hey @AshwinKul28  raised a PR, would appreciate feedback

**Comment by lucifercr07** [comment]
Closing this issue, as [PR](https://github.com/DiceDB/dice/pull/458) is merged. Thanks @aashraybhandar1 for contributing.
