### ISSUE TITLE
 Add support for `COMMAND GETKEYS` command

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#147]
Add support for the `COMMAND GETKEYS` command in DiceDB similar to the [`COMMAND GETKEYS` command in Redis](https://redis.io/docs/latest/commands/command-getkeys/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by Yonggiee** [comment]
Hey @kakdeykaushik, can I confirm if you are currently working on this issue? If not, I would like to work on this.

**Comment by kakdeykaushik** [comment]
I'm not working on this `GETKEYS` please go ahead to pick it up.

**Comment by arpitbbhayani** [comment]
@Yonggiee I have assigned the issue to you. Thanks.
