### ISSUE TITLE
 Add support for `COMMAND INFO` command

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#148]
Add support for the `COMMAND INFO` command in DiceDB similar to the [`COMMAND INFO` command in Redis](https://redis.io/docs/latest/commands/command-info/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by shashankdaima** [comment]
I have created a shallow PR as WIP. #151

**Comment by maniSHarma7575** [comment]
@shashankdaima Are you still working on this?

If not, @arpitbbhayani , @JyotinderSingh Could you please assign this to me?

**Comment by JyotinderSingh** [comment]
> @shashankdaima Are you still working on this? I don't see any activity on this from couple of weeks
> 
> 
> 
> If not, @arpitbbhayani , @JyotinderSingh Could you please assign this to me?

Assigned to you.

**Comment by sanimesh96** [comment]
Hi @maniSHarma7575, Are you still working on this? I dont see any activity on this issue so far.
If not, i would like to take up this issue. Can you assign this to me?
cc: @JyotinderSingh,@arpitbbhayani.

**Comment by JyotinderSingh** [comment]
> Hi @maniSHarma7575, Are you still working on this? I dont see any activity on this issue so far.
> 
> If not, i would like to take up this issue. Can you assign this to me?
> 
> cc: @JyotinderSingh,@arpitbbhayani.

Assigned

**Comment by AshwinKul28** [comment]
@sanimesh96 Any latest updates on this? Please pull the latest from the master in the PR and move it from Draft to Review.

**Comment by AshwinKul28** [comment]
https://github.com/DiceDB/dice/pull/326#issuecomment-2325343608

**Comment by arpitbbhayani** [comment]
@sanimesh96 any updates on this? we would like to close this as soon as possible. Do you need any help?

**Comment by JyotinderSingh** [comment]
This issue is available to be taken up.

**Comment by psrvere** [comment]
@JyotinderSingh - Please assign to me

**Comment by meetghodasara** [comment]
@JyotinderSingh I would also like to work on this issue. Please assign it to me. Thanks.

**Comment by gauravrp** [comment]
@JyotinderSingh Can this issue be assigned to me?

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh - Please assign to me

Assigned to @gauravrp for now to allow more people to get involved into contributing.

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh I would also like to work on this issue. Please assign it to me. Thanks.

Assigned to @gauravrp for now to allow more people to get involved into contributing.

**Comment by meetghodasara** [comment]
Hi @JyotinderSingh 
I have submitted a draft PR for the COMMAND INFO implementation. 
Could you please review it and let me know if the response meets the expected requirements?

<img width="893" alt="Screenshot 2024-09-18 at 9 52 49 PM" src="https://github.com/user-attachments/assets/f023e711-8e85-4842-88ae-b42e6db2affd">

`COMMAND INFO`

![image](https://github.com/user-attachments/assets/01d7b3d7-e112-4e54-b5c5-dcb6973cec52)

**Comment by gauravrp** [comment]
@meetghodasara If the PR for this issue has been merged, can we please close it?

**Comment by lucifercr07** [comment]
Closing, merged as part of https://github.com/DiceDB/dice/pull/612
