### ISSUE TITLE
 Add support for `COMMAND LIST` command

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#149]
Add support for the `COMMAND LIST` command in DiceDB similar to the [`COMMAND LIST` command in Redis](https://redis.io/docs/latest/commands/command-list/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by patelajay745** [comment]
I want to work on this .

**Comment by yashs360** [comment]
Hey @patelajay745  I am working on it currently with the PR's linked up. Please pick other issues from the list.

**Comment by KaviiSuri** [comment]
@arpitbbhayani i want to work on this, is it free to pick up? can it be assigned?

**Comment by Harsh-2909** [comment]
@arpitbbhayani @JyotinderSingh  Can I work on this issue if nobody is working on it?

**Comment by JyotinderSingh** [comment]
> @arpitbbhayani i want to work on this, is it free to pick up? can it be assigned?

Assigned

**Comment by JyotinderSingh** [comment]
> @arpitbbhayani @JyotinderSingh  Can I work on this issue if nobody is working on it?

Have assigned to @KaviiSuri since he messaged first. Please have a look at any other open issues or inactive issues which are assigned but not being worked on. Thanks @Harsh-2909!

**Comment by AshwinKul28** [comment]
@KaviiSuri Thanks a lot for picking this up. Do you have any latest updates on this? If you have any blockers lets discuss this over the Discord.

**Comment by KaviiSuri** [comment]
Hey @AshwinKul28 , i had issues with my system for the past week and only got it back this sunday.

It seems like someone else completed the issue in the meanwhile. Is there anything else i can pickup or contribute too?
