### ISSUE TITLE
need inline documentation on why BGREWRITEAOF forked a process

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#16]
**Following functions need better comments**

Here is a list of files along with the lines highlighted that need better comments making it easier to understand what's happening

- https://github.com/DiceDB/dice/blob/master/core/eval.go#L170-L176

**Here's why I think it is difficult to understand the code**

understanding how we are forking, referring to Go doc for that, and the reason for doing it would help.

**Comment by rohanverma94** [comment]
Added inline documentation, please review. 
https://github.com/DiceDB/dice/compare/master...rohanverma94:dice:stable-tested
