### ISSUE TITLE
Add support for JSON as a datatype

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#165]
We need to support JSON as a datatype for values. 

Please look at the [redis documentation](https://redis.io/docs/latest/develop/data-types/json/) to understand how the Redis JSON datatype behaves and the commands required to manipulate JSON data.

# Expected features
* Complete support for JSON standard.
* Support for `JSON.SET` command.
* Support for `JSON.GET` command.
* Support for partial updates.

You will also need to figure out an efficient way to represent JSON objects internally.

**Comment by MohitVachhani** [comment]
Hey @JyotinderSingh , is someone going to pick this up ? If not then I can give it a try!

**Comment by JyotinderSingh** [comment]
> Hey @JyotinderSingh , is someone going to pick this up ? If not then I can give it a try!

Assigned

**Comment by MayukhSobo** [comment]
@arpitbbhayani I want to take this up.

**Comment by JyotinderSingh** [comment]
> @arpitbbhayani I want to take this up. 

Hi, this issue is already assigned to someone. Please feel free to pick up another unassigned issue.

**Comment by arpitbbhayani** [comment]
@Maveric-k07 Go for it. I agree https://github.com/DiceDB/dice/issues/166 and this are closely related.
