### ISSUE TITLE
Replace regex matching with wildcard matching for DSQL queries

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#167]
Presently, the DSQL selector clause is treated as a regex matcher, however, the feature set implementation is limited to wildcard matching (and plans to stay like that for the foreseeable future).

It will be more efficient to update this to a pure wildcard matching logic for better efficiency.

Reference: https://github.com/DiceDB/dice/blob/master/core/regex.go

**Comment by Dev79844** [comment]
Hey
I would like to work on this issue.

**Comment by JyotinderSingh** [comment]
> Hey I would like to work on this issue.

Assigned.

**Comment by Dev79844** [comment]
Added a PR #169
