### ISSUE TITLE
Add support for negative integer encoding/decoding.

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#183]
Presently [dencoding/int.go](https://github.com/DiceDB/dice/blob/master/core/dencoding/int.go) only supports unsigned integers. 

* Add support for signed integer encoding, this would allow us to support signed integer stacks and queues down the line.
* Add unit tests to validate correctness.
* Benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by Vsareen0** [comment]
Hey @JyotinderSingh if no one has picked it, I would like to give this a go. !

**Comment by JyotinderSingh** [comment]
> Hey @JyotinderSingh if no one has picked it, I would like to give this a go. !

Assigned

**Comment by JyotinderSingh** [comment]
Fixed in #216
