### ISSUE TITLE
Implement test cases for expired keys in QueueRef.Remove() method

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#184]
Description:
The `QueueRef.Remove()` method is designed to remove key references from the queue and handle expired keys. However, there are currently no test cases to verify the behavior of this method when dealing with expired keys.

Write a test which verifies that:
1. The method correctly continues to pop elements until it finds a non-expired key.
2. It properly handles scenarios where all keys in the queue are expired.
3. It correctly returns nil when no valid keys are found in the queue.

Tasks:
1. Add the test case into queueref_test.go.
2. Implement test cases for `QueueRef.Remove()` that cover the following scenarios:
   a. Removing a single non-expired key
   b. Removing multiple non-expired keys in sequence
   c. Removing an expired key followed by a non-expired key
   d. Removing multiple expired keys followed by a non-expired key
   e. Removing all expired keys (queue becomes empty)
   f. Removing from an empty queue
4. Verify that the method returns the correct QueueElement for non-expired keys.
6. Add benchmark to check the behavior with a large number of expired keys.

**Comment by VipinRaiP** [comment]
Shall i work on it?

**Comment by JyotinderSingh** [comment]
> Shall i work on it?

Assigned
