### ISSUE TITLE
Implement test cases for expired keys in StackRef.Pop() method

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#185]
Description:
The `StackRef.Pop()` method is designed to pop key references from the stack and handle expired keys. However, there are currently no test cases to verify the behavior of this method when dealing with expired keys.

Write a test which verifies that:
1. The method correctly continues to pop elements until it finds a non-expired key.
2. It properly handles scenarios where all keys in the stack are expired.
3. It correctly returns nil when no valid keys are found in the stack.

Tasks:
1. Add the test case into stackref_test.go.
2. Implement test cases for `StackRef.Pop()` that cover the following scenarios:
   a. Removing a single non-expired key
   b. Removing multiple non-expired keys in sequence
   c. Removing an expired key followed by a non-expired key
   d. Removing multiple expired keys followed by a non-expired key
   e. Removing all expired keys (stack becomes empty)
   f. Removing from an empty stack
4. Verify that the method returns the correct StackElement for non-expired keys.
6. Add benchmark to check the behavior with a large number of expired keys.

**Comment by sourav014** [comment]
hey @JyotinderSingh , would love to pick this up.

**Comment by JyotinderSingh** [comment]
> hey @JyotinderSingh , would love to pick this up.

Assigned

**Comment by JyotinderSingh** [comment]
@sourav014  are you working on this?

**Comment by JyotinderSingh** [comment]
Unassigned due to inactivity

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh i would like to work on this. can you assign it to me?

Assigned
