### ISSUE TITLE
Supporting `NX | XX` in JSON.SET

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#191]
- [ ] Once the `JSON.SET` command is implemented, we need a way to support `NX | XX`.
- [ ] update the documentation https://github.com/dicedb/docs for this.

ref - https://redis.io/docs/latest/commands/json.set/

Also, write unit and integration tests for the command. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by vaibh1297** [comment]
Hey @JyotinderSingh , can I pick this up ?

**Comment by JyotinderSingh** [comment]
> Hey @JyotinderSingh , can I pick this up ?
> 
> 
> 
> 

Assigned, please start work once JSON support is added
