### ISSUE TITLE
Benchmark Executor performance

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#193]
The DSQL executor parses the DSQLQuery object and returns a result set of keys and/or values.

We currently have no benchmark of the performance characteristics of this operation.

## Requirements
- Create a benchmark with large number of keys in the store and validate query performance. It may be a good idea to check performance difference at ~1k, ~10k, ~100k keys in the store.
- benchmark time taken and memory allocs using benchmem.
- test cases should validate different kinds of queries (with/without ordering specified, with/without WHERE clause, with/without complex wildcard matchers)

**Comment by AshwinKul28** [comment]
HI @JyotinderSingh I can pick this up. Since I'm anyway going to dive deeper into the codebase, I can work on the test cases and benchmarking.

**Comment by JyotinderSingh** [comment]
> HI @JyotinderSingh I can pick this up. Since I'm anyway going to dive deeper into the codebase, I can work on the test cases and benchmarking. 

Assigned

**Comment by AshwinKul28** [comment]
HI @JyotinderSingh the plan I'm thinking of is to use a `go-dice` client and populate keys using the `client.JSONSet()` function and then run the benchmarks using the different scenarios suggested above. Does this sound okay?

**Comment by JyotinderSingh** [comment]
> HI @JyotinderSingh the plan I'm thinking of is to use a `go-dice` client and populate keys using the `client.JSONSet()` function and then write the benchmarks using the different scenarios suggested above. Does this sound okay?

JSON support is not yet available on master

**Comment by AshwinKul28** [comment]
I have covered all the cases available in the `executer_test.go` to run the benchmark cases with the keys 100, 1000, 10000, 100000. Here's a report. 

[executerbenchmark_Nx.txt](https://github.com/user-attachments/files/16474519/executerbenchmark_Nx.txt)
