### ISSUE TITLE
Adding unit tests for multiple files

### ISSUE THREAD

**Issue by lucifercr07** [DiceDB/dice#198]
In `core` package many files don't have unit tests associated to them.
Create unit tests for those e.g: `eval.go, commands.go, events.go`.

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh please assign this to me, have started working.
> 
> Don't have access to add labels please add them.

Assigned, also could you create a separate issue for all files? This way more people can contribute and it's easier to track.

**Comment by AshwinKul28** [comment]
Thanks @lucifercr07 for contributing. Closing this issue! Status - shipped 🚀
