### ISSUE TITLE
 Add support for `PX` in `SET` command

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#200]
We already have the `SET` command implemented. Now we need to add support for `PX` option similar to the [`PX` option in Redis](https://redis.io/docs/latest/commands/set/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by SyedMa3** [comment]
Hey @arpitbbhayani , I would like to take this up.

**Comment by arpitbbhayani** [comment]
@SyedMa3 Assigned the issue to you. Go for it.

**Comment by SyedMa3** [comment]
Sure, understandable.

**Comment by SyedMa3** [comment]
completed the task. Waiting for Issue 213 to get resolved.

>Side Note:
The benchmark cli command for `evalSET` needs to have the value of `benchtime` flag less than `100x` since `WatchChannel` is a buffered channel of size 100 and may lead to a deadlock.

**Comment by arpitbbhayani** [comment]
https://github.com/DiceDB/dice/pull/236/
