### ISSUE TITLE
 Add support for `EXAT` in `SET` command

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#202]
We already have the `SET` command implemented. Now we need to add support for `EXAT` option similar to the [`EXAT` option in Redis](https://redis.io/docs/latest/commands/set/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by hanshal101** [comment]
I can work on this !!!

**Comment by arpitbbhayani** [comment]
@hanshal101 you already have one on your place. Let's crack one at a time.

**Comment by adnan-abdullah1** [comment]
@arpitbbhayani  can i take up this one

**Comment by Harsh-2909** [comment]
@arpitbbhayani @JyotinderSingh Can I take this up?

**Comment by arpitbbhayani** [comment]
https://github.com/DiceDB/dice/pull/218

**Comment by arpitbbhayani** [comment]
@Harsh-2909 The issue was already picked and I just merged the implementation. But thank you for going through it.
There are other issues that you may find amusing. Thanks again.

**Comment by Harsh-2909** [comment]
It's fine. I will look for some other issue

**Comment by JyotinderSingh** [comment]
Fixed and Closed with #247
