### ISSUE TITLE
 Add support for `PXAT` in `SET` command

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#203]
We already have the `SET` command implemented. Now we need to add support for `PXAT` option similar to the [`PXAT` option in Redis](https://redis.io/docs/latest/commands/set/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by lucifercr07** [comment]
@arpitbbhayani would like to pick this up.

**Comment by arpitbbhayani** [comment]
@lucifercr07 Assigned the issue to you. Go for it.

It would be awesome if you keep posting updates to this issue so that we know you are working on it. If we see an inactivity of 7 days, we will remove your assignment. This is just to ensure that the project maintains its momentum and others are not blocked on this work.

But it really means a ton to us that you are contributing to this project. Thanks again.
