### ISSUE TITLE
 Add support for `NX` in `SET` command

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#204]
We already have the `SET` command implemented. Now we need to add support for `NX` option similar to the [`NX` option in Redis](https://redis.io/docs/latest/commands/set/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by chanducheryala** [comment]
@arpitbbhayani , i want to work on it, can u please assign to me

**Comment by JyotinderSingh** [comment]
> @arpitbbhayani , i would like to work on this, can u please assign to me

Assigned

**Comment by chanducheryala** [comment]
PR : https://github.com/DiceDB/dice/pull/227
