### ISSUE TITLE
 Add support for `KEEPTTL` in `SET` command

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#206]
We already have the `SET` command implemented. Now we need to add support for `KEEPTTL` option similar to the [`KEEPTTL` option in Redis](https://redis.io/docs/latest/commands/set/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by kakdeykaushik** [comment]
I'd like to work on it. please assign this issue to me.

**Comment by kakdeykaushik** [comment]
@kolharsam 's PR #212 looks neat. He should be assigned to this issue.
