### ISSUE TITLE
Add support for KQueue

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#22]
**Is your feature request related to a problem? Please describe.**
Dice DB does not run on OSX.

**Describe the solution you'd like**
Dice DB currently does not run on OSX because it does not support EPOLL, hence we need to add support for KQueue and do a conditional build.

**Comment by arpitbbhayani** [comment]
Reference Links: https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool

**Comment by rohanverma94** [comment]
Same for the darwin platform(macOS), we have to introduce the right syscall invocations as defined here https://github.com/golang/go/blob/e92853523d11d1e50d89a3c017c5d902aed0596a/src/runtime/sys_darwin.go

This should happen in a new file - ``eval_darwin.go``
