### ISSUE TITLE
Handle INT64_MIN edge case in EncodeInt/DecodeInt

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#221]
The current implementation of EncodeInt and DecodeInt may not correctly handle the minimum 64-bit integer value due to potential overflow in two's complement arithmetic. We need to add a specific test case for this value and ensure correct behavior.
Tasks:

## Requirements
- Add a test case for INT64_MIN in int_test.go
- Verify correct encoding and decoding of INT64_MIN
- If issues are found, implement a fix in EncodeInt and/or DecodeInt functions

**Comment by Vsareen0** [comment]
Hey @JyotinderSingh I would like to pick this.

**Comment by JyotinderSingh** [comment]
> Hey @JyotinderSingh I would like to pick this.

Assigned.
