### ISSUE TITLE
Expand benchmark for EncodeInt and DecodeInt

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#222]
The current benchmark for EncodeInt and DecodeInt only tests positive integers up to MaxInt64. We should expand the benchmarks to cover a wider range of scenarios, including negative numbers and very large numbers.
Tasks:

Create additional benchmark functions or modify the existing one to cover:

- Negative numbers
- Numbers close to INT64_MIN and INT64_MAX

Run benchmarks and analyze results to ensure performance is consistent across different input ranges

**Comment by Vsareen0** [comment]
Hey @JyotinderSingh let me handle #221 and this one.

**Comment by JyotinderSingh** [comment]
> Hey @JyotinderSingh let me handle #221 and this one.

Sure, could you please comment on the other issue too (can't assign unless you have interacted with it)

**Comment by Vsareen0** [comment]
Sure.
