### ISSUE TITLE
Support for hot reload via Air package

### ISSUE THREAD

**Issue by AshwinKul28** [DiceDB/dice#233]
With this package, we can support hot reload. 
https://github.com/air-verse/air

**Comment by AshwinKul28** [comment]
@JyotinderSingh Please assign it to me, I'm giving PR right away.

**Comment by AshwinKul28** [comment]
<img width="697" alt="Screenshot 2024-08-04 at 11 58 08 AM" src="https://github.com/user-attachments/assets/86b4a384-7f75-4aa3-b366-b0eb32f76ed0">

Via air package hot reload can be possible on files such as .go, .tpl, .tmpl, .yaml.

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh Please assign it to me, I'm giving PR right away. 
> 
> 

Assigned
