### ISSUE TITLE
 Add support for `PFADD` command

### ISSUE THREAD

**Issue by Vsareen0** [DiceDB/dice#238]
Add support for the `PFADD` command in DiceDB similar to the [`PFADD` command in Redis](https://redis.io/docs/latest/commands/command-list/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by Vsareen0** [comment]
Assigned to myself.

**Comment by Vsareen0** [comment]
Assigned to myself @JyotinderSingh / @arpitbbhayani

**Comment by arpitbbhayani** [comment]
@Vsareen0 how close are we to completing this? what is ETA?

**Comment by Vsareen0** [comment]
Hey @arpitbbhayani Sorry for the delay, will try to close this by this Sunday.

**Comment by Vsareen0** [comment]
hey @arpitbbhayani Sorry for time consumption, I tried but unable to write implementation for this. You can reassign to someone else.

**Comment by AshwinKul28** [comment]
Thanks @Vsareen0 for the update. 

cc @JyotinderSingh Please open it for everyone and someone else can pick this up.

**Comment by kailashchoudhary11** [comment]
Hey @JyotinderSingh , I would like to take this up.

**Comment by lucifercr07** [comment]
Have started working on this as part of assigned [issue](https://github.com/DiceDB/dice/issues/9).

**Comment by lucifercr07** [comment]
@JyotinderSingh we can close this issue as implemented as part of PR [here](https://github.com/DiceDB/dice/pull/422).
