### ISSUE TITLE
 Add support for `PFCOUNT` command

### ISSUE THREAD

**Issue by Vsareen0** [DiceDB/dice#239]
Add support for the `PFCOUNT` command in DiceDB similar to the [`PFCOUNT` command in Redis](https://redis.io/docs/latest/commands/command-list/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by maniSHarma7575** [comment]
> Or if you have multiple items on the plate, lets open this issue for everyone, and others can pick this up.
Thanks

@AshwinKul28 I can pick this up?

**Comment by lucifercr07** [comment]
Addressed as part of https://github.com/DiceDB/dice/pull/422

**Comment by lucifercr07** [comment]
@JyotinderSingh we can close this issue as implemented as part of PR [here](https://github.com/DiceDB/dice/pull/422).
