### ISSUE TITLE
Add support for `LPUSH` command

### ISSUE THREAD

**Issue by NOS-AE** [DiceDB/dice#244]
Add support for the `LPUSH` command in DiceDB similar to the [`LPUSH` command in Redis](https://redis.io/docs/latest/commands/lpush/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [benchmem](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by tdadadavid** [comment]
Hi @arpitbbhayani, I will like to work on this issue.

**Comment by NOS-AE** [comment]
Is it WIP or can I work on this? `LPOP` `RPUSH` `RPOP` @arpitbbhayani

**Comment by tdadadavid** [comment]
please what is WIP?

**Comment by NOS-AE** [comment]
> please what is WIP?

Work-In-Progree

**Comment by tdadadavid** [comment]
No, i just want to pick this up and start working on it.

**Comment by NOS-AE** [comment]
> No, I want to pick this up and start working on it.
> I am still getting familiar with the codebase.

Oops..I'm self assigning bro.

**Comment by NOS-AE** [comment]
> No, I want to pick this up and start working on it.
> I am still getting familiar with the codebase.

Oops..I'm self assigning bro.

**Comment by tdadadavid** [comment]
okay no problem, I will watch out for these ones `LPOP` `RPUSH` `RPOP`

**Comment by JyotinderSingh** [comment]
> > No, I want to pick this up and start working on it.
> > I am still getting familiar with the codebase.
> 
> Oops..I'm self assigning bro. I think you can also start a new issue like this to request for an assignment.

Assigned

**Comment by NOS-AE** [comment]
#311
