### ISSUE TITLE
Stanardize/Refactor error

### ISSUE THREAD

**Issue by soumya-codes** [DiceDB/dice#248]
As the repo size grows in volume it is important to standardize on the errors. We need to make sure that the shared/common errors are well-defined at one place and reused for different/appropriate use-cases. Currently the same error is being replicated across multiple places. For example the error for wrong syntax(`ERR syntax error`) is duplicated across at-least 9 places. 

Please check [here](https://github.com/redis/redis/blob/e4ddc344635315a494b8a05a5af1c799c44a8f9a/src/server.c#L1862) to see how Redis handles common messages. 

**Important:** Please ensure we use idiomatic go practices while refactoring the code.

**Expected behavior**

The existing functionality shouldn't get effected and all test-cases should pass.

**Comment by lucifercr07** [comment]
@soumya-codes would like to work on this.

**Comment by soumya-codes** [comment]
@lucifercr07 thanks, go for this. @JyotinderSingh please assign.

**Comment by yaten2302** [comment]
Hey @lucifercr07 , may we collaborate on this issue?

**Comment by JyotinderSingh** [comment]
> @soumya-codes would like to work on this.

Assigned

**Comment by pb2582528** [comment]
@lucifercr07  - 

This function creates a new DiceError but returns only its message field, losing the custom error type.

func NewErr(message string) error {
    return newDiceErr(message).message
}

Why not use :
func NewErr(message string) error {
    return newDiceErr(message)
}
