### ISSUE TITLE
Add support for `MGET` Command

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#251]
We need to implement the MGET command similar to the [MGET command in Redis](https://redis.io/commands/mget/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

1. Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).
2. For integration tests, you can refer to the tests folder. Note: they have used TCL for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).
3. For the command, benchmark the code and measure the time taken and memory allocs using [benchmem](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by chanducheryala** [comment]
@JyotinderSingh , I would like to work on this

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh , I would like to work on this

Assigned

**Comment by chanducheryala** [comment]
[](https://github.com/DiceDB/dice/pull/292)
