### ISSUE TITLE
Add support for `HSET` Command

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#255]
We need to implement the HSET command similar to the [HSET command in Redis](https://redis.io/commands/hset/). This command sets field in the hash stored at key to value. Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

1. Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).
2. For integration tests, you can refer to the tests folder. Note: they have used TCL for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).
3. For the command, benchmark the code and measure the time taken and memory allocs using [benchmem](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by lucifercr07** [comment]
@JyotinderSingh can you please assign this to me.

**Comment by yaten2302** [comment]
@JyotinderSingh , actually, I was reading about this command on the redis website, could you please guide that what's the use of the `field` option in this command? Like, `HSET key field value [field value ...]`, in this I'm not able to understand the use of `field` option <br>
![image](https://github.com/user-attachments/assets/03a06f6a-a104-4be8-b6aa-62b563a592af)

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh , actually, I was reading about this command on the redis website, could you please guide that what's the use of the `field` option in this command? Like, `HSET key field value [field value ...]`, in this I'm not able to understand the use of `field` option ![image](https://private-user-images.githubusercontent.com/129659514/355450285-03a06f6a-a104-4be8-b6aa-62b563a592af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDg2NzYsIm5iZiI6MTcyMjk0ODM3NiwicGF0aCI6Ii8xMjk2NTk1MTQvMzU1NDUwMjg1LTAzYTA2ZjZhLWExMDQtNGJlOC1iNmFhLTYyYjU2M2E1OTJhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxMjQ2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODJjNjMwM2Y3OGI2MzRjNTljNzM4OTUyZWM2MjkwNzMyMWIxNDU0ZjI5N2ZmMzk3ZmFkMGYzM2YyYTg5MzFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UFnOST0Uzv6rGZ-SfriErKnLVpLtSGE0Cz5vvSt-tWQ)

Explore the docs and play around, that is the best way to learn.

**Comment by codeimmortal** [comment]
Please assign this to me.

**Comment by JyotinderSingh** [comment]
> Please assign this to me.

Assigned

**Comment by kolharsam** [comment]
@JyotinderSingh could you please assign this to me?

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh could you please assign this to me?

Assigned

**Comment by raghavbabbar** [comment]
Hi, @kolharsam Could you please let me know the ETA for this issue, looks like mine issue https://github.com/DiceDB/dice/issues/257 is dependent on this issue implementation. cc @JyotinderSingh

**Comment by kolharsam** [comment]
> Hi, @kolharsam Could you please let me know the ETA for this issue, looks like mine issue https://github.com/DiceDB/dice/issues/257 is dependent on this issue implementation. cc @JyotinderSingh 

Hi @raghavbabbar sorry about the delay. Had a very busy weekend. Will update regarding this in a couple of days

**Comment by JyotinderSingh** [comment]
@kolharsam Are you actively working on this?

**Comment by kolharsam** [comment]
Yes, @JyotinderSingh I am actively working on this. Will share some proper updates soon.

**Comment by JyotinderSingh** [comment]
> Yes, @JyotinderSingh I am actively working on this. Will share some proper updates soon. 

Awesome, thanks!
