### ISSUE TITLE
Feature Request: Homebrew tap for installing dice db

### ISSUE THREAD

**Issue by atmnksd** [DiceDB/dice#259]
Right now I see dice db needs to be built from sources in order to use it. This project will be more useful if users can first start using dice db without required to deal with development complexity.

Possible Solution:
We can build and distribute precompiled binaries the binaries could be versioned and published as releases on this project. A homebrew tap can refer this releases for deploying it on macos.

**Comment by arpitbbhayani** [comment]
We will pick this up once we have our first stable release. Thanks for pointing it out.
