### ISSUE TITLE
Setup GitHub actions to auto-build Dice for platforms

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#27]
We need a way to build Dice DB for all platforms upon creating a new release tag. We can use [GoReleaser](https://github.com/goreleaser) to do this.

**Comment by Hakai-Shin** [comment]
I would like to work on this task.

**Comment by arpitbbhayani** [comment]
@Hakai-Shin go for it. I have assigned it to you.

**Comment by arpitbbhayani** [comment]
@Hakai-Shin  where are you with the implementation? are you stuck somewhere? You can join the [Discord Server](https://discord.gg/6r8uXWtXh7) for quick collaboration.

**Comment by Hakai-Shin** [comment]
Hi @arpitbbhayani , I have got some hands-on with goreleaser tool, currently I am working with goreleaser for github actions. I will be closing this issue soon.

**Comment by arpitbbhayani** [comment]
#59
