### ISSUE TITLE
Add support for command `GETSET`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#276]
Add support for the `GETSET` command in DiceDB similar to the [`GETSET` command in Redis](https://redis.io/docs/latest/commands/command-list/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by lucifercr07** [comment]
@arpitbbhayani would like to work on this.
However looks like `GETSET` is [deprecated](https://redis.io/docs/latest/commands/getset/) now in favour of `SET with the GET argument`.
Link in description points to `COMMAND LIST`, can you please confirm once?

**Comment by arpitbbhayani** [comment]
@lucifercr07 but we should still implement it to maintain full compatability.

**Comment by JyotinderSingh** [comment]
@lucifercr07 do you have the bandwidth to actively work on this issue?

**Comment by Yashgupta9330** [comment]
if anyone is not working can you pls assign it to me?

**Comment by lucifercr07** [comment]
@JyotinderSingh have been working on this, will raise a PR by this week.

**Comment by lucifercr07** [comment]
PR raised: https://github.com/DiceDB/dice/pull/377
@JyotinderSingh please review
