### ISSUE TITLE
Add support for command `DBSIZE`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#278]
Add support for the `DBSIZE` command in DiceDB similar to the [`DBSIZE` command in Redis](https://redis.io/docs/latest/commands/command-list/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by Saumay** [comment]
Hey @arpitbbhayani, I would like to work on this issue.
Can you please assign it to me?

**Comment by arpitbbhayani** [comment]
@Saumay Go for it. Thanks.

**Comment by Saumay** [comment]
Hey @arpitbbhayani, I am late in picking up this.
I can see @raknay has already picked this up and it's been merged as well.
https://github.com/DiceDB/dice/pull/328

Can we close this issue then?
