### ISSUE TITLE
Add support for command `EXPIREAT`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#283]
Add support for the `EXPIREAT` command in DiceDB similar to the [`EXPIREAT` command in Redis](https://redis.io/docs/latest/commands/command-list/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by jh2310** [comment]
I want to complete this task

**Comment by JyotinderSingh** [comment]
> I want to complete this task

Assigned

**Comment by jh2310** [comment]
I have a question, that is, after setting the expiration time, do I need to scan it regularly, or do I have to judge it when it is available?
I found this problem when I was testing just now.

**Comment by JyotinderSingh** [comment]
> I have a question, that is, after setting the expiration time, do I need to scan it regularly, or do I have to judge it when it is available? I found this problem when I was testing just now.

We automatically perform expiry both as a part of the [main loop](https://github.com/DiceDB/dice/blob/master/server/async_tcp.go#L182), as well as during [GET operations](https://github.com/DiceDB/dice/blob/master/core/store.go#L93).

**Comment by jh2310** [comment]
Okok, that's good, that means that this function is perfect at present, right? Then I'll test it again

**Comment by ashwaniYDV** [comment]
hi @arpitbbhayani  @JyotinderSingh I would like to work on this issue.

**Comment by JyotinderSingh** [comment]
> hi @arpitbbhayani  @JyotinderSingh I would like to work on this issue.
> 
> @JyotinderSingh  would you please assign this task to me.

Assigned
