### ISSUE TITLE
`STACKREFLEN` is not aware of the deletion of key

### ISSUE THREAD

**Issue by NOS-AE** [DiceDB/dice#285]
I'm not sure the expected behavior of the STACKREF type, a ref behaves like a soft link to the key, that is, stackreflen report the correct len after trying to access a deleted key, which may be confusing.

**How to reproduce**
> m3/macos 14.2
> go run main.go based on commit `34d5fa5`
```
127.0.0.1:7379> set s1 1
OK
127.0.0.1:7379> stackrefpush st1 s1
(integer) 1
127.0.0.1:7379> stackreflen st1
(integer) 1
127.0.0.1:7379> del s1
(integer) 1
127.0.0.1:7379> stackreflen st1
(integer) 1
127.0.0.1:7379> stackrefpop st1
(nil)
127.0.0.1:7379> stackreflen st1
(integer) 0
```

**Expected behavior**

```
127.0.0.1:7379> set s1 1
OK
127.0.0.1:7379> stackrefpush st1 s1
(integer) 1
127.0.0.1:7379> stackreflen st1
(integer) 1
127.0.0.1:7379> del s1
(integer) 1
127.0.0.1:7379> stackreflen st1
(integer) 0
127.0.0.1:7379> stackrefpop st1
(nil)
127.0.0.1:7379> stackreflen st1
(integer) 0
```

**Comment by JyotinderSingh** [comment]
Thank you for reporting this bug, must have overlooked this case.

**Comment by AshwinKul28** [comment]
@JyotinderSingh For this, while pushing onto the stack, shall we also add a reference? 
https://github.com/DiceDB/dice/blob/master/core/eval.go#L978

**Comment by 22liyi** [comment]
java 可以用这个db么？

**Comment by kushal0511-not** [comment]
@JyotinderSingh if nobody is working on this , can i take this one?

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh if nobody is working on this , can i take this one?

Assigned

**Comment by kushal0511-not** [comment]
@JyotinderSingh 
I am thinking of adding cleanup method in **stackref.go**
```
// Cleanup removes expired or deleted keys from the stack.
func (s *StackRef) Cleanup() {
	var validElements []int64

	for {
		val, err := s.si.Pop()
		if err != nil {
			break // Break the loop if the stack is empty
		}

		key := *((*string)(unsafe.Pointer(uintptr(val))))
		obj := Get(key)
		if obj != nil {
			validElements = append(validElements, val)
		}
	}

	for i := len(validElements) - 1; i >= 0; i-- {
		s.si.Push(validElements[i])
	}
}
```
and will use it before returning the length.
The reason behind is that the keys which are expired or deleted  can be anywhere in stack.

Do you have any other optimal way to do this? 
Or any suggestion?

**Comment by kushal0511-not** [comment]
[@JyotinderSingh](https://github.com/JyotinderSingh)
I am thinking of adding cleanup method in stackref.go
```
// Cleanup removes expired or deleted keys from the stack.
func (s *StackRef) Cleanup() {
	var validElements []int64

	for {
		val, err := s.si.Pop()
		if err != nil {
			break // Break the loop if the stack is empty
		}

		key := *((*string)(unsafe.Pointer(uintptr(val))))
		obj := Get(key)
		if obj != nil {
			validElements = append(validElements, val)
		}
	}

	for i := len(validElements) - 1; i >= 0; i-- {
		s.si.Push(validElements[i])
	}
}
```
and will use it before returning the length.
The reason behind is that the keys which are expired or deleted can be anywhere in stack.


I thought of map but we cannot handle expired keys in that case.
or should we count expired keys also in STACKREFLEN?

Do you have any other optimal way to do this?
Or any suggestion?

**Comment by NOS-AE** [comment]
> [@JyotinderSingh](https://github.com/JyotinderSingh) I am thinking of adding cleanup method in stackref.go
> 
> ```
> // Cleanup removes expired or deleted keys from the stack.
> func (s *StackRef) Cleanup() {
> 	var validElements []int64
> 
> 	for {
> 		val, err := s.si.Pop()
> 		if err != nil {
> 			break // Break the loop if the stack is empty
> 		}
> 
> 		key := *((*string)(unsafe.Pointer(uintptr(val))))
> 		obj := Get(key)
> 		if obj != nil {
> 			validElements = append(validElements, val)
> 		}
> 	}
> 
> 	for i := len(validElements) - 1; i >= 0; i-- {
> 		s.si.Push(validElements[i])
> 	}
> }
> ```
> 
> and will use it before returning the length. The reason behind is that the keys which are expired or deleted can be anywhere in stack.
> 
> I thought of map but we cannot handle expired keys in that case. or should we count expired keys also in STACKREFLEN?
> 
> Do you have any other optimal way to do this? Or any suggestion?

To make things look consistent, we could do one of these refactorations:
returning `nil` when `STACKREFPOP` a deleted key
or
returning the number of keys that haven't been deleted or expired when executing `STACKREFLEN `.
The former one may be easier to realize.

**Comment by kushal0511-not** [comment]
@NOS-AE  Thanks for suggestions.
> returning nil when STACKREFPOP a deleted key

This will change current behavior of Pop(), that is popping until non-expired key and also not deleted.

@JyotinderSingh which approach should we follow from [above](https://github.com/DiceDB/dice/issues/285#issuecomment-2284277131) two?

**Comment by kushal0511-not** [comment]
@JyotinderSingh 
In worst case for 1st approach could be like many (suppose 10000 ) expired key and 2-3 non-expired key.
then STACKREFLEN return a number which will far from real number.

Performance wise 2nd approach is not good.

if we don't have any other option we can go with 1st approach.

Also one thing to notice the comment is not referring to correct implementation of Pop()

```
// Pop pops the reference from the stack s.
// returns nil if key does not exist in the store any more
// if the expired key is popped from the stack, we continue to pop until
// until we find one non-expired key
// TODO: test for expired keys
func (s *StackRef) Pop() (*StackElement, error) {
```
comment says that function returns nil if key does not exists but actually it pops the key and check for next key in stack (it behaves same as expired key). 

cc @NOS-AE

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh 
> 
> In worst case for 1st approach could be like many (suppose 10000 ) expired key and 2-3 non-expired key.
> 
> then STACKREFLEN return a number which will far from real number.
> 
> 
> 
> Performance wise 2nd approach is not good.
> 
> 
> 
> if we don't have any other option we can go with 1st approach.
> 
> 
> 
> Also one thing to notice the comment is not referring to correct implementation of Pop()
> 
> 
> 
> ```
> 
> // Pop pops the reference from the stack s.
> 
> // returns nil if key does not exist in the store any more
> 
> // if the expired key is popped from the stack, we continue to pop until
> 
> // until we find one non-expired key
> 
> // TODO: test for expired keys
> 
> func (s *StackRef) Pop() (*StackElement, error) {
> 
> ```
> 
> comment says that function returns nil if key does not exists but actually it pops the key and check for next key in stack (it behaves same as expired key). 
> 
> 
> 
> cc @NOS-AE 
> 
> 

Yeah the second line of the comment doesn't clearly explain the behavior. We can fix it as a part of the PR for this issue.

I'm tempted to go with option 2 (perform cleanup).

@soumya-codes what do you think?

**Comment by JyotinderSingh** [comment]
> > @JyotinderSingh In worst case for 1st approach could be like many (suppose 10000 ) expired key and 2-3 non-expired key.在最坏的情况下，第一种方法可能是许多（假设 10000 个）过期密钥和 2-3 个未过期密钥。 then STACKREFLEN return a number which will far from real number.然后 STACKREFLEN 返回一个远离实数的数字。
> 
> > 
> 
> > Performance wise 2nd approach is not good.性能方面，第二种方法不好。
> 
> > 
> 
> > if we don't have any other option we can go with 1st approach.如果我们没有其他选择，我们可以采用第一种方法。
> 
> > 
> 
> > Also one thing to notice the comment is not referring to correct implementation of Pop()另外需要注意的一件事是，该注释并未提及 Pop() 的正确实现
> 
> > 
> 
> > ```
> 
> > // Pop pops the reference from the stack s.
> 
> > // returns nil if key does not exist in the store any more
> 
> > // if the expired key is popped from the stack, we continue to pop until
> 
> > // until we find one non-expired key
> 
> > // TODO: test for expired keys
> 
> > func (s *StackRef) Pop() (*StackElement, error) {
> 
> > ```
> 
> > 
> 
> > comment says that function returns nil if key does not exists but actually it pops the key and check for next key in stack (it behaves same as expired key).注释说如果键不存在，函数将返回 nil，但实际上它会弹出键并检查堆栈中的下一个键（其行为与过期键相同）。
> 
> > 
> 
> > cc @NOS-AE
> 
> 
> 
> Prefer the consistency rather than an approximate probe. If so, leaving a statement/comment in document/code about the worst time complexity of `STACKREFLEN` would be great for whoever want to use it.

Agreed. Let's go with the performance tradeoff in this case.

**Comment by kushal0511-not** [comment]
Going with cleanup method.

**Comment by soumya-codes** [comment]
@kushal0511-not, given the current context i agree with @JyotinderSingh that we should go for consistency over approximation and take the second approach.

However in the medium term we can handle this more efficiently by separating the two concerns `stack-length` and `stack-operations` separately. 
1. We handle updating stack length of each of the stacks synchronously as and when a key is deleted or it expires. We can see how we can handle this with minimal overhead.
2. The handling of removing/dealing with deleted/expired keys can be done lazily during stack push/pop operations as we do today, the handling of stack-length can be handled synchronously when key expires or is deleted. 

Let me know what you both think, if you agree with this approach we can discuss about the implementation.

**Comment by soumya-codes** [comment]
> returns nil if key does not exist in the store any more

So will we be updating the comment to reflect the current behaviour?

**Comment by AshwinKul28** [comment]
The cleanup method looks good. @kushal0511-not 

Also, I agree with what @soumya-codes says, stack-length and actual stack operations can be separated, I just have once concern that there at any point in time will there be any inconsistencies between length and actual operation just because we are doing it lazily.

**Comment by soumya-codes** [comment]
@AshwinKul28 when I say lazily, I meant we can keep the implementation as it is today i.e. handling the deleted/expired key during POP operation. Only issue I see with the current approach is that the stack size can be ever increasing if we have in-frequent POP operations.

**Comment by kushal0511-not** [comment]
> Let me know what you both think, if you agree with this approach we can discuss about the implementation.

@soumya-codes Sure we can discuss. 
I have doubt about how we can handle expired keys because at the time of expiration key can be any where in stack.

> So will we be updating the comment to reflect the current behavior?

yes

> just an overhead of popping and again pushing almost full array every time.

@AshwinKul28  yeah

**Comment by kushal0511-not** [comment]
@soumya-codes  and I discussed this issue and we've reached the following conclusions:

1. There is no reference in redis of QREF or STCKREF from which we can get to know implementation and time and space complexity of command. 
Is this new add-on in DiceDB like which we are offering different from redis?

2. As of Now , We don't have any notification mechanism so that we know that key got expired (at the moment of expiration). We need to fix that before implementing STACKREFLEN. 

Given these points, we've decided that we should temporarily remove support for STACKREFLEN until these issues are resolved.

@JyotinderSingh @arpitbbhayani

**Comment by JyotinderSingh** [comment]
> @soumya-codes  and I discussed this issue and we've reached the following conclusions:
> 
> 
> 
> 1. There is no reference in redis of QREF or STCKREF from which we can get to know implementation and time and space complexity of command. 
> 
> Is this new add-on in DiceDB like which we are offering different from redis?
> 
> 
> 
> 2. As of Now , We don't have any notification mechanism so that we know that key got expired (at the moment of expiration). We need to fix that before implementing STACKREFLEN. 
> 
> 
> 
> Given these points, we've decided that we should temporarily remove support for STACKREFLEN until these issues are resolved.
> 
> 
> 
> CC: @JyotinderSingh @arpitbbhayani 

STACKREF is a novel data structure in dice. I am okay with removing the STACKREFLEF command.
Alternatively we could maintain the command with the performance penalty of clearing up the stack.
I am okay with whatever the general consensus is.

**Comment by soumya-codes** [comment]
> STACKREF is a novel data structure in dice. I am okay with removing the STACKREFLEF command. Alternatively we could maintain the command with the performance penalty of clearing up the stack. I am okay with whatever the general consensus is.

Since it is a unique proposition from DiceDB, we can add few limitations to ensure novelty while limiting the performance penalty:
1. Limit the stack size. For example to 10000 entries.
2. Limit the number of stacks. For example to 100.

@kushal0511-not @JyotinderSingh wdyt?

**Comment by JyotinderSingh** [comment]
> > STACKREF is a novel data structure in dice. I am okay with removing the STACKREFLEF command. Alternatively we could maintain the command with the performance penalty of clearing up the stack. I am okay with whatever the general consensus is.
> 
> 
> 
> Since it is a unique proposition from DiceDB, we can add few limitations to ensure novelty while limiting the performance penalty:
> 
> 1. Limit the stack size. For example to 10000 entries.
> 
> 2. Limit the number of stacks. For example to 100.
> 
> 
> 
> @kushal0511-not @JyotinderSingh wdyt?

Sounds good to me

**Comment by JyotinderSingh** [comment]
We probably want to do something similar for QueueRef

**Comment by kushal0511-not** [comment]
> > STACKREF is a novel data structure in dice. I am okay with removing the STACKREFLEF command. Alternatively we could maintain the command with the performance penalty of clearing up the stack. I am okay with whatever the general consensus is.
> 
> Since it is a unique proposition from DiceDB, we can add few limitations to ensure novelty while limiting the performance penalty:
> 
> 1. Limit the stack size. For example to 10000 entries.
> 2. Limit the number of stacks. For example to 100.
> 
> @kushal0511-not @JyotinderSingh wdyt?

Yeah thats good idea.

> We probably want to do something similar for QueueRef

Yes
@JyotinderSingh 
Can i do changes for that also in the same PR which i will raise for this issue?

**Comment by JyotinderSingh** [comment]
> > > STACKREF is a novel data structure in dice. I am okay with removing the STACKREFLEF command. Alternatively we could maintain the command with the performance penalty of clearing up the stack. I am okay with whatever the general consensus is.
> 
> > 
> 
> > Since it is a unique proposition from DiceDB, we can add few limitations to ensure novelty while limiting the performance penalty:
> 
> > 
> 
> > 1. Limit the stack size. For example to 10000 entries.
> 
> > 2. Limit the number of stacks. For example to 100.
> 
> > 
> 
> > @kushal0511-not @JyotinderSingh wdyt?
> 
> 
> 
> Yeah thats good idea.
> 
> 
> 
> > We probably want to do something similar for QueueRef
> 
> 
> 
> Yes
> 
> @JyotinderSingh 
> 
> Can i do changes for that also in the same PR which i will raise for this issue? If that is okay 
> 
> 

Sure, sounds good
