### ISSUE TITLE
Add comments in the code above each command telling what it does

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#29]
**Following functions need better comments**

- all the commands implemented in `eval.go` file. Write exhaustive documentation suggesting what it does.

**Here's why I think it is difficult to understand the code**

Code may not be very difficult to understand, but adding the documentation will make it easier for the new contributors to get started quickly.

**Comment by sahil1913** [comment]
@arpitbbhayani I can pickup this task

**Comment by arpitbbhayani** [comment]
Go for it. Assigning it to you. Thanks a ton ✨

**Comment by arpitbbhayani** [comment]
@sahil1913  where are you with the implementation? are you stuck somewhere? You can join the [Discord Server](https://discord.gg/6r8uXWtXh7) for quick collaboration.
