### ISSUE TITLE
Store `int` value by reference and not serialized in `str`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#3]

**Comment by gunishmatta** [comment]
@arpitbbhayani  I would like to work on this

**Comment by samarthjuneja24** [comment]
Hey @arpitbbhayani , can you please assign this issue to me

**Comment by arpitbbhayani** [comment]
Done. @samarthjuneja24

**Comment by jayantpranjal0** [comment]
@arpitbbhayani I would like to work on this.

**Comment by AshwinKul28** [comment]
Thanks @jayantpranjal0 for the interest.
Unfortunately, this was a very old issue and we are revamping the store, and query operations. This issue is not relevant now; though we will open more relevant ones soon after the rewrite. Closing this.
