### ISSUE TITLE
Add support for command `WAIT`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#309]
Add support for the `WAIT` command in DiceDB similar to the [`WAIT` command in Redis](https://redis.io/docs/latest/commands/command-list/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by raghavbabbar** [comment]
@arpitbbhayani  could you please assign this to me?

**Comment by arpitbbhayani** [comment]
@raghavbabbar Go for it.

**Comment by JyotinderSingh** [comment]
@raghavbabbar could you please add updates on your progress on the issue?

**Comment by raghavbabbar** [comment]
https://discord.com/channels/1034342738960855120/1264145943884992595/1273975330780221522 As we don't have replica at the moment. what functionality are we expecting out from this issue. could you guys please help me @JyotinderSingh

**Comment by JyotinderSingh** [comment]
> https://discord.com/channels/1034342738960855120/1264145943884992595/1273975330780221522 As we don't have replica at the moment. what functionality are we expecting out from this issue. could you please help me @JyotinderSingh 

Makes sense, we can add this issue to the icebox for now.
