### ISSUE TITLE
Report inconsistency in the command `SET`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#333]
This issue is all about ensuring we are as close to Redis as possible. The command in focus for this issue is `SET`.

Go through the [official documentation](https://redis.io/docs/latest/commands) of the command `SET` on Redis and identify the inconsistencies. The inconsistencies could be in

1. unhandled edge case
1. unexpected behavior
1. unsupported option

Because we are trying to be compatible with Redis v7.2.5, I would recommend you try out different variants of the command with different inputs on that specific version. The instructions on running Redis v7.2.5 locally

- [from source code](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [use Docker](https://hub.docker.com/_/redis)

Once you find the discrepancy, you can either

1. raise an issue on [Dice repository](https://github.com/dicedb/dice) with details, or
1. try to fix it yourself and raise a PR

If you are [raising the issue](https://github.com/DiceDB/dice/issues/new?assignees=&labels=&projects=&template=inconsistent_dicedb_vs_redis.md&title=Inconsistent+%60%7BCMD%7D%60%3A+%3CDescribe+the+error+in+one+concise+line%3E), make sure you provide the details such as

0. [use the template](https://github.com/DiceDB/dice/issues/new?assignees=&labels=&projects=&template=inconsistent_dicedb_vs_redis.md&title=Inconsistent+%60%7BCMD%7D%60%3A+%3CDescribe+the+error+in+one+concise+line%3E) and provide the following details
1. steps to reproduce (series of commands)
1. observed output on DiceDB
1. observed output on Redis v7.2.5

Also, feel free to update the documentation and raise the PR in the [docs repository](https://github.com/dicedb/docs).

> You will need to go deeper into the command make sure you are covering all cases and reporting the inconsistencies or fixing them. The deeper the work, the better our stability will be. Also, it is possible that we do not find any discrepancies, so please mention the same in the comment on this issue. Mention the PR or issue links that you create under this issue.

**Comment by IWhitebird** [comment]
hi @arpitbbhayani  ,  I would like to work on this.

**Comment by IWhitebird** [comment]
hey , can i work on this ?

**Comment by arpitbbhayani** [comment]
@IWhitebird Go for it. Thanks a ton :) Assigned the issue to you.

**Comment by IWhitebird** [comment]
I tried every possible combination of options with varying input, and both databases gave the same result.

**Comment by AshwinKul28** [comment]
Hello @IWhitebird  thanks for the work and update. Can you please raise a PR for the changes and attach this issue to it? Please pull the latest changes from the master before raising a PR.

**Comment by AshwinKul28** [comment]
Hello @IWhitebird There's one usecase where I see inconsistent results

``` Output
127.0.0.1:7379> SET mykey "hello" NX EX 10
OK
127.0.0.1:7379> GET mykey
"hello"
127.0.0.1:7379> SET mykey "world" NX EX 10
(nil)
127.0.0.1:7379> GET mykey
(nil)
127.0.0.1:7379> TTL mykey
(integer) -2
```

Expected:

```
127.0.0.1:6379> SET mykey "hello" NX EX 10
OK
127.0.0.1:6379> GET mykey
(nil)
127.0.0.1:6379> SET mykey "hello" NX EX 10
OK
127.0.0.1:6379> GET mykey
"hello"
127.0.0.1:6379> SET mykey "world" NX EX 10
(nil)
127.0.0.1:6379> GET mykey
"hello"
127.0.0.1:6379> TTL mykey
(integer) 983
127.0.0.1:6379> 

@JyotinderSingh shall we create an issue for this?

**Comment by IWhitebird** [comment]
![image](https://github.com/user-attachments/assets/6133e6ff-d23b-4244-972f-ea1938578618)

it's giving same output on my end , is there something I am missing ?
i am  redis:7.2.5 on docker

**Comment by AshwinKul28** [comment]
Ahh okay, maybe it's an issue with the dice cli. Thanks for the confirmation @IWhitebird Closing the issue.

**Comment by Aditya-Bhalerao** [comment]
Hi @AshwinKul28, found these inconsistencies in SET while working on https://github.com/DiceDB/dice/issues/378

```
# On DiceDB
127.0.0.1:7379> SET \x00\x01 "value"
OK
127.0.0.1:7379> GET "\x00\x01"
"value"
127.0.0.1:7379> GET \x00\x01
"value"
```
```
# On Redis
127.0.0.1:6379> SET "\x00\x01" "value"
OK
127.0.0.1:6379> GET "\x00\x01"
"value"
127.0.0.1:6379> GET \x00\x01
(nil)
```

and

```
# On DiceDB
127.0.0.1:7379> SET \x00 "value"
OK
127.0.0.1:7379> get "\x00"
"value"
127.0.0.1:7379> get \x00
"value"
```
```
# On Redis
127.0.0.1:6379> set SET \x00 "value"
(error) ERR syntax error
```

It seems that DiceDB and Redis handle certain edge cases with special characters in a significantly different manner.

Even though this issue was closed previously, I'm commenting here because it still seems like the most relevant place for discussion.
