### ISSUE TITLE
Report inconsistency in the command `SLEEP`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#334]
This issue is all about ensuring we are as close to Redis as possible. The command in focus for this issue is `SLEEP`.

Go through the [official documentation](https://redis.io/docs/latest/commands) of the command `SLEEP` on Redis and identify the inconsistencies. The inconsistencies could be in

1. unhandled edge case
1. unexpected behavior
1. unsupported option

Because we are trying to be compatible with Redis v7.2.5, I would recommend you try out different variants of the command with different inputs on that specific version. The instructions on running Redis v7.2.5 locally

- [from source code](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [use Docker](https://hub.docker.com/_/redis)

Once you find the discrepancy, you can either

1. raise an issue on [Dice repository](https://github.com/dicedb/dice) with details, or
1. try to fix it yourself and raise a PR

If you are [raising the issue](https://github.com/DiceDB/dice/issues/new?assignees=&labels=&projects=&template=inconsistent_dicedb_vs_redis.md&title=Inconsistent+%60%7BCMD%7D%60%3A+%3CDescribe+the+error+in+one+concise+line%3E), make sure you provide the details such as

0. [use the template](https://github.com/DiceDB/dice/issues/new?assignees=&labels=&projects=&template=inconsistent_dicedb_vs_redis.md&title=Inconsistent+%60%7BCMD%7D%60%3A+%3CDescribe+the+error+in+one+concise+line%3E) and provide the following details
1. steps to reproduce (series of commands)
1. observed output on DiceDB
1. observed output on Redis v7.2.5

Also, feel free to update the documentation and raise the PR in the [docs repository](https://github.com/dicedb/docs).

> You will need to go deeper into the command make sure you are covering all cases and reporting the inconsistencies or fixing them. The deeper the work, the better our stability will be. Also, it is possible that we do not find any discrepancies, so please mention the same in the comment on this issue. Mention the PR or issue links that you create under this issue.

**Comment by Harsh-2909** [comment]
I would like to take this issue

**Comment by arpitbbhayani** [comment]
@Harsh-2909 Go for it. Thanks a ton :) Assigned the issue to you.

**Comment by Harsh-2909** [comment]
@arpitbbhayani  @JyotinderSingh  I checked the documentation and even ran Redis v7.2.5 locally but it seems that the `SLEEP` command is not present in this version.

I am attaching a few screenshots below:

Searching for SLEEP command in Redis Documentation
![Searching for SLEEP command in Redis Documentation](https://github.com/user-attachments/assets/9690e191-72a5-4f92-baab-0edb615533b9)

Running Redis v7.2.5 to check for SLEEP command
![Running Redis v7.2.5 to check for SLEEP command](https://github.com/user-attachments/assets/77bc8b2d-1bde-4e45-9fc1-fd0549753636)

![Using COMMAND DOCS SLEEP to get the documentation](https://github.com/user-attachments/assets/0a74b61a-afd0-4e32-a525-3c91570ce4a3)

It seems that the command `SLEEP` is not present in Redis v7.2.5

Should I create an issue to remove the `SLEEP` command from diceDB. I would like your inputs in this.

**Comment by arpitbbhayani** [comment]
@Harsh-2909 Let's keep the sleep command as is. I think I remember seeing it in some old version of Redis because oof which I implemented. Having an additional command does no harm. DiceDB will continue to support SLEEP command.

Thanks Harsh for exploring this. Means a ton. Will go ahead and close this issue then.
