### ISSUE TITLE
Report inconsistency in the command `PING`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#336]
This issue is all about ensuring we are as close to Redis as possible. The command in focus for this issue is `PING`.

Go through the [official documentation](https://redis.io/docs/latest/commands) of the command `PING` on Redis and identify the inconsistencies. The inconsistencies could be in

1. unhandled edge case
1. unexpected behavior
1. unsupported option

Because we are trying to be compatible with Redis v7.2.5, I would recommend you try out different variants of the command with different inputs on that specific version. The instructions on running Redis v7.2.5 locally

- [from source code](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [use Docker](https://hub.docker.com/_/redis)

Once you find the discrepancy, you can either

1. raise an issue on [Dice repository](https://github.com/dicedb/dice) with details, or
1. try to fix it yourself and raise a PR

If you are [raising the issue](https://github.com/DiceDB/dice/issues/new?assignees=&labels=&projects=&template=inconsistent_dicedb_vs_redis.md&title=Inconsistent+%60%7BCMD%7D%60%3A+%3CDescribe+the+error+in+one+concise+line%3E), make sure you provide the details such as

0. [use the template](https://github.com/DiceDB/dice/issues/new?assignees=&labels=&projects=&template=inconsistent_dicedb_vs_redis.md&title=Inconsistent+%60%7BCMD%7D%60%3A+%3CDescribe+the+error+in+one+concise+line%3E) and provide the following details
1. steps to reproduce (series of commands)
1. observed output on DiceDB
1. observed output on Redis v7.2.5

Also, feel free to update the documentation and raise the PR in the [docs repository](https://github.com/dicedb/docs).

> You will need to go deeper into the command make sure you are covering all cases and reporting the inconsistencies or fixing them. The deeper the work, the better our stability will be. Also, it is possible that we do not find any discrepancies, so please mention the same in the comment on this issue. Mention the PR or issue links that you create under this issue.

**Comment by Dev79844** [comment]
Hello @arpitbbhayani
I would like to work on this issue

**Comment by Harsh-2909** [comment]
Hello @arpitbbhayani 
I would like to work on this

**Comment by sudoharshita16** [comment]
Hello @arpitbbhayani 
I would like to work on this

**Comment by arpitbbhayani** [comment]
@Dev79844 Go for it. Thanks a ton :) Assigned the issue to you.

**Comment by Dev79844** [comment]
@arpitbbhayani I tested the ping command and compared with redis 7.2.5. PING in dice is working exactly like PING in redis.

**Comment by AshwinKul28** [comment]
@Dev79844 Thanks for the update and work. Can you please raise the PR and attach this issue to it?

**Comment by AshwinKul28** [comment]
Hey @Dev79844 Thanks for the update. Just add the evidence from the Redis and the Dice PING execution. Then we will close the issue.

**Comment by AshwinKul28** [comment]
Looks consistent. Closing the issue. Thanks @Dev79844
