### ISSUE TITLE
QWATCH bug: inconsistent types on retrieval 

### ISSUE THREAD

**Issue by YahyaHaq** [DiceDB/dice#341]
We have a bug in our QWATCH command. We can store a value as an integer but on retrieval it treats it as a string. Running this query in qwatch_test.go  `var qWatchQuery = "SELECT $key, $value FROM 'match:100:*' WHERE $value > 1 ORDER BY $value DESC LIMIT 3"` will give us an error "2024/08/03 12:43:48 ERRO incompatible types in comparison: string and int".

**Comment by YahyaHaq** [comment]
@JyotinderSingh Can you assign this to me

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh Can you assign this to me

Assigned

**Comment by JyotinderSingh** [comment]
This was already fixed in #363 as a part of another bug fix. But thanks for reporting this.
