### ISSUE TITLE
Add support for command [JSON.TYPE] 

### ISSUE THREAD

**Issue by jujiale** [DiceDB/dice#342]
- Implement get the key's value type that  [JSON.GET] command returned
- Add unit and integration tests

**Comment by jujiale** [comment]
@JyotinderSingh can I accomplish this command for dice. if yes, please assign it to me. thanks.

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh can I accomplish this command for dice. if yes, please assign it to me. thanks.

Assigned.

**Comment by JyotinderSingh** [comment]
> > @JyotinderSingh can I accomplish this command for dice. if yes, please assign it to me. thanks.
> 
> Assigned. Thanks for adding this issue.

**Comment by JyotinderSingh** [comment]
Thanks for fixing this!
