### ISSUE TITLE
Optimize DBSIZE command to not require lock on keypool

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#346]
DBSIZE store API currently takes a lock on the keypool to evaluate the number of keys in the database. Instead we can simply return the value stored in KeyspaceStat data structure which already counts the number of keys.

Additionally there is likely to be much lesser contention on this data structure as compared to the keypool, which will help with performance.

**Comment by raknay** [comment]
@JyotinderSingh  Assign it to me.

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh  Assign it to me.

Assigned.
