### ISSUE TITLE
Add support for command `FILTERKEYS`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#35]
**Is your feature request related to a problem? Please describe.**
We need a way to filter out keys on the basis of wildcard patterns; so that the KV tuples can be piped through other commands for in-mem aggregations.

**Describe the solution you'd like**
Create a command `FILTERKEYS` that accepts wildcards as an argument and returns the list of KV pairs as a response. 

```
> FILTERKEYS "*user:*"
0) 0) user:1
    1) value:1
1) 0) user:2
    1) value:2
```

a JSON equivalent of the response is

```
[
    ["user:1", "value:1"],
    ["user:2", "value:2"],
    ...
]
```

**Comment by MayukhSobo** [comment]
Hi @arpitbbhayani. Can I take this up? This would be my first encounter with DiceDB

**Comment by arpitbbhayani** [comment]
@MayukhSobo go for it. Assigning it to you.

**Comment by manosriram** [comment]
@MayukhSobo are you still actively working this issue? If not, I want to pick this up; looks like an interesting add.

**Comment by arpitbbhayani** [comment]
@MayukhSobo where are you with the implementation? are you stuck somewhere? You can join the [Discord Server](https://discord.gg/6r8uXWtXh7) for quick collaboration.

**Comment by arpitbbhayani** [comment]
@MayukhSobo sure. No worries take your time 🙌

**Comment by arpitbbhayani** [comment]
@MayukhSobo that is totally fine. Folks would not automatically merge.

**Comment by Prady2006** [comment]
Hey @MayukhSobo are you still working on the feature , or can i start working on this feature @arpitbbhayani  ?

**Comment by MayukhSobo** [comment]
@Prady2006 I am working on this. Will make a PR today.
