### ISSUE TITLE
Add support for NX, XX, GT, LT, etc. to EXPIRE and EXPIREAT commands

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#355]
The EXPIREAT command supports a set of options:
NX -- Set expiry only when the key has no expiry
XX -- Set expiry only when the key has an existing expiry
GT -- Set expiry only when the new expiry is greater than current one
LT -- Set expiry only when the new expiry is less than current one
A non-volatile key is treated as an infinite TTL for the purpose of GT and LT. The GT, LT and NX options are mutually exclusive.

We need to add support for these options in our implementations of these commands.

**Comment by raghavbabbar** [comment]
Could you please assign this to me ? @JyotinderSingh

**Comment by JyotinderSingh** [comment]
> Could you please assign this to me ? @JyotinderSingh

Assigned.
