### ISSUE TITLE
Fix Flakey test. - Set Multiple Nested Values in JSON Test

### ISSUE THREAD

**Issue by yashs360** [DiceDB/dice#357]
Set Multiple Nested Values in JSON Test is flakey. Review and fix flakeyness. `json_test.go`

**Comment by Aditya-Bhalerao** [comment]
Hi @JyotinderSingh, can you please assign this issue to me. I'll take a look. Thanks

**Comment by JyotinderSingh** [comment]
> 
> 
> Hi @JyotinderSingh, can you please assign this issue to me. I'll take a look. Thanks

Hey, looks like someone already prepared a draft PR. We'll have some new issues soon, please comment on those and we'll assign them.
Thanks!
