### ISSUE TITLE
Fix Flakey Test - Get All Prices in JSON Tests

### ISSUE THREAD

**Issue by yashs360** [DiceDB/dice#358]
Get All Prices in JSON Tests is flakey due to order of elements. Review and fix flakeyness. `json_test.go`

**Comment by kushal0511-not** [comment]
@JyotinderSingh can i take this one?

**Comment by arpitbbhayani** [comment]
@kushal0511-not you already have one on your plate :) wrap that up and then you can pick this up (if still open) :D

**Comment by soumya-codes** [comment]
i think #365 will fix the issue. cc @JyotinderSingh @VedWhat
