### ISSUE TITLE
Add support for command [JSON.CLEAR]

### ISSUE THREAD

**Issue by jujiale** [DiceDB/dice#371]
Implement [JSON.CLEAR] command
`
JSON.CLEAR returns an integer reply specifying the number of matching JSON arrays and objects cleared + number of matching JSON numerical values zeroed
`

refer to [https://redis.io/docs/latest/commands/json.clear/](url)
Add unit and integration tests

**Comment by jujiale** [comment]
@JyotinderSingh can I accomplish this command for dice. if yes, please assign it to me. thanks.

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh can I accomplish this command for dice. if yes, please assign it to me. thanks.

Thanks for creating this issue. Assigned it to you.
