### ISSUE TITLE
Fix RENAME command

### ISSUE THREAD

**Issue by kushal0511-not** [DiceDB/dice#374]
When using the RENAME command, 
If the sourceKey and destinationKey are the same but sourceKey does not exist, the command returns OK instead of returning an error as expected. 

Actual (DiceDB) :
![Screenshot from 2024-08-21 21-29-04](https://github.com/user-attachments/assets/cbc112c0-858f-46a9-9482-631205bf8840)

Expected (Redis 7.2.5) :
![image-1](https://github.com/user-attachments/assets/847c1bb3-1b4c-4d09-aa5d-b7ddc06b493e)

**Comment by arpitbbhayani** [comment]
PR: https://github.com/DiceDB/dice/pull/376

**Comment by arpitbbhayani** [comment]
Thank you @kushal0511-not for raising the issue. raised the PR to fix and merging it now.

**Comment by kushal0511-not** [comment]
@arpitbbhayani You might have missed it.

I had rised PR #375 😅.

**Comment by kushal0511-not** [comment]
I will close that PR
