### ISSUE TITLE
Add support for `FLUSHDB` and `FLUSHALL` commands

### ISSUE THREAD

**Issue by ashwaniYDV** [DiceDB/dice#389]
FLUSHDB
------

* Syntax
  FLUSHDB [ASYNC | SYNC]
* Delete all the keys of the currently selected DB. 

* By default, FLUSHDB will synchronously flush all keys from the database.

* It is possible to use one of the following modifiers to dictate the flushing mode explicitly:
  * ASYNC: flushes the database asynchronously
  * SYNC: flushes the database synchronously

FLUSHALL
------

* Syntax
  FLUSHALL [ASYNC | SYNC]

* Delete all the keys of all the existing databases, not just the currently selected one. This command never fails.

* By default, FLUSHALL will synchronously flush all keys from the database.

* It is possible to use one of the following modifiers to dictate the flushing mode explicitly:
  * ASYNC: flushes the databases asynchronously
  * SYNC: flushes the databases synchronously

**Comment by ashwaniYDV** [comment]
@JyotinderSingh would you please assign this to me.

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh would you please assign this to me.

Assigned
