### ISSUE TITLE
Pull Request Template

### ISSUE THREAD

**Issue by sahil1913** [DiceDB/dice#39]
**Is your feature request related to a problem? Please describe.**
PRs from different devs would be in different format which brings non-uniformity across the project. 

**Describe the solution you'd like**
Create a PR template which will help aligning uniformity across PRs and thus for the project as of whole 

**Additional context**
Refs: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by Mystigan** [comment]
I would like to take this up.

**Comment by AshwinKul28** [comment]
We do need to have a Pull request template. @arpitbbhayani @JyotinderSingh 
I'm thinking shall we wait till our rewrite completes? till then we can close the issue.
