### ISSUE TITLE
Add support of lists implemeted using `ziplist`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#4]
- the list can have a cap of entries (configuration) we can put in there
- commands to add, and remove elements from the list given an index

**Comment by paresh-bhave** [comment]
@arpitbbhayani I've been looking to contribute to open-source for a while and this project seem like a perfect place to start. I would like to contribute to this issue but also, I would like to understand little bit of a background on this. I've been following you on LinkedIn and familiar with DiceDB project goal but my familiarity with Redis is at the beginner level and pretty much theoretical. I'm hoping that by contributing to this project I would get a deeper understanding of the Redis system. It would be great if you can guide me if this issue would be a good place to start or perhaps a smaller bug / feature ?

**Comment by Vsareen0** [comment]
Hey @arpitbbhayani , If no one is working on this, I would like to contribute to this.

**Comment by Vsareen0** [comment]
Hey @JyotinderSingh is it open to work and need some documentation before being assigned ?

**Comment by AshwinKul28** [comment]
@JyotinderSingh Can you please assign this to @Vsareen0

**Comment by AshwinKul28** [comment]
Unfortunately, this was a very old issue and we are revamping the core implementations. This issue is not relevant now; though we will open more relevant ones soon after the rewrite. Closing this.
