### ISSUE TITLE
Inconsistent `MSET`: MSET command causes error when retrieving integers in DiceDB

### ISSUE THREAD

**Issue by Aditya-Bhalerao** [DiceDB/dice#406]
The command `MSET` is not consistent with Redis implementation. Here are the steps to reproduce the issue

Execute Command - MSET key value (Where value is an Integer)
Excute Command - GET key

Here's the output I observed in Redis v7.2.5

```
# On Redis v7.2.5:
127.0.0.1:6379> MSET key8 12345
OK
127.0.0.1:6379> get key8
"12345"
```

and here's the output I observed in DiceDB's latest commit of the `master` branch

```
# On DiceDB:
127.0.0.1:7379> MSET key8 12345
OK
127.0.0.1:7379> get key8
(error) ERROR expected int64 but got another type: 12345
```

Additional Observation

When using the SET command with an integer value in DiceDB, there are no issues when retrieving the value with the GET command:

```
127.0.0.1:7379> SET key 123
OK
127.0.0.1:7379> GET key
123
```
This indicates that the issue may lie with the MSET command, as the SET command works as expected.

Make the implementation consistent with the Redis implementation.
Make sure you are using Redis version 7.2.5 as a reference for the
command implementation and to setup Redis

- [from source code](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843), or
- [use Docker](https://hub.docker.com/_/redis).

**Comment by Aditya-Bhalerao** [comment]
I came across this issue while working on #378

I'm currently working on it. Could you please assign this issue to me?

**Comment by lucifercr07** [comment]
@Aditya-Bhalerao assigned this to you.

**Comment by ar1fKhan** [comment]
Hello @lucifercr07 ,
Can you assigne it to me

**Comment by lucifercr07** [comment]
@Aditya-Bhalerao can you please share updates on the issue?

**Comment by ar1fKhan** [comment]
https://github.com/DiceDB/dice/pull/594
create MR for this

**Comment by Aditya-Bhalerao** [comment]
@lucifercr07, it looks like a PR has already been created. I’ll unassign myself from this issue. Sorry for holding it up.

**Comment by lucifercr07** [comment]
Closing, Fixed as part of https://github.com/DiceDB/dice/pull/594.
