### ISSUE TITLE
Remove unsafe pointers from stack , queue and dequeue

### ISSUE THREAD

**Issue by kushal0511-not** [DiceDB/dice#407]
As we are moving away from unsafe.Pointer
We need to get rid of it in stack , queue and dequeue.
Ref issue : https://github.com/DiceDB/dice/issues/350
Ref PR : https://github.com/DiceDB/dice/pull/370

**Comment by bpranava** [comment]
Hi @kushal0511-not , is someone working on this issue? If not, can I pick this up?

**Comment by kushal0511-not** [comment]
@bpranava I am not working on this.
@AshwinKul28 , are you working on this?

**Comment by AshwinKul28** [comment]
@kushal0511-not The PR related to this already merged, for stack and Queue we are still having it. But I'm working on a part to remove keypool which will remove the dependency of unsafe pointer totally. 

Will take care of it in my next PR.

**Comment by lucifercr07** [comment]
Closing this as addressed as part of PR: https://github.com/DiceDB/dice/pull/370.
