### ISSUE TITLE
Setup Zap logger

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#414]
We should replace the current logger (`"github.com/charmbracelet/log"`) with Zap for better performance.

**Comment by Dev79844** [comment]
Hello @JyotinderSingh!
I would like to work on this

**Comment by soumya-codes** [comment]
I have already written a variant for it. If it's ok, i can take this up?

**Comment by Dev79844** [comment]
Sure

**Comment by soumya-codes** [comment]
@Dev79844 thanks...

**Comment by icetech233** [comment]
zerolog is best

**Comment by soumya-codes** [comment]
@icetech233 would like to hear more on this. Why do you think zerolog is best?

**Comment by yashs360** [comment]
Should be easy to benchmark this? Or refer to an existing benchmark.

Also, i have closed a task to unify logging so please include that in scope once we have decided on the logging lib.

**Comment by icetech233** [comment]
> @icetech233 would love to hear more on this. Why do you think zerolog is best?

the most fast

**Comment by icetech233** [comment]
> zerolog

Benchmarks  https://github.com/rs/zerolog

**Comment by AshwinKul28** [comment]
I have been using zerolog from a long time. And yes it has a performance advantage mentioned in [these benchmarks ](https://github.com/DiceDB/dice/issues/335). In our last discussion I missed to mention this @soumya-codes . We can actually go with the zerolog instead of zap.

**Comment by sbshah97** [comment]
Why not just go ahead with slog? 

This is a nice talk which the Go team gave about logging in Go 
https://youtu.be/8rnI2xLrdeM?si=bllbR3HBMi9sUJbw

**Comment by aashraybhandar1** [comment]
Hey guys is there a consensus on this? And is anybody looking to pick it up? If not I would like to pick it up

**Comment by pr2897** [comment]
@AshwinKul28  @JyotinderSingh  can I go ahead with zerolag? I want to pick it up.

**Comment by JyotinderSingh** [comment]
> @AshwinKul28  @JyotinderSingh  can I go ahead with zerolag? I want to pick it up.

I believe @AshwinKul28 is already tackling this

**Comment by lucifercr07** [comment]
@kaviisuri thanks for contributing, assigned.
