### ISSUE TITLE
Add support for command [JSON.DEL]

### ISSUE THREAD

**Issue by jujiale** [DiceDB/dice#419]
Implement [JSON.DEL] command

**Delete a value**
`JSON.DEL key [path]`

**Return**
`JSON.DEL returns an integer reply specified as the number of paths deleted (0 or more)`

refer to [json.del](https://redis.io/docs/latest/commands/json.del/)
Add unit and integration tests

**Comment by jujiale** [comment]
@JyotinderSingh hello, I plan to accomplish this  command for dice.  please assign it to me. thanks.

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh hello, I plan to accomplish this  command for dice.  please assign it to me. thanks.

Awesome, thanks for taking this up @jujiale! Assigned to you.
