### ISSUE TITLE
Complexity with GC, mutex & storage engine layout

### ISSUE THREAD

**Issue by rohanverma94** [DiceDB/dice#43]
**Is your feature request related to a problem? Please describe.**
Atomics and Mutexes are common solutions for locking. Behind the scenes, they are tuned for exclusive access and not for quick turn-around. 

A common remedy to his problem is lock-free programming but not everything can be turned into a lock-free construct. Turnaround time should be minimal if the primary use case is a key-value store, moreover, if more data types and eviction policies are to be introduced in the future then this turnaround time would be significant with the current storage engine based on ``map[string]*object``. 

For instance, in LFU, while inserting key-value I've to keep track of the access frequency and if the store is found to be near its capacity, it should evict the least frequently used value, this is a classic example of a chain where every single operation being blocked by a mutex and releasing of those mutexes itself depend on the response time of storage layout.

**Describe the solution you'd like**
Not just in Golang, but in C++ also we have been using constructs like singleton, monostate, etc which are designed around exclusivity. And to address those problems we use **" signals and slots"**.

 So the solution I propose is to use **"Buffered channels" with a slot size of 1.** The above problem of LFU policy can easily be modeled using slots, a buffered channel essentially operates on a slot being filled or empty and has the potential to make a quick turnaround. 

As discussed earlier in https://github.com/DiceDB/dice/issues/31#issuecomment-1281692558 , a storage engine based on slices is friendly enough for GC and we should only use maps/hashtables for DB index ( db 0, db 1, db 2....) as on top of weird GC issues with maps, the computation for hash function also causes a significant delay on an "ms" scale.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rohanverma94** [comment]
@arpitbbhayani If you'll approve of the changes proposed, I would start preparing design documents for new data structure.

**Comment by arpitbbhayani** [comment]
I really think keeping Dice DB single-threaded for evaluation engine will be a better choice.

LFU can be approximated, we don't need brute correctness. Approximation can be easily handled while being single threaded.

My idea of Dice DB is to 

- keep it single threaded for core evaluation
- multi-threaded for single command execution so as to utilise all the cores (in-mem ETL and data processing use case fits here)

This way we keep things simple and straightforward for most.

Happy to chat.

**Comment by rohanverma94** [comment]
What about the storage engine?

**Comment by arpitbbhayani** [comment]
Right now I was thinking of keeping it in-memory + periodic backups. Multi-threading will help when we go for disk storage (given the slowness of disk IO). We can decide to make them persistent later.

**Comment by rohanverma94** [comment]
Okay, so I'll hold my design for now. Btw a lot of changes are coming in windows version. I just implemented a entire POSIX system call for windows and it was a headache. Fsync implementation for windows would be a lot harder...

![image](https://user-images.githubusercontent.com/8470490/196865685-23b77aaf-bb91-4d22-97e8-8b7fc5fe115b.png)

**Comment by arpitbbhayani** [comment]
@rohanverma94 thanks a ton :) looking forward to it!

**Comment by jnana-cetana** [comment]
> Okay, so I'll hold my design for now. Btw a lot of changes are coming in windows version. I just implemented a entire POSIX system call for windows and it was a headache. Fsync implementation for windows would be a lot harder, I can just wish there wouldn't be a tech debt for the windows platform in the future. With the POSIX platform, life is much simpler I must say!
> 
> ![image](https://user-images.githubusercontent.com/8470490/196865685-23b77aaf-bb91-4d22-97e8-8b7fc5fe115b.png)

Wow! So much to learn. Looking forward.

**Comment by rohanverma94** [comment]
@arpitbbhayani In spite of automatic GC here
```bash
GODEBUG=gctrace=1 ./dice
2022/10/31 10:15:43 rolling the dice ⚄︎
2022/10/31 10:15:43 starting an asynchronous TCP server on 0.0.0.0 7379
gc 1 @126.086s 0%: 0.044+0.33+0.026 ms clock, 0.35+0.13/0.27/0+0.21 ms cpu, 3->3->0 MB, 4 MB goal, 0 MB stacks, 0 MB globals, 8 P
GC forced
gc 2 @247.568s 0%: 0.072+0.25+0.004 ms clock, 0.58+0/0.42/0+0.036 ms cpu, 2->2->0 MB, 4 MB goal, 0 MB stacks, 0 MB globals, 8 P
GC forced
gc 3 @375.271s 0%: 0.15+0.73+0.023 ms clock, 1.2+0/1.1/0+0.19 ms cpu, 0->0->0 MB, 4 MB goal, 0 MB stacks, 0 MB globals, 8 P

```
My INFO command is showing 
```bash
127.0.0.1:7379> info
# Keyspace
db0:keys=680,expires=0,avg_ttl=0
db1:keys=0,expires=0,avg_ttl=0
db2:keys=0,expires=0,avg_ttl=0
db3:keys=0,expires=0,avg_ttl=0
```
Because of
```go
KeyspaceStat[0]["keys"]++
```
This is wrong because I never used 680 keys in the first place. Some weird GC issues in play here! This is owing to ioredis testing

**Comment by AshwinKul28** [comment]
@rohanverma94 Thanks for the contribution. 
Unfortunately, this was a very old issue and we are revamping the core implementations. This issue is not very much relevant now; though we will open more relevant ones soon after the rewrite. Closing this.
