### ISSUE TITLE
Add integration test for ABORT command

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#437]
* Add an integration test for the abort command.
* The test should ensure that the server shuts down in time once the abort command is received.
* Restart the server to ensure restarts are also successful.
* Ensure that the server port is released when the server is shut down.

**Comment by tdadadavid** [comment]
Please can you assign this to me?

**Comment by chettriyuvraj** [comment]
I would love to have a swing at this one :)

@JyotinderSingh

**Comment by JyotinderSingh** [comment]
> Please can you assign this to me?

Assigned.

**Comment by TheRanomial** [comment]
@JyotinderSingh i tried to implement it and also a PR for it. Can you have a look?
https://github.com/DiceDB/dice/pull/442

**Comment by tdadadavid** [comment]
@JyotinderSingh I worked on the abort test command 
#451

**Comment by tdadadavid** [comment]
My apologies for the silence. 

Due to the new changes (refactoring), I have to rebase the PR I made. Thanks

**Comment by tdadadavid** [comment]
My apologies for the silence. 

Due to the new changes (refactoring), I have to rebase the PR I made. Thanks

**Comment by tdadadavid** [comment]
@JyotinderSingh I reworked the abort test command
#531
