### ISSUE TITLE
TCL Unit tests implementation for `AUTH, AOF, EXPIRE, BITPOS`

### ISSUE THREAD

**Issue by lucifercr07** [DiceDB/dice#449]
- Implement TCL unit tests for individual commands:
    - `AUTH, AOF, EXPIRE`
    - Ref files: [expire.tcl](https://github.com/redis/redis/blob/7b070423b8e20cf14a9ab80dfa7bea5ba88c54a3/tests/unit/expire.tcl), [aof.tcl](https://github.com/redis/redis/blob/b653c759cd9f0629ea19ef7c8a11400c065c7efd/tests/unit/auth.tcl), [auth.tcl](https://github.com/redis/redis/blob/b653c759cd9f0629ea19ef7c8a11400c065c7efd/tests/unit/auth.tcl), [bitops.tcl](https://github.com/redis/redis/blob/1407ac1f3ece8f7e4094f92e649e5d0b7c5e5bde/tests/unit/bitops.tcl)

**Comment by AshwinKul28** [comment]
Thanks @lucifercr07 , Will start working on it

**Comment by lucifercr07** [comment]
Closing as implemented as part of commit [here](https://github.com/AshwinKul28/dice-tests/commit/18d40f568892116d517d27808cb56d1aad1c080f) on `dice-tests` repo.
