### ISSUE TITLE
Refactor constants

### ISSUE THREAD

**Issue by soumya-codes** [DiceDB/dice#468]
Today we have most of the constants used across the repo in constants/constants.go. This is an anti-pattern as the constant.go becomes a garbage dump of constants over a period of time.

Move the constants to the package they are scoped to instead of centralizing them at one place.

This is a good first issue for anyone trying to understand the codebase.

**Comment by jayantpranjal0** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by soumya-codes** [comment]
@jayantpranjal0 assigned. Please do post updates regularly. This helps us keep track of issues and overall progress.
