### ISSUE TITLE
Failure when executing `SET` with arg `EX` with big integer

### ISSUE THREAD

**Issue by lucifercr07** [DiceDB/dice#479]
1. Name of the command: `SET` command with `EX` value `10000000000000000`
2. Expected output:
```
redis> SET foo bar EX 10000000000000000
(error) invalid expire time in 'set' command
```
3. Current output:
```
0.0.0.0:7379> SET foo bar EX 10000000000000000
OK
```
5. Expectation to add related unit/integration test (we should maintain our own integration test suite as well to allow easier debugging in the future):
- Related TCL test case [here](https://github.com/AshwinKul28/dice-tests/blob/main/tcltests/unit/expire.tcl#L88C5-L91C49). This test case should ideally pass once this issue is fixed. Steps to run the test cases are mentioned on repo [here](https://github.com/AshwinKul28/dice-tests/blob/main/README.md).

**Comment by raghavbabbar** [comment]
Can you please assign this to me! If possible

**Comment by raghavbabbar** [comment]
if you are not working on this, could you please assign this to me

**Comment by arpitbbhayani** [comment]
@raghavbabbar this is a test issue. I am crafting a format that makes it self-sufficient. Give me a few hours I will open a bunch of good issues to work on. Give me some time.

**Comment by lucifercr07** [comment]
Closing this issue would open a new one with TCL template. Thanks @raghavbabbar, would assign you on the similar issue once created.
