### ISSUE TITLE
Communication medium like slack/discord

### ISSUE THREAD

**Issue by Hakai-Shin** [DiceDB/dice#48]
**Is your feature request related to a problem? Please describe.**

Is there any medium for communication like slack or discord?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by arpitbbhayani** [comment]
![101-stars](https://user-images.githubusercontent.com/4745789/197318990-e8616341-afa9-4fd4-adb9-dec51fc436ac.PNG)

**Comment by arpitbbhayani** [comment]
Thanks for the suggestion, created the Discord servers for contributors for quick collaboration: https://discord.gg/6r8uXWtXh7
