### ISSUE TITLE
[SAMPLE ISSUE]   Inconsistent `GETEX`: GETEX with big integer should report an error

### ISSUE THREAD

**Issue by AshwinKul28** [DiceDB/dice#481]
## Steps to reproduce

Run the commands mentioned in the test on Line 98 in the file https://github.com/AshwinKul28/dice-tests/tree/main/tcltests/unit/expire.tcl#L98.

## Expected output

The expected output when the above set of commands when run on Redis

```
ERR invalid expire time in 'getex' command
```

## Observed output

The observed output when the above set of commands when run on DiceDB

```
bar
```

The steps to run the test cases are mentioned in the README of the [dice-tests repository](https://github.com/AshwinKul28/dice-tests).

## Expectations for resolution

This issue will be considered resolved when the following things are done

1. changes in the [`dice`](https://github.com/dicedb/dice) code to meet the expected behavior
2. Successful run of the tcl test behavior

You can find the tests under the `tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [setup DiceDB locally](https://github.com/dicedb/dice)
- [setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [setup DiceDB CLI](https://github.com/dicedb/dice)

**Comment by sanuj96** [comment]
Can I work on this issue? @AshwinKul28

**Comment by arpitbbhayani** [comment]
@sanuj96 we are just testing something. good-first issues will be added very soon :) thanks for being so eager. it means a ton.

**Comment by sanuj96** [comment]
@arpitbbhayani Thanks Arpit. Would wait.
