### ISSUE TITLE
Improve test coverage for Query Execution and document feature gaps.

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#483]
DiceDB includes a SQL parser and query executor to support Dice-flavoured SQL (DSQL) queries on top of in-memory key-value data. This is a critical component and needs to be extremely stable and well-tested.

The tests for this component can be found under:
* [tests/qwatch_test.go](https://github.com/DiceDB/dice/blob/master/tests/qwatch_test.go) - end-to-end test for QWATCH command, which tests query execution and message delivery.
* [internal/querywatcher/dsql_test.go](https://github.com/DiceDB/dice/blob/master/internal/querywatcher/dsql_test.go) - DSQL parser test which validates SQL query parsing.
* [internal/querywatcher/executor_test.go](https://github.com/DiceDB/dice/blob/master/internal/querywatcher/executor_test.go) - executor unit tests which test for correct query results in the executor.

## Requirements for this issue
* Find feature gaps and report them under this issue, we will create new issues out of them if they are valid.
* Improve test coverage with more query patterns.
  * Check if certain query patterns are not being validated, think combinations of different features (WHERE + ORDER BY, ORDER BY + LIMIT, etc.)
  * Add tests for such patterns
* Try to break the QWATCH feature, and report findings.

**Comment by mo-pankaj** [comment]
Hi @JyotinderSingh can you assign me this?

**Comment by JyotinderSingh** [comment]
> Hi @JyotinderSingh can you assign me this?

Please feel free to begin working on this issue and report findings here. This issue can be taken up by multiple people at the same time so I won't be assigning it to anyone in particular (to avoid confusion)

**Comment by vaibspider** [comment]
Hi @JyotinderSingh, somehow the links above for tests don't seem to work.
Are these tests really present in the master branch?

**Comment by JyotinderSingh** [comment]
> Hi @JyotinderSingh, somehow the links above for tests don't seem to work.
> 
> Are these tests really present in the master branch?

They have been moved under the integration_tests directory

**Comment by vaibspider** [comment]
I see, thanks!

**Comment by vaibspider** [comment]
I think there's a discrepancy in the documentation about the syntax for DSQL.
In the documentation here: [qwatch-doc](https://dicedb.io/commands/qwatch/), this is specified:

> SELECT $key, $value  FROM 'key_pattern'
WHERE condition
ORDER BY field [ASC | DESC] LIMIT n

while the tests here: [qwatch_test](https://github.com/DiceDB/dice/blob/master/integration_tests/commands/qwatch_test.go) uses the 'like' keyword:

> SELECT $key, $value WHERE $key like 'match:10?:*' ORDER BY $value desc LIMIT 3

**Comment by arpitbbhayani** [comment]
@vaibspider yes, we recently changed it. Now we do not need `FROM` clause. Can you raise a PR in `docs` repository? it would be a great help.

**Comment by vaibspider** [comment]
Sure, will do that!

**Comment by AshwinKul28** [comment]
Closing the issue as PR is already merged.
