### ISSUE TITLE
Add support for command [JSON.ARRLEN]

### ISSUE THREAD

**Issue by jujiale** [DiceDB/dice#484]
Implement [JSON.ARRLEN] command
**Report the length of the JSON array at path in key**
`JSON.ARRLEN key [path]`

**Return**
`JSON.ARRLEN returns an array of integer replies, an integer for each matching value, each is the array's length, or nil, if the matching value is not an array.`

refer to [json.arrlen](https://redis.io/docs/latest/commands/json.arrlen/)
Add unit and integration tests

**Comment by jujiale** [comment]
@JyotinderSingh hello,  I will add this command for dice. please assign it to me. thanks.

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh hello,  I will add this command for dice. please assign it to me. thanks.

Thanks @jujiale! Assigned

**Comment by arpitbbhayani** [comment]
https://github.com/DiceDB/dice/issues/488
