### ISSUE TITLE
Add support for command `JSON.ARRAPPEND`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#485]
Add support for the `JSON.ARRAPPEND` command in DiceDB similar to the [`JSON.ARRAPPEND` command in Redis](https://redis.io/docs/latest/commands/command-list/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by raghavbabbar** [comment]
could you please assign this to me

**Comment by arpitbbhayani** [comment]
@raghavbabbar you already have a few on your plate, once you wrap that you can pick this one. trying to be fair here to others :) but thank you so much for being so eager.

**Comment by srivastava-yash** [comment]
@arpitbbhayani, I can pick this up. could you assign this to me?

**Comment by lucifercr07** [comment]
@srivastava-yash assigned, thanks for picking this up.

**Comment by srivastava-yash** [comment]
@lucifercr07 @JyotinderSingh Quick question: So in JSON.ARRAPPEND we want to append to a list at a given path, so should I check the type of the fields that are already there in the array and then convert this value in the argument to the same type and only then append, right? 
Or should I just append it assuming the user knows what they are appending? Either I can just run a sonic.UnmarshalString on the arg and just append. What do you suggest? Nothing was mentioned in the redis doc about it, maybe I can try finding it in their code

**Comment by JyotinderSingh** [comment]
> @lucifercr07 @JyotinderSingh Quick question: So in JSON.ARRAPPEND we want to append to a list at a given path, so should I check the type of the fields that are already there in the array and then convert this value in the argument to the same type and only then append, right? 
> 
> Or should I just append it assuming the user knows what they are appending? Either I can just run a sonic.UnmarshalString on the arg and just append. What do you suggest? Nothing was mentioned in the redis doc about it, maybe I can try finding it in their code

You need to check the type of object already present at any path which you'd like to modify. If the object doesn't match the expected type you'll return an error. Ensure that test cases validating this behavior are also added.
Additionally, run the same commands on a redis instance (redis docs pages have an embedded cli to run redis commands) and ensure the results (including error responses) are consistent.
