### ISSUE TITLE
Add support for command `JSON.DEBUG HELP`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#492]
Add support for the `JSON.DEBUG HELP` command in DiceDB similar to the [`JSON.DEBUG HELP` command in Redis](https://redis.io/docs/latest/commands/command-list/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by jujiale** [comment]
please assgin to me. thanks.

**Comment by kaifkh20** [comment]
I think issue #493 will be sufficient for this.

**Comment by psrvere** [comment]
I agree. 

@lucifercr07 - #491 #492 and #493 are referring to just one command with two subcommands: `json.debug help` and `json.debug memory`. The former subcommand is just help text. Should we combine these 3 as one issue?

**Comment by lucifercr07** [comment]
We can keep the issues open as it is for reference purpose. You can work on both i.e. #492 and #493 together, will assign.
