### ISSUE TITLE
Add support for command `JSON.DEBUG MEMORY`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#493]
Add support for the `JSON.DEBUG MEMORY` command in DiceDB similar to the [`JSON.DEBUG MEMORY` command in Redis](https://redis.io/docs/latest/commands/command-list/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by jujiale** [comment]
please assgin to me. thanks.

**Comment by lucifercr07** [comment]
@jujiale I believe you already have a few issues assigned (#484, #487, #503). Once you wrap those up, you’re welcome to pick this one. Want to make sure everyone gets a chance to contribute :) Thanks so much for your eagerness and enthusiasm.

**Comment by lucifercr07** [comment]
@psrvere assigned, thanks for picking this up.

**Comment by jujiale** [comment]
> @jujiale I believe you already have a few issues assigned (#484, #487, #489, #490, #503). Once you wrap those up, you’re welcome to pick this one. Want to make sure everyone gets a chance to contribute :) Thanks so much for your eagerness and enthusiasm.
get it, let's build dice stronger together

**Comment by psrvere** [comment]
Update - I am almost done with the feature, just closing out the test cases. I have a few questions.

While trying to match responses with redis, I realised dice existing JSON commands implementation vary in responses as compared to redis. 

Let's look at JSON.GET, for example.

![Response Comparison](https://github.com/user-attachments/assets/1b368174-bbdc-493a-9a81-9ef5681efde4)

[Data Link](https://docs.google.com/spreadsheets/d/1cvgVa5fzs5hfDaPBNFHcXS_YFixiqiuzkE97cDgpqXA/edit?usp=sharing)

As you can see, there are several inconsistencies between redis and dice responses. 

I have three questions:

1. Which of the above are bugs, which one are not relevant and which one a matter of prioritisation / design decisions?
2. How do I decide what is good enough consistency for a feature?
3. Any other principles / rules that I should be aware of?

cc - @lucifercr07 @JyotinderSingh

**Comment by JyotinderSingh** [comment]
> Update - I am almost done with the feature, just closing out the test cases. I have a few questions.
> 
> 
> 
> While trying to match responses with redis, I realised dice existing JSON commands implementation vary in responses as compared to redis. 
> 
> 
> 
> Let's look at JSON.GET, for example.
> 
> 
> 
> ![Response Comparison](https://github.com/user-attachments/assets/1b368174-bbdc-493a-9a81-9ef5681efde4)
> 
> 
> 
> [Data Link](https://docs.google.com/spreadsheets/d/1cvgVa5fzs5hfDaPBNFHcXS_YFixiqiuzkE97cDgpqXA/edit?usp=sharing)
> 
> 
> 
> As you can see, there are several inconsistencies between redis and dice responses. 
> 
> 
> 
> I have three questions:
> 
> 
> 
> 1. Which of the above are bugs, which one are not relevant and which one a matter of prioritisation / design decisions?
> 
> 2. How do I decide what is good enough consistency for a feature?
> 
> 3. Any other principles / rules that I should be aware of?
> 
> 
> 
> cc - @lucifercr07 @JyotinderSingh 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

The JSON library we use does not support the entirety of JSON Path syntax. As of now we do not have a better approach of handling this.
We can think about 100% coverage of the JSON Path syntax once the system is more mature.

**Comment by JyotinderSingh** [comment]
The sheet mentioning the inconsistencies is super helpful, thanks @psrvere!
