### ISSUE TITLE
Add support for command `JSON.OBJKEYS`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#498]
Add support for the `JSON.OBJKEYS` command in DiceDB similar to the [`JSON.OBJKEYS` command in Redis](https://redis.io/docs/latest/commands/command-list/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by vigneshrajkumar** [comment]
@arpitbbhayani I'll signup for this

**Comment by lucifercr07** [comment]
@vigneshrajkumar assigned, thanks for picking this up.

**Comment by iamskp11** [comment]
Hey @lucifercr07 @vigneshrajkumar  ,
Since there are no updates here since 5 days, is this still being worked on? Will be happy to work on this

**Comment by JyotinderSingh** [comment]
> Hey @lucifercr07 @vigneshrajkumar  ,
> 
> Since there are no updates here since 5 days, is this still being worked on? Will be happy to work on this

Assigned

**Comment by iamskp11** [comment]
Hey @JyotinderSingh @lucifercr07  , 
Consider this case where a path matches with multiple JSON objects. In that cases, we will have array of arrays, where each inner array will contain a list of keys at one of the matching path. 

The inner arrays will be randomly arranged + keys inside inner array will also be in random order. Similar to what happens with `json.get`. In Redis, we always get same ordering, similar to what is stored in JSON. 

I have implemented functionality of JSON.OBJKEYS, but was confused with what approach can I take to perform integration test. 

As of now, for testing, once I have output, I am trying to sort each individual inner array (if it is a list of key), and then matching it with expected result (which is also sorted in same way). Have tested on mutliple cases, and also verified the results with redis-stack-server, and they look correct.

Do you have some other idea which I can take for testing in this particular case?

<img width="320" alt="image" src="https://github.com/user-attachments/assets/ed974754-1139-47d3-84a4-13939fdfe0bc">

**Comment by JyotinderSingh** [comment]
> Hey @JyotinderSingh @lucifercr07  , 
> 
> Consider this case where a path matches with multiple JSON objects. In that cases, we will have array of arrays, where each inner array will contain a list of keys at one of the matching path. 
> 
> 
> 
> The inner arrays will be randomly arranged + keys inside inner array will also be in random order. Similar to what happens with `json.get`. In Redis, we always get same ordering, similar to what is stored in JSON. 
> 
> 
> 
> I have implemented functionality of JSON.OBJKEYS, but was confused with what approach can I take to perform integration test. 
> 
> 
> 
> As of now, for testing, once I have output, I am trying to sort each individual inner array (if it is a list of key), and then matching it with expected result (which is also sorted in same way). Have tested on mutliple cases, and also verified the results with redis-stack-server, and they look correct.
> 
> 
> 
> Do you have some other idea which I can take for testing in this particular case?
> 
> 
> 
> <img width="320" alt="image" src="https://github.com/user-attachments/assets/ed974754-1139-47d3-84a4-13939fdfe0bc">
> 
> 
> 
> 

Array ordering inside array fields is deterministic. Field ordering inside JSON is not deterministic.

You cannot sort the array as a part of the test, since it defeats the purpose of the array being a sorted container. Note that our JSON.GET implementation also maintains correct array ordering. So this is a non-issue.

However in case of field ordering being non deterministic, we have tackled this so far by providing all possible permutations of the result set. Another more idiomatic possibility if you can it in your test code is to use assert.ElementsMatch (it's present somewhere in the code)

**Comment by JyotinderSingh** [comment]
Also, we don't need to handle this in our server code, JSON standard doesn't enforce key ordering for the json fields.

**Comment by JyotinderSingh** [comment]
We had discussion around thjs behaviour in the following pull request https://github.com/DiceDB/dice/pull/365

**Comment by JyotinderSingh** [comment]
> Hey @JyotinderSingh ,
> 
> I read the discussion in PR #365 . 
> 
> 
> 
> Ordering inside Array  is fine, they are deterministic. 
> 
> Non-deterministic key ordering is also expected for JSON.
> 
> 
> 
> What I meant to say is, in case of `$..a` path, we would be getting the multiple path values in any random order. Inside those json objects, the keys are also in any random order.
> 
> 
> 
> Suppose json is 
> 
> <img width="429" alt="image" src="https://github.com/user-attachments/assets/6f0fde21-801f-4f01-805f-a5529db64f04">
> 
> 
> 
> If we say `json.get $..a`, we would be getting the three `a` values in any order (non-deterministic). 
> 
> `"[{\"b\":2,\"c\":1},{\"big_key1\":1,\"big_key2\":2},[3]]"` , or
> 
> `"[{\"big_key2\":2,\"big_key1\":1},{\"b\":2,\"c\":1},[3]]"`, or
> 
> `"[{\"big_key1\":1,\"big_key2\":2},{\"b\":2,\"c\":1},[3]]"`, or
> 
> `"[{\"c\":1,\"b\":2},{\"big_key1\":1,\"big_key2\":2},[3]]"`
> 
> 
> 
> 
> 
> Now, the `json.objkeys` would be responding as
> 
> `[[b c ] [big_key1 big_key2] (nil)]`, 
> 
> `[ [big_key2 big_key1] [b c] (nil)]`,
> 
> `[[big_key1 big_key2] [b c] (nil)]`,
> 
> `[[c b ] [big_key1 big_key2] (nil)]` respectively for above 4 values of path `$..a`.
> 
> 
> 
> All the above four combinations are possible  (some more are possible too) and are correct. 
> 
> 
> 
> So, in these cases, maybe sorting and then comparing with sorted expected value would be a good way to test. Other way can be to have all possible permutations(of array of arrays) as expected value, and then check if result is one of them. 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

We have a helper method to check for array permutations, can we make use of that?

**Comment by iamskp11** [comment]
> > Hey @JyotinderSingh ,
> > I read the discussion in PR #365 .
> > Ordering inside Array  is fine, they are deterministic.
> > Non-deterministic key ordering is also expected for JSON.
> > What I meant to say is, in case of `$..a` path, we would be getting the multiple path values in any random order. Inside those json objects, the keys are also in any random order.
> > Suppose json is
> > <img alt="image" width="429" src="https://private-user-images.githubusercontent.com/54633306/368206547-6f0fde21-801f-4f01-805f-a5529db64f04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODc4NzksIm5iZiI6MTcyNjU4NzU3OSwicGF0aCI6Ii81NDYzMzMwNi8zNjgyMDY1NDctNmYwZmRlMjEtODAxZi00ZjAxLTgwNWYtYTU1MjlkYjY0ZjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE1MzkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjOWI3MjFlYTdkN2NkZmQ2MmI2NGZlMTJjNmQyNDU2NTUwYjkwYzQzM2ZhOWQyYmVkNzU5OGM2ZmI1YzdmMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ff95CK6Pe88p-hB2JnaTIGm0P7RtCSQwvxAXkwEjD7U">
> > If we say `json.get $..a`, we would be getting the three `a` values in any order (non-deterministic).
> > `"[{\"b\":2,\"c\":1},{\"big_key1\":1,\"big_key2\":2},[3]]"` , or
> > `"[{\"big_key2\":2,\"big_key1\":1},{\"b\":2,\"c\":1},[3]]"`, or
> > `"[{\"big_key1\":1,\"big_key2\":2},{\"b\":2,\"c\":1},[3]]"`, or
> > `"[{\"c\":1,\"b\":2},{\"big_key1\":1,\"big_key2\":2},[3]]"`
> > Now, the `json.objkeys` would be responding as
> > `[[b c ] [big_key1 big_key2] (nil)]`,
> > `[ [big_key2 big_key1] [b c] (nil)]`,
> > `[[big_key1 big_key2] [b c] (nil)]`,
> > `[[c b ] [big_key1 big_key2] (nil)]` respectively for above 4 values of path `$..a`.
> > All the above four combinations are possible  (some more are possible too) and are correct.
> > So, in these cases, maybe sorting and then comparing with sorted expected value would be a good way to test. Other way can be to have all possible permutations(of array of arrays) as expected value, and then check if result is one of them.
> 
> We have a helper method to check for array permutations, can we make use of that?

I can see one : `arraysArePermutations` - it is for 1D integer array . 
This case is different - output is 2D array, with randomness at both levels - arrays and array fields.

**Comment by JyotinderSingh** [comment]
> > > Hey @JyotinderSingh ,
> 
> > > I read the discussion in PR #365 .
> 
> > > Ordering inside Array  is fine, they are deterministic.
> 
> > > Non-deterministic key ordering is also expected for JSON.
> 
> > > What I meant to say is, in case of `$..a` path, we would be getting the multiple path values in any random order. Inside those json objects, the keys are also in any random order.
> 
> > > Suppose json is
> 
> > > <img alt="image" width="429" src="https://private-user-images.githubusercontent.com/54633306/368206547-6f0fde21-801f-4f01-805f-a5529db64f04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODc4NzksIm5iZiI6MTcyNjU4NzU3OSwicGF0aCI6Ii81NDYzMzMwNi8zNjgyMDY1NDctNmYwZmRlMjEtODAxZi00ZjAxLTgwNWYtYTU1MjlkYjY0ZjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE1MzkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjOWI3MjFlYTdkN2NkZmQ2MmI2NGZlMTJjNmQyNDU2NTUwYjkwYzQzM2ZhOWQyYmVkNzU5OGM2ZmI1YzdmMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ff95CK6Pe88p-hB2JnaTIGm0P7RtCSQwvxAXkwEjD7U">
> 
> > > If we say `json.get $..a`, we would be getting the three `a` values in any order (non-deterministic).
> 
> > > `"[{\"b\":2,\"c\":1},{\"big_key1\":1,\"big_key2\":2},[3]]"` , or
> 
> > > `"[{\"big_key2\":2,\"big_key1\":1},{\"b\":2,\"c\":1},[3]]"`, or
> 
> > > `"[{\"big_key1\":1,\"big_key2\":2},{\"b\":2,\"c\":1},[3]]"`, or
> 
> > > `"[{\"c\":1,\"b\":2},{\"big_key1\":1,\"big_key2\":2},[3]]"`
> 
> > > Now, the `json.objkeys` would be responding as
> 
> > > `[[b c ] [big_key1 big_key2] (nil)]`,
> 
> > > `[ [big_key2 big_key1] [b c] (nil)]`,
> 
> > > `[[big_key1 big_key2] [b c] (nil)]`,
> 
> > > `[[c b ] [big_key1 big_key2] (nil)]` respectively for above 4 values of path `$..a`.
> 
> > > All the above four combinations are possible  (some more are possible too) and are correct.
> 
> > > So, in these cases, maybe sorting and then comparing with sorted expected value would be a good way to test. Other way can be to have all possible permutations(of array of arrays) as expected value, and then check if result is one of them.
> 
> > 
> 
> > We have a helper method to check for array permutations, can we make use of that?
> 
> 
> 
> I can see one : `arraysArePermutations` - it is for 1D integer array . 
> 
> This case is different - output is 2D array, with randomness at both levels - arrays and array fields.

Yeah, got it. Can you try to make the existing method work with multiple levels? If that doesn't work we can go ahead with writing the permutations ourselves and comparing against those.
