### ISSUE TITLE
Add support for command `JSON.OBJLEN`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#499]
Add support for the `JSON.OBJLEN` command in DiceDB similar to the [`JSON.OBJLEN` command in Redis](https://redis.io/docs/latest/commands/command-list/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by rushabhk04** [comment]
Assign this issue to me. Thanks

**Comment by lucifercr07** [comment]
@rushabhk04 assigned, thanks for picking this up.

**Comment by iamskp11** [comment]
Hey @lucifercr07 @rushabhk04 ,
Since there are no updates here since 5 days, is this still being worked on? Will be happy to work on this

**Comment by rushabhk04** [comment]
Yes, please go ahead with it. Thanks

**Comment by iamskp11** [comment]
Hey @lucifercr07 , have picked this one, and have done basic method implementation. Will be sharing PR post tests and benchmarking memory + time. Thanks!

**Comment by phaneesh707** [comment]
Hey @iamskp11 , i'm really sorry didn't notice that you are also working on it , since this issue was inactive i just started working on and created a PR for it.Sorry!
@lucifercr07 could you please review the PR,thanks.
