### ISSUE TITLE
Inconsistent `EXPIRE`: EXPIRE with big integer overflows when converted to milliseconds

### ISSUE THREAD

**Issue by AshwinKul28** [DiceDB/dice#504]
## Steps to reproduce

Run the commands mentioned in the test on Line 110 in the file https://github.com/AshwinKul28/dice-tests/tree/main/tcltests/unit/expire.tcl#L110.

## Expected output

The expected output when the above set of commands when run on Redis

```
ERR invalid expire time in 'expire' command
```

## Observed output

The observed output when the above set of commands when run on DiceDB

```
1
```

The steps to run the test cases are mentioned in the README of the [dice-tests repository](https://github.com/AshwinKul28/dice-tests).

## Expectations for resolution

This issue will be considered resolved when the following things are done

1. changes in the [`dice`](https://github.com/dicedb/dice) code to meet the expected behavior
2. Successful run of the tcl test behavior

You can find the tests under the `tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [setup DiceDB locally](https://github.com/dicedb/dice)
- [setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [setup DiceDB CLI](https://github.com/dicedb/dice)

**Comment by raghavbabbar** [comment]
@AshwinKul28 if you aren't working on this, could you please assign this to me

**Comment by arpitbbhayani** [comment]
@raghavbabbar :D you have one JSON issue already assigned, wrap that up first :) then you can pick others. once again, thank you for being so eager :D

**Comment by ashwaniYDV** [comment]
@AshwinKul28 @arpitbbhayani please assign this to me

**Comment by arpitbbhayani** [comment]
@ashwaniYDV Go for it and thanks for taking this up.
