### ISSUE TITLE
Inconsistent `EXPIRE`: EXPIRE with XX option on a key without ttl

### ISSUE THREAD

**Issue by AshwinKul28** [DiceDB/dice#509]
## Steps to reproduce

Run the commands mentioned in the test on Line 493 in the file https://github.com/AshwinKul28/dice-tests/tree/main/tcltests/unit/expire.tcl#L493.

## Expected output

The expected output when the above set of commands when run on Redis

```
-1
```

## Observed output

The observed output when the above set of commands when run on DiceDB

```
199
```

The steps to run the test cases are mentioned in the README of the [dice-tests repository](https://github.com/AshwinKul28/dice-tests).

## Expectations for resolution

This issue will be considered resolved when the following things are done

1. changes in the [`dice`](https://github.com/dicedb/dice) code to meet the expected behavior
2. Successful run of the tcl test behavior

You can find the tests under the `tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [setup DiceDB locally](https://github.com/dicedb/dice)
- [setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [setup DiceDB CLI](https://github.com/dicedb/dice)

**Comment by jainam2907** [comment]
@arpitbbhayani @AshwinKul28 Can you please assign this issue to me?

**Comment by arpitbbhayani** [comment]
@jainam2907 assigned. Thank you for taking this up.

**Comment by AshwinKul28** [comment]
HI @jainam2907 Can you please add evidence to all the fixes. Please run the test and provide observed outputs.

**Comment by jainam2907** [comment]
Hi @AshwinKul28, Sorry for the delay. 
I have added the RCA, resolution, and the tcl test output [here](https://github.com/DiceDB/dice/pull/513#issuecomment-2339650823).
