### ISSUE TITLE
BUG: Deadlock while cache eviction

### ISSUE THREAD

**Issue by apoorvyadav1111** [DiceDB/dice#520]
Hi team,

This issue was first reported as per conversation on the discord community by **Ritik**. To replicate the issue, please follow the steps below:

1. Update the KeysLimit  in dice/config/config.go
`var KeysLimit int = 2 // default buffer size.`
2. Run following commands
`mset a b c d` works fine
`set x y` should lead to deadlock

Upon initial debugging, I found the issue is due to the locks being acquired in functions when trying to set a new value. Please find the sequence leading to deadlock below:

1. evalSet calls store.Put()
2. store.Put() calls PutHelper with acquiring Lock()
3. PutHelper() validates the key limit and goes for eviction via store.evict()
4. In populateEvictionPool() we try to get RLock() to evict, which causes deadlock as Lock() is already acquired on step 2.

cc: @JyotinderSingh 

Regards,
Apoorv

**Comment by aashraybhandar1** [comment]
Hey @apoorvyadav1111  are you picking this up? If not I would like to pick this up

**Comment by ayadav16** [comment]
Hi @aashraybhandar1 , You can pick this up. However, I will not be able to assign this issue to you since I don't have the permissions.

Apoorv

**Comment by apoorvyadav1111** [comment]
Hey @aashraybhandar1 , You can pick this up. Though, I don't have GitHub permission to assign this issue to you.
Apoorv

**Comment by lucifercr07** [comment]
@aashraybhandar1 Assigned, thanks for contributing.

**Comment by aashraybhandar1** [comment]
@lucifercr07 @apoorvyadav1111 Created a PR: #529 . Would appreciate feedback from you guys. Thank You!

**Comment by JyotinderSingh** [comment]
No longer an issue since we removed all store level locks.
