### ISSUE TITLE
Adding support for command `SHUTDOWN`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#54]
**Is your feature request related to a problem? Please describe.**
There is no way for a client to initiate a shutdown of the server. We need this to shut down the server gracefully after running tests.

**Describe the solution you'd like**
We need a command `SHUTDOWN` that shuts down the server, gracefully.

**Comment by chowmean** [comment]
Hi @arpitbbhayani , can you please elaborate more on what you have in mind? 
Personally, I don't think the client should be able to do a shutdown the server. These functionalities are generally available with the sysadmin and are done at the Linux service level.

**Comment by arpitbbhayani** [comment]
I agree. But we are adding this to facilitate tests. The commend will be disabled in production setup.

**Comment by arpitbbhayani** [comment]
I recommend you to wait for my big PR to merge, I think this might just become redundant. Let me get my PR merged and we will be in a position to decide if we really need SHUTDOWN or not. Should be able to converge in next couple of days.
