### ISSUE TITLE
Wrong/Un-implemented commands returns "PONG"

### ISSUE THREAD

**Issue by sahil1913** [DiceDB/dice#55]
**Describe the bug**
Wrong/un-implemented commands when fired returns "PONG".
This can create confusion on the behaviour altogether

**To Reproduce**
1. run some 
2. enter gibberish as a command

**Expected behavior**
Return a correct response stating either command not implemented or wrong command fired.

@arpitbbhayani to share the correct response format.

**Comment by sahil1913** [comment]
@arpitbbhayani please add response format/string..
I'll work on this issue, should be a quick fix

**Comment by AshwinKul28** [comment]
<img width="481" alt="Screenshot 2024-09-08 at 5 32 43 PM" src="https://github.com/user-attachments/assets/e840b892-3400-4402-82f9-363d8e8fdc39">

Already dice server is taking care of this, closing the issue.
