### ISSUE TITLE
Add Support for JSON.INGEST Command in RESP Protocol

### ISSUE THREAD

**Issue by pratikpandey21** [DiceDB/dice#552]
### Description

Extend support for the JSON.INGEST command to the RESP (REdis Serialization Protocol) format. This command allows users to set a value based on a dynamically generated key, where the key is generated using a key prefix and a unique identifier. The key prefix will be provided as an argument in the RESP command.

### Command Overview:

**Command**: JSON.INGEST
**Example**: JSON.INGEST <key_prefix> <JSON_value>
**Functionality**: This command functions like the SET command, but instead of specifying a full key, the user provides a key prefix. The full key is generated by appending a unique identifier to the key prefix, and the provided JSON value is stored against this generated key.

### Details:

The command will act like the existing SET command, where:

- key_prefix is the prefix of the key that the user wants to use.
- JSON_value is the value to be stored in JSON format.

The complete key is dynamically generated by appending a unique identifier to the provided key prefix.

### Tasks:
- Implement the JSON.INGEST command support in RESP.
- Create comprehensive documentation in DiceDB Docs for the JSON.INGEST command in RESP, including usage examples, parameter descriptions, and potential use cases.

**Comment by pratikpandey21** [comment]
Depends On: https://github.com/DiceDB/dice/issues/551

**Comment by rishirishhh** [comment]
I would like to work on this issue if its not assigned to anyone @arpitbbhayani

**Comment by bhagatvansh** [comment]
Hi @pratikpandey21 I would you like to collaborate on this issue as well

**Comment by lucifercr07** [comment]
@rishirishhh thanks for contributing, assigned.

**Comment by bhagatvansh** [comment]
Hi @lucifercr07 can 2 people collaborate on the same issue?

**Comment by lucifercr07** [comment]
Closing, merged as part of https://github.com/DiceDB/dice/pull/588.

**Comment by pratikpandey21** [comment]
@rishirishhh any updates from your side, please let us know if any blockers.

**Comment by pratikpandey21** [comment]
@rishirishhh any updates from your side, please let us know if any blockers.

**Comment by psrvere** [comment]
@pratikpandey21 - I think this is done in #551.

**Comment by lucifercr07** [comment]
Closing as merged as part of [PR](https://github.com/DiceDB/dice/pull/588).
cc: @pratikpandey21
