### ISSUE TITLE
Add Support for QWATCH Command with HTTP

### ISSUE THREAD

**Issue by pratikpandey21** [DiceDB/dice#553]
### Description

Implement support for the QWATCH command over HTTP, utilizing Server-Sent Events (SSE) to enable real-time updates to clients based on changes to underlying data. This enhancement will allow HTTP clients to subscribe to SQL-like queries over data structures and receive push notifications whenever the results of the query change, providing a more efficient alternative to polling for updates.

### Command Overview:

Command: QWATCH
HTTP Method: POST
Endpoint: /QWATCH
Body: SQL Query. Check [here](https://dicedb-docs.netlify.app/commands/qwatch/) for Query reference.

### Behaviour with HTTP:

**Subscription Mechanism:**

- When an HTTP client sends a POST request to the /QWATCH endpoint with the query parameter, the server establishes a persistent connection using Server-Sent Events (SSE).
- The server continuously monitors the data matching the specified query.
- Whenever a data modification affects the query results, the server updates the client over the SSE connection.

**Response Format:**

The server responds with an HTTP 200 OK status and sets the Content-Type header to text/event-stream.
Each update is sent as an SSE event with the following format:

`data: [{"key": "<key>", "value": <JSON value>}]`

### Tasks:

- Implement the /QWATCH endpoint to accept HTTP POST requests.
- Establish an SSE connection and manage it efficiently to support multiple concurrent clients.
- Create comprehensive documentation for using QWATCH over HTTP, including examples.

**Comment by lucifercr07** [comment]
@pratikpandey21 would like to work on this.

**Comment by lucifercr07** [comment]
Closing, merged as part of #614

**Comment by lucifercr07** [comment]
Closing, merged as part of https://github.com/DiceDB/dice/pull/614
