### ISSUE TITLE
Add Integration Tests for HTTP Server

### ISSUE THREAD

**Issue by pratikpandey21** [DiceDB/dice#558]
Develop integration tests for the newly added HTTP server in DiceDB to ensure its correct functionality and robustness. These tests should be similar to those that exist for the **AsyncServer** and should cover a wide range of scenarios to validate the HTTP server's behavior under different conditions.

**Comment by pratikpandey21** [comment]
Depends on #551

**Comment by tdadadavid** [comment]
Please can this be assigned to me, I worked on the test for the asyncTestServer #531

**Comment by lucifercr07** [comment]
@tdadadavid thanks for contributing, assigned.

**Comment by Shikha-code36** [comment]
Please can this be assigned to me I have created a PR regarding HTTP server integration tests https://github.com/DiceDB/dice/pull/598

**Comment by tdadadavid** [comment]
#621 I have raised a PR and converted it to a draft.
@lucifercr07

**Comment by pratikpandey21** [comment]
@Shikha-code36 This issue was assigned to @tdadadavid, and he's made good progress. Please pick up any unassigned issues, so we don't do redundant work.

Thanks for contributing to Dice. Keep an eye out for new issues, as there will be more regarding TCL tests soon.

**Comment by lucifercr07** [comment]
Closing merged as part of #694 #708
