### ISSUE TITLE
Multi Threading Support: Refactor store layer implementation

### ISSUE THREAD

**Issue by soumya-codes** [DiceDB/dice#567]
Refactor store layer implementation to align with EVAL related changes required for Multi Threading Support.

For more details check:
https://github.com/DiceDB/dice/issues/565

Check reference implementation here:
https://github.com/soumya-codes/dicestorepoc

**Comment by AshikBN** [comment]
@soumya-codes would like to work on this. happy to collaborate with other people if it requires more hands.

**Comment by pratikpandey21** [comment]
I can involve you once I get to a position where I can split the work @AshikBN

**Comment by AshikBN** [comment]
Sure, makes sense. I'm currently understanding the codebase.
Please assign one when the task is broken down...  or if you have any easy to medium-level issue. thanks @pratikpandey21 @soumya-codes

**Comment by shashank-priyadarshi** [comment]
@pratikpandey21 @soumya-codes can I please take this up!
