### ISSUE TITLE
Multi Threading Support: Integrate Shard/Worker implementation with EVAL/Store changes

### ISSUE THREAD

**Issue by soumya-codes** [DiceDB/dice#568]
This would be the final step in the Multi Threading Support.

Its advisable to be take up this task after the following tasks are complete:
1. https://github.com/DiceDB/dice/issues/565
2. https://github.com/DiceDB/dice/issues/566
3. https://github.com/DiceDB/dice/issues/567

Integrate EVAL/Store level changes with the Shard implementation.
Integrate the EVAL/Store level changes Worker changes in the PR https://github.com/DiceDB/dice/pull/539

**Note:** We need to ensure that the integration tests are also updated accordingly.

**Comment by aashraybhandar1** [comment]
Hey @soumya-codes would like to pick this up when the above issues are done. Thank You!

**Comment by kaustubhdeokar** [comment]
@soumya-codes , please assign this to me

**Comment by N3XT14** [comment]
@lucifercr07 @soumya-codes . Can I take this up?

I have had other commits in this and other repo with difficulty-level hard. 

Thanks
