### ISSUE TITLE
Add support for Redis `SELECT` command

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#569]
Add support for the `SELECT` command in DiceDB similar to the [`SELECT` command in Redis](https://redis.io/docs/latest/commands/select/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by JyotinderSingh** [comment]
While DiceDB currently doesn't support multiple logical databases, we need to support this command to unblock certain other tasks.

For now this can be implemented as a dummy command which just responds with RespOk.

**Comment by codeasashu** [comment]
@JyotinderSingh Can I work on this please?

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh Can I work on this please?

Assigned

**Comment by codeasashu** [comment]
@JyotinderSingh can you review PR?
