### ISSUE TITLE
Add support for Redis `TYPE` command 

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#571]
Add support for the `TYPE` command in DiceDB similar to the [`TYPE` command in Redis](https://redis.io/docs/latest/commands/type/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by rishirishhh** [comment]
Kindly assign this task to me

**Comment by JyotinderSingh** [comment]
> Kindly assign this task to me

Assigned.

**Comment by Gauravkumar2701** [comment]
@rishirishhh  are you working on it.

**Comment by rishirishhh** [comment]
yes I am

**Comment by rishirishhh** [comment]
I will be completing the issue in next 2 days

**Comment by lucifercr07** [comment]
Merged as part of https://github.com/DiceDB/dice/pull/601
