### ISSUE TITLE
Add support for Redis `LLEN` command 

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#572]
Add support for the `LLEN` command in DiceDB similar to the [`LLEN` command in Redis](https://redis.io/docs/latest/commands/llen/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by nithinkjoy-tech** [comment]
Hi @JyotinderSingh I would like to work on this.

**Comment by JyotinderSingh** [comment]
> Hi @JyotinderSingh I would like to work on this.

Assigned.

**Comment by jainbhavya53** [comment]
Hi @JyotinderSingh 
Created a PR for the issue: https://github.com/DiceDB/dice/pull/580 

Can you please review it ?

Thanks

**Comment by nithinkjoy-tech** [comment]
Hi @JyotinderSingh, I am unassigning myself as @jainbhavya53 raised PR for this issue.

**Comment by JyotinderSingh** [comment]
> Hi @JyotinderSingh Created a PR for the issue: #580
> 
> Can you please review it ?
> 
> Thanks

Thanks for the PR @jainbhavya53, will review it soon. While we truly appreciate your effort please take care that you work on issues after they are assigned to you to avoid duplicate work being done by you/others.
