### ISSUE TITLE
Inconsistent behaviour in GET command 

### ISSUE THREAD

**Issue by rushabhk04** [DiceDB/dice#596]
GET Command  for SET and JSON in Dice returns value, whereas in Redis, it returns error! Hence it becomes inconsistent. Will be raising a PR with test cases for the same!

Thanks. Please assign this to me.

Regards,
Rushabh

**Comment by lucifercr07** [comment]
@rushabhk04 assigned, thanks for contributing.
Can you please add details around issue, similar to [this](https://github.com/DiceDB/dice/issues/516).

**Comment by rushabhk04** [comment]
Hello Lucifer, 

This issue can be closed as the changes are already present in the current version. So, this can be ignored!

Thanks
