### ISSUE TITLE
 Add support for string sets

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#6]

**Comment by himanishm07** [comment]
@arpitbbhayani Any detail on this? Is the requirement to support String sets in Values?

**Comment by AshwinKul28** [comment]
@arpitbbhayani @JyotinderSingh Still a valid issue? If not we can close, other wise we can assign it to @himanishm07 or someone.

**Comment by sudoharshita16** [comment]
@AshwinKul28 
If no one is working on this, can I work on it?

**Comment by AshwinKul28** [comment]
Sure, @JyotinderSingh please validate this issue, and assign it to @sudoharshita16 . If it's invalid because of very old, they you can pick some latest ones.

**Comment by JyotinderSingh** [comment]
>  @AshwinKul28 @JyotinderSingh 
> 
> If no one is working on this, can I work on it? 

Would recommend picking one of the more recent issues. This issue is not at the top of our priority list for now.

**Comment by sudoharshita16** [comment]
sure okay

**Comment by sudoharshita16** [comment]
@JyotinderSingh 
I went through all the open issues but all are already assigned. I will keep an eye if something new comes up.

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh 
> 
> I went through all the open issues but they are already assigned. I will keep an eye if something new comes up.

We will add a lot of new issues in the upcoming week.

**Comment by AshwinKul28** [comment]
Unfortunately, this was a very old issue and we are revamping the core implementations. This issue is not relevant now; though we will open more relevant ones soon after the rewrite. Closing this.
