### ISSUE TITLE
Need standardized errors

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#61]
We need a way to standardize the errors

- the language
- format
- conventions
- global declarations
- error codes

https://github.com/uber-go/guide/blob/master/style.md#errors

**Comment by manosriram** [comment]
are you working on this? if not, i would like to pick this up. @arpitbbhayani

**Comment by arpitbbhayani** [comment]
@manosriram no one is working on this. You can pick this up. Would recommend you prepare a small draft and your idea and post it on this issue.

We all would converge on the approach.

**Comment by manosriram** [comment]
thanks @arpitbbhayani, will share the draft.

**Comment by lucifercr07** [comment]
@arpitbbhayani I believe this can be closed with merge of https://github.com/DiceDB/dice/pull/288

**Comment by AshwinKul28** [comment]
Yes, good to close now. Thanks @lucifercr07
