### ISSUE TITLE
BUG: Incorrect behavior of keyspace stats and DBSIZE command

### ISSUE THREAD

**Issue by apoorvyadav1111** [DiceDB/dice#615]
Hi,

While going through the code, I observed that we are incrementing the KeyspaceStat count even if the operation is not creating new keys but overwriting the existing ones. This leads to the following behavior in dice:
<img width="424" alt="image" src="https://github.com/user-attachments/assets/55149d83-007f-4018-bb8a-68a337093822">
In Redis:
<img width="292" alt="image" src="https://github.com/user-attachments/assets/cb4d954d-890b-4543-afdd-f2b9f4471bc8">
Please assign this to me, if possible.

**Comment by Abh-ay** [comment]
Hi @apoorvyadav1111  
can i pick this up?

**Comment by apoorvyadav1111** [comment]
Hi @Abh-ay , I have been working on this and will be raising a PR soon. Thank you for your interest in contributing. Please keep watch on new issues.
Apoorv

**Comment by Abh-ay** [comment]
Ok @apoorvyadav1111 
I created PR also for this, should I close this request?
Thanks!!
