### ISSUE TITLE
BUG: FLUSHDB and QWATCH

### ISSUE THREAD

**Issue by apoorvyadav1111** [DiceDB/dice#616]
Hi everyone,

One observation while working on DBSIZE command is when FLUSHDB is executed before QWATCH, the server does not respond further. I will be adding detailed CLI steps soon to reproduce this issue. 
### Edit: Replication Steps:
1. Pull latest master
2. Run server locally
3. Run either redis-cli -p 7379 or dice-cli for setting values, lets say terminal 1
4. Run dicedb-cli (important for Qwatch / subscribe), lets say terminal 2
5. While running the three terminals, run following commands in order.

### SETUP:
in terminal 2:
```subscribe 'SELECT $key, $value WHERE $key like "match:10?:*" ORDER BY $value desc LIMIT 3'```

### GET Updates:
in terminal 1:
```
SET match:100:user:1 23
```
Simultaneously, terminal 2 should update with following result:
```
qwatch    from SELECT $key, $value WHERE $key like 'match:10?:*' ORDER BY $value desc LIMIT 3: [['match:100:user:1', '23']]
``` 

Try setting new values in terminal 2 if you would like and terminal 1 will update with new values. 

### BUG
Run the following command in terminal 1
```
FLUSHDB
```
Now trying setting new values in terminal 2, but this time around terminal 2 will not receive any new update

Please assign this issue to me. 
cc: @JyotinderSingh 

Thanks

**Comment by TheRanomial** [comment]
Hi @apoorvyadav1111 can i work on this one.

**Comment by apoorvyadav1111** [comment]
Hi @TheRanomial , I have been working on this and will be raising a PR soon. 
Apoorv
