### ISSUE TITLE
Benchmarking utility

### ISSUE THREAD

**Issue by Hakai-Shin** [DiceDB/dice#62]
**Is your feature request related to a problem? Please describe.**

This might be too early, but I am curious on how software benchmarking is handled. I got to know redis has a redis-benchmark utility. Can we have benchmarking utility for dice as well. This feature might not be urgent but I am curious to look into this.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AshwinKul28** [comment]
We are leveraging Go Benchmarking utility and developed lot many benchmarking test cases. Closing this issue.
