### ISSUE TITLE
Using CodeRabbit.ai for PR reviews

### ISSUE THREAD

**Issue by rohanjaswal2507** [DiceDB/dice#628]
Hi team,

I have been monitoring the buzz on this project for a few weeks now. However, being not a Go developer and with busy schedules, I have not been able to dive into this yet. I hope to get into contribution soon.

None the less, I was wondering how about using [CodeRabbit](https://coderabbit.ai/) for having PR reviews on this repo. If they are offering a service for public repos, why not use it?

Thanks!

**Comment by vinitparekh17** [comment]
@rohanjaswal2507 We appreciate your suggestion but We do not encourage this kind of issues if you have issues related DiceDB, Bug report, Feature request then feel free to open an issue.

For suggestions, I would recommend you to join [Discord](https://discord.gg/ZAUvTDvz) to get in touch with community.

Thanks!

**Comment by rohanjaswal2507** [comment]
Ah, didn't see that in the documentation. No worries.
