### ISSUE TITLE
Reinforce RESP handler

### ISSUE THREAD

**Issue by rohanverma94** [DiceDB/dice#63]
**Describe the bug**
RESP handler often breaks, need to fix it.
 
**To Reproduce**
DO THIS-
```bash 
(printf '+PING\r\n+PING\r\n';) | nc localhost 7379
(printf '+PING\r\n+PING\r\n';) | nc localhost 7379
(printf '+OING\r\n+PING\r\n';) | nc localhost 7379
```

**Expected behavior**
This should log "Possible security attack" on the server side and disconnect the client issuing the command.

**Additional context**
Try Fuzzers to break the current RESP implementation to explore more steps to reproduce the larger issue with RESP handler.

**Comment by AshwinKul28** [comment]
Closing this issue as shipped.
