### ISSUE TITLE
Command Subcommands should be listed as separate commands

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#635]
The output of `COMMAND LIST` in the current implementation in DiceDB outputs `COMMAND`, but in Redis it outputs all the subcommand as 

```
COMMAND|COUNT
COMMAND|DOCS
COMMAND|GETKEYS
COMMAND|GETKEYSANDFLAGS
COMMAND|HELP
COMMAND|INFO
COMMAND|LIST
```

So, make the output for subcommand of `COMMAND` command same as Redis.

**Comment by hgupta12** [comment]
Can I take this up?

**Comment by arpitbbhayani** [comment]
@hgupta12 Thank you for picking this up.
