### ISSUE TITLE
Redundant conditional in evalGET

### ISSUE THREAD

**Issue by hamdaankhalid** [DiceDB/dice#64]
**Describe the bug**
Not a bug but more of something that caught my eye when reading the codebase. It's my first time looking at or attempting anything open source. Lmk if this is the wrong category to file this. I wanted to open this issue so I could make a corresponding PR and fix this.

Package: core
File: eval.go
Method: evalGET

Get(key) will delete any expired key already, so the conditional listed below is redundant in code.
```
if hasExpired(obj) {
		return RESP_NIL
}
```

**Expected behavior**
Remove redundant condition since Get(key) takes care of the case.

**Comment by AshwinKul28** [comment]
HI @hamdaankhalid , Thanks for this. 
Unfortunately, this was an old issue and we are revamping the core implementations. This issue is not much relevant now, and we have fixed it as well; though we will open more relevant ones soon after the rewrite. Closing this.
