### ISSUE TITLE
Add support for command `BITFIELD_RO`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#640]
Add support for the `BITFIELD_RO` command in DiceDB similar to the [`BITFIELD_RO` command in Redis](https://redis.io/docs/latest/commands/command-list/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by kushal0511-not** [comment]
@arpitbbhayani i would like to work on this, can you please assign to me?

**Comment by arpitbbhayani** [comment]
@kushal0511-not Thanks for taking this up. assigned.

**Comment by anchalsinghrajput** [comment]
hi @kushal0511-not, are you still working on this issue? If not, Can I pick this up?

**Comment by kushal0511-not** [comment]
@anchalsinghrajput i am waiting for #639 to complete , this command will use that command only.

**Comment by apoorvyadav1111** [comment]
Hi @kushal0511-not , #639 is in progress and will need some time to ensure I handle all the edge cases for all 4 subcommands. 
Thanks.

**Comment by apoorvyadav1111** [comment]
Hi @kushal0511-not , I have created a PR #723 for #639. However, It is still a draft so more changes might come upon further testing.
Apoorv

**Comment by kushal0511-not** [comment]
@apoorvyadav1111 Thanks for informing.
I will take a look.

**Comment by kushal0511-not** [comment]
@JyotinderSingh
I’m currently occupied with other work commitments and won’t be able to work on this. Feel free to assign someone else.
Thanks.

**Comment by iamskp11** [comment]
Hey @JyotinderSingh , will get this done since Kushal has unassigned himself. Please assign to me!

**Comment by JyotinderSingh** [comment]
> Hey @JyotinderSingh , will get this done since Kushal has unassigned himself. Please assign to me!

Assigned

**Comment by apoorvyadav1111** [comment]
Hi @iamskp11, bitfield has been implemented. This issue was tagged as dependent on the bitfield command, so just wanted to share update here.
