### ISSUE TITLE
Add support for command `HINCRBY`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#647]
Add support for the `HINCRBY` command in DiceDB similar to the [`HINCRBY` command in Redis](https://redis.io/docs/latest/commands/command-list/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by hash-f** [comment]
@arpitbbhayani, I would like to take this on. Please assign this to me.

**Comment by arpitbbhayani** [comment]
@hash-f you already have another one on your plate :) will keep this one open for someone else to take up.

**Comment by hash-f** [comment]
Sure, sure. One is enough. Thank you! Someone else commented on that other issue before me. So I thought that one was going to him. :P

**Comment by ankkyprasad** [comment]
Hi @arpitbbhayani, I'd like to work on this issue. Can you please assign this to me?

**Comment by meetghodasara** [comment]
Hi @arpitbbhayani , I am excited to work on this issue. Can you please assigned it to me?

**Comment by AshwinKul28** [comment]
Hey @ankkyprasad go for it.

@meetghodasara can you please check other opened issues. Thanks for showing interest! 🥳
