### ISSUE TITLE
Add support for command `HMSET`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#651]
Add support for the `HMSET` command in DiceDB similar to the [`HMSET` command in Redis](https://redis.io/docs/latest/commands/command-list/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by raghavbabbar** [comment]
@arpitbbhayani please assign this to me

**Comment by arpitbbhayani** [comment]
@raghavbabbar Thanks for taking this up. assigned.

**Comment by karandixit10** [comment]
@arpitbbhayani Can I work on this issue if no ones working on it?

**Comment by raghavbabbar097** [comment]
Hey! @karandixit10 i am working on it

**Comment by anchalsinghrajput** [comment]
Hey @raghavbabbar, are you still working on this, if not can I take this up ?

**Comment by raghavbabbar** [comment]
https://github.com/DiceDB/dice/pull/960
