### ISSUE TITLE
Inconsistent `BITCOUNT`: BITCOUNT fuzzing without start/end

### ISSUE THREAD

**Issue by lucifercr07** [DiceDB/dice#663]
## Steps to reproduce

Run the commands mentioned in the test on Line 114 in the file https://github.com/AshwinKul28/dice-tests/blob/main/tcltests/unit/bitpos.tcl#L114.

## Expected output

The expected output when the above set of commands when run on Redis

```
Expected [r bitcount str 0 -1 bit]
```

## Observed output

The observed output when the above set of commands when run on DiceDB

```
2153 (context: type eval line 7 cmd {assert {[r bitcount str 0 -1 bit]
```

The steps to run the test cases are mentioned in the README of the [dice-tests repository](https://github.com/AshwinKul28/dice-tests).

## Expectations for resolution

This issue will be considered resolved when the following things are done:

1. Changes in the [`dice`](https://github.com/dicedb/dice) repository code to meet the expected behavior.
1. Successful run of the tcl test behavior.

You can find the tests under the `tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [Setup DiceDB locally](https://github.com/dicedb/dice)
- [Setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [Setup DiceDB CLI](https://github.com/dicedb/dice)

**Comment by Nijin-P-S** [comment]
Hi @lucifercr07 , can you assign this task to me?

**Comment by jainbhavya53** [comment]
Hi @lucifercr07 
Can I take this up ? Would love to work on it.
Thanks

**Comment by AshwinKul28** [comment]
@Nijin-P-S @jainbhavya53 Assigned other issues to both of you. Let's have a single issue on your plate at a time. Once that's completed you can pick other opened issues.

**Comment by VedWhat** [comment]
Hey @AshwinKul28 I'll take this up.lmk

**Comment by lucifercr07** [comment]
@VedWhat assigned, thanks for contributing.
