### ISSUE TITLE
Inconsistent `BITCOUNT`: BITCOUNT with start, end

### ISSUE THREAD

**Issue by lucifercr07** [DiceDB/dice#664]
## Steps to reproduce

Run the commands mentioned in the test on Line 68 in the file https://github.com/AshwinKul28/dice-tests/tree/main#L68.

## Expected output

The expected output when the above set of commands when run on Redis

```
Expected '4' to be equal to '26' (context: type eval line 9 cmd {assert_equal [r bitcount s 0 -1 bit] [count_bits $s]} proc ::test)
```

## Observed output

The observed output when the above set of commands when run on DiceDB

```
Expected '4' to be equal to '26' (context: type eval line 9 cmd {assert_equal [r bitcount s 0 -1 bit] [count_bits $s]} proc ::test)
```

The steps to run the test cases are mentioned in the README of the [dice-tests repository](https://github.com/AshwinKul28/dice-tests).

## Expectations for resolution

This issue will be considered resolved when the following things are done:

1. Changes in the [`dice`](https://github.com/dicedb/dice) repository code to meet the expected behavior.
1. Successful run of the tcl test behavior.

You can find the tests under the `tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [Setup DiceDB locally](https://github.com/dicedb/dice)
- [Setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [Setup DiceDB CLI](https://github.com/dicedb/dice)

**Comment by Nijin-P-S** [comment]
Hi @lucifercr07 , can you assign this task to me?

**Comment by jainbhavya53** [comment]
Hi @lucifercr07 
Can I take this up ? Would love to work on it.
Thanks

**Comment by AshwinKul28** [comment]
@Nijin-P-S @jainbhavya53 Assigned other issues to both of you. Let's have a single issue on your plate at a time. Once that's completed you can pick other opened issues.

**Comment by VedWhat** [comment]
@AshwinKul28 I'll take this up lmk

**Comment by clueless-skywatcher** [comment]
Hi @AshwinKul28 Can I pick this up?

**Comment by lucifercr07** [comment]
@clueless-skywatcher assigned, thanks for contributing.

**Comment by clueless-skywatcher** [comment]
Hi @AshwinKul28 I have been trying to solve this issue for the past few days but every time I run `./tcltest` I come across this issue. Please see log for details

OS: WSL2 (Ubuntu 22.04 LTS)
```
No directory path provided. Cloning repository...
Cloning into 'dice'...
remote: Enumerating objects: 4142, done.
remote: Counting objects: 100% (1788/1788), done.
remote: Compressing objects: 100% (552/552), done.
remote: Total 4142 (delta 1575), reused 1242 (delta 1236), pack-reused 2354 (from 1)
Receiving objects: 100% (4142/4142), 8.01 MiB | 994.00 KiB/s, done.
Resolving deltas: 100% (2768/2768), done.
Patch applied successfully.
'air' found, running 'air'...
Running tests...
Cleanup: may take some time... OK
Starting test server at port 21079
[ready]: 2114
Testing unit/auth
[1/6 done]: unit/auth (0 seconds)
Testing unit/bitpos
[exception]: Executing test client: couldn't open socket: connection refused.
couldn't open socket: connection refused
    while executing
"socket $server $port"
    (procedure "redis" line 7)
    invoked from within
"redis $::host $::port 0 $::tls"
    (procedure "run_external_server_test" line 5)
    invoked from within
"run_external_server_test $code $overrides"
    (procedure "start_server" line 61)
    invoked from within
"start_server {tags {"bitops"}} {
    test {BITCOUNT returns 0 against non existing key} {
        assert {[r bitcount no-key] == 0}
        assert {[r..."
    (file "tcltests/unit/bitpos.tcl" line 47)
    invoked from within
"source $path"
    (procedure "execute_test_file" line 4)
    invoked from within
"execute_test_file $data"
    (procedure "test_client_main" line 10)
    invoked from within
"test_client_main $::test_server_port "
Stopping the server...
Removing cloned directory 'dice'...
```

**Comment by clueless-skywatcher** [comment]
Hi @arpitbbhayani 

Thanks for reaching out. Unfortunately I haven’t been able to reproduce this issue as mentioned in the aforementioned comment.

**Comment by lucifercr07** [comment]
Closing, fixed as part of https://github.com/DiceDB/dice/pull/699
