### ISSUE TITLE
Inconsistent `BITPOS`: BITPOS bit=1 works with intervals

### ISSUE THREAD

**Issue by lucifercr07** [DiceDB/dice#670]
## Steps to reproduce

Run the commands mentioned in the test on Line 380 in the file https://github.com/AshwinKul28/dice-tests/blob/main/tcltests/unit/bitpos.tcl#L380.

## Expected output

The expected output when the above set of commands when run on Redis

```
Expected [r bitpos str 1 8 -1 bit]
```

## Observed output

The observed output when the above set of commands when run on DiceDB

```
8 (context: type eval line 10 cmd {assert {[r bitpos str 1 8 -1 bit]
```

The steps to run the test cases are mentioned in the README of the [dice-tests repository](https://github.com/AshwinKul28/dice-tests).

## Expectations for resolution

This issue will be considered resolved when the following things are done:

1. Changes in the [`dice`](https://github.com/dicedb/dice) repository code to meet the expected behavior.
1. Successful run of the tcl test behavior.

You can find the tests under the `tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [Setup DiceDB locally](https://github.com/dicedb/dice)
- [Setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [Setup DiceDB CLI](https://github.com/dicedb/dice)

**Comment by Nijin-P-S** [comment]
Hi @lucifercr07 , can you assign this task to me?

**Comment by karandixit10** [comment]
Hi @lucifercr07, can I take this up?

**Comment by jainbhavya53** [comment]
Hi @lucifercr07 
Can I take this up ? Would love to work on it.
Thanks

**Comment by AshwinKul28** [comment]
@Nijin-P-S Go for it. Thanks

@karandixit10 @jainbhavya53 Please check for other opened issues. Thanks for your interest. Means a lot!

**Comment by lucifercr07** [comment]
@karandixit10 assigned, thanks for picking this up.

**Comment by karandixit10** [comment]
Hi @lucifercr07 This issue has the same scenario as #669. Shall I work on this or is it being worked on by someone else?

**Comment by jainbhavya53** [comment]
PR: https://github.com/DiceDB/dice/pull/716

**Comment by jainbhavya53** [comment]
@lucifercr07 Can you please assign this issue to me and close it ?
Its fixed by https://github.com/DiceDB/dice/pull/716

**Comment by lucifercr07** [comment]
Merged as part of https://github.com/DiceDB/dice/pull/716
