### ISSUE TITLE
Inconsistent `EXPIRE`: EXPIRE with empty string as TTL should report an error

### ISSUE THREAD

**Issue by lucifercr07** [DiceDB/dice#671]
## Steps to reproduce

Run the commands mentioned in the test on Line 81 in the file https://github.com/AshwinKul28/dice-tests/blob/main/tcltests/unit/expire.tcl#L81.

## Expected output

The expected output when the above set of commands when run on Redis

```
'*not an integer*'
```

## Observed output

The observed output when the above set of commands when run on DiceDB

```
'ERR invalid expire time in 'expire' command'
```

The steps to run the test cases are mentioned in the README of the [dice-tests repository](https://github.com/AshwinKul28/dice-tests).

## Expectations for resolution

This issue will be considered resolved when the following things are done:

1. Changes in the [`dice`](https://github.com/dicedb/dice) repository code to meet the expected behavior.
1. Successful run of the tcl test behavior.

You can find the tests under the `tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [Setup DiceDB locally](https://github.com/dicedb/dice)
- [Setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [Setup DiceDB CLI](https://github.com/dicedb/dice)

**Comment by Abh-ay** [comment]
@lucifercr07 
can i take this up?

**Comment by AshwinKul28** [comment]
@Abh-ay Thanks for picking this up. Assigned!

**Comment by Abh-ay** [comment]
Hi @AshwinKul28 @lucifercr07 
Just verify this command in redis and it accept -ve value also refer below ss
![image](https://github.com/user-attachments/assets/e9cb799e-9f21-4190-ba17-74381e016fd2)
Should we handle this or keep as it is?
