### ISSUE TITLE
Broken behaviour of`DumpAllAOF` in MacOS

### ISSUE THREAD

**Issue by vinitparekh17** [DiceDB/dice#683]
## Steps to reproduce

`go run main.go`

## Expected output

It should log it once:
```sh
AOF file rewrite complete
```

## Observed output

![Screenshot_20240922_034337](https://github.com/user-attachments/assets/c8c3e3f2-49bf-4056-87cb-5e2ee4b83773)

## Expectations for resolution

This issue will be considered resolved when the following things are done

1. changes in the [`dice`](https://github.com/dicedb/dice) code to meet the expected behavior
2. addition of relevant test case to ensure we catch the regression

You can find the tests under the `tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [setup DiceDB locally](https://github.com/dicedb/dice)
- [setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [setup DiceDB CLI](https://github.com/dicedb/dice)

**Comment by KaviiSuri** [comment]
@vinitparekh17 Can i pick this one up?

**Comment by vinitparekh17** [comment]
@KaviiSuri Sure, thanks for taking this up.

cc: @lucifercr07 assign him

**Comment by KaviiSuri** [comment]
@vinitparekh17 , i get this issue on my system when running `BGREWRITEAOF` 
<img width="981" alt="image" src="https://github.com/user-attachments/assets/e3b5edc5-c5b5-49a3-a4e3-ffdeae912ff9">

are you aware of the reasons for this?

**Comment by vinitparekh17** [comment]
@KaviiSuri unfortunately I am not aware of this?

**Comment by KaviiSuri** [comment]
Okay, I'll try to figure it out. Can you confirm what os and arch are you on? Would help in debugging

**Comment by vinitparekh17** [comment]
> Okay, I'll try to figure it out. Can you confirm what os and arch are you on? Would help in debugging

Arch linux, amd64

**Comment by KaviiSuri** [comment]
on macos, i can consistently reproduce that the "child" process flow never gets triggered in the EvalBGREWRITEAOF function


<img width="916" alt="image" src="https://github.com/user-attachments/assets/212f4dba-22e5-48f1-88ba-16749af4e823">


<img width="686" alt="image" src="https://github.com/user-attachments/assets/f31d40f9-6afd-488a-a434-1c823ae1fba5">

no logs from child process or any logs with pid as 0.

will be investigating why this happens later

**Comment by KaviiSuri** [comment]
after logging PPID, it is confirmed that SYS_FORK is returning the wrong value, since the ppid of one of the logs matches the pid of the main proccess we run the server on

<img width="664" alt="image" src="https://github.com/user-attachments/assets/3a20701c-77bc-4d54-8d11-325be482b6e2">

**Comment by KaviiSuri** [comment]
<img width="713" alt="image" src="https://github.com/user-attachments/assets/de2e1a7a-a1b8-4920-8a77-406ff6ee9c21">
the issue on macos is solved!

The solution is to just record PID before fork, and then `isChild := syscall.GetPPID() == originalPid`

will try to replicate on linux to and create a PR for both

**Comment by vinitparekh17** [comment]
> on further discusions on discord, the original issue seems expected (multiple workers writing their shards to AOF will log multiple times).
> 
> while the issue that i found on MacOS in the investigation still is a real issue, it's fixed by #704

Thanks for making such an effort 👍🏻

**Comment by vinitparekh17** [comment]
Closing as it’s resolved.
