### ISSUE TITLE
Tests for command `SET`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#69]
Currently, there are almost no unit tests for the `SET` command. We need a comprehensive test suite for this command that also checks the correctness and completeness.

1. covers the correctness of single command
2. covers the correctness when multiple commands are fired
3. no commands are dropped abruptly
4. ensure we check for small, large, and massive inputs (if applicable)

**Comment by sahil1913** [comment]
@arpitbbhayani for `SET` command the tests are in `set_test.go`.
Are more tests required for it?

**Comment by arpitbbhayani** [comment]
Yes. Correctness is yet to be tested. Long input, different data types, and bulk commands.

**Comment by sahil1913** [comment]
Okay cool. I can work on this issue. Will add more tests in the same file.
Please assign the issue.

**Comment by nihcas700** [comment]
@arpitbbhayani I have made some code changes for this task, would be great to have the permissions to open a PR.

**Comment by lucifercr07** [comment]
@nihcas700 you can fork the repo and raise a PR, no other permissions are required I believe.

**Comment by nihcas700** [comment]
Thanks @lucifercr07. Opened the [MR](https://github.com/DiceDB/dice/pull/399)

**Comment by psrvere** [comment]
@JyotinderSingh - I can pick this up, if it's available.

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh - I can pick this up, if it's available.

I believe we already have comprehensive tests for the SET command now. Could you check if there are any cases we are missing?

**Comment by psrvere** [comment]
@JyotinderSingh - Reviewed all unit and integration tests for SET command. Found a few gaps and raised PR for the same - #1118
