### ISSUE TITLE
Tests for command `PING`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#70]
Currently, there are almost no unit tests for the `PING` command. We need a comprehensive test suite for this command that also checks the correctness and completeness.

1. covers the correctness of single command
2. covers the correctness when multiple commands are fired
3. no commands are dropped abruptly
4. ensure we check for small, large, and massive inputs (if applicable)

**Comment by HarinRamesh** [comment]
Hi, I will take up this issue.

**Comment by HarinRamesh** [comment]
Hi, I am getting a connection refused error while running test case, seems like PING commands are properly working.

<img width="847" alt="Screenshot 2022-11-06 at 7 45 47 PM" src="https://user-images.githubusercontent.com/32133974/200175975-fd037cec-b526-4798-aa79-950d273f3492.png">

Below is my code for the test.
@arpitbbhayani @rohanverma94 



	var wg sync.WaitGroup
	go runTestServer(&wg)

	var b []byte
	var buf = bytes.NewBuffer(b)
	conn := getLocalConnection()
	buf.WriteByte('a')
	cmd := fmt.Sprintf("PING")
	v := fireCommand(conn, cmd)
	if v != "PONG" {
		t.Fail()
	}
	fmt.Println("====================================")
	fmt.Println(v)
	fmt.Println("====================================")


	cmd = fmt.Sprintf("PING HELLO!")
	v = fireCommand(conn, cmd)
	if v != "HELLO!" {
		t.Fail()
	}
	fmt.Println("====================================")
	fmt.Println(v)
	fmt.Println("====================================")
	fireCommand(conn, "ABORT")
	wg.Wait()

**Comment by rohanverma94** [comment]
Can you share the complete code ? Example seems unclear

**Comment by rohanverma94** [comment]
@HarinRamesh 
Try something like this
```go
	conn := getLocalConnection()
	defer func(conn net.Conn) {
		err := conn.Close()
		if err != nil {

		}
	}(conn)
```
it will allow the client connection to do a warmup before accepting actual bytes.
