### ISSUE TITLE
Implement Global Rate Limiter using DiceDB for Playground Backend

### ISSUE THREAD

**Issue by lucifercr07** [DiceDB/dice#729]
## Description

DiceDB Playground is an interactive platform that allows users to experiment with DiceDB commands in a live environment, similar to the Go Playground. Users will be able to submit and execute commands directly through a web interface. The initial implementation will focus on enabling users to search for and trigger commands.  
For more details about DiceDB playground you can check [here](https://docs.google.com/document/d/1M5XfuOwQsRcl6g_VBr-FCLy71cnqCp7ulgyt6MsfESU/edit?usp=sharing). 

We need to implement a global rate limiter that restricts the total number of requests served across all users to 1000 commands/minute. The rate limiter will use DiceDB for tracking and managing the request counts. It should count how many requests are made globally and block further requests if the limit is exceeded within the current minute window.

The rate limiter should not track individual users or IP addresses but work as a global safeguard for the entire server.

**Note:** Implementation will be part of DiceDB playground backend [repo](https://github.com/DiceDB/playground-mono).

## Details
- A global rate limiter is implemented using DiceDB to allow up to 1000 command requests/minute.
- DiceDB commands such as `GET`, `INCR`, and `EXPIRE` should be used to track and manage the request count for the current minute window.
- Requests exceeding the limit should be blocked, and an appropriate `429 Too Many Requests` response should be returned.
- The limit count should automatically reset at the start of each new minute.
- The rate limiter should apply only to `/command` endpoint, excluding `/search`.
- Ensure expiry of key tracking request count properly.

## Tasks
1. Create a brief doc around how the flow and implementation would be done.
2. Implement the logic in the backend service.
3. Validate under load to ensure it correctly blocks requests after 1000 requests/minute.

**Comment by ayushsatyam146** [comment]
I would like to take this up @lucifercr07

**Comment by RishabhC-137** [comment]
Can i take this up? @lucifercr07

**Comment by lucifercr07** [comment]
@RishabhC-137 assigned, thanks for contributing.

**Comment by lucifercr07** [comment]
@RishabhC-137 let me know if any blockers for you. We've initial structure in place at DiceDB playground backend [repo](https://github.com/DiceDB/playground-mono) now, you should be unblocked.

**Comment by lucifercr07** [comment]
Merged as part of https://github.com/DiceDB/playground-mono/pull/3
