### ISSUE TITLE
Tests for command `DEL`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#73]
Currently, there are almost no unit tests for the `DEL` command. We need a comprehensive test suite for this command that also checks the correctness and completeness.

1. covers the correctness of single command
2. covers the correctness when multiple commands are fired
3. no commands are dropped abruptly
4. ensure we check for small, large, and massive inputs (if applicable)

**Comment by rawris** [comment]
I can pick this up @arpitbbhayani
