### ISSUE TITLE
Fix: Report Command Bug template points to wrong test folder

### ISSUE THREAD

**Issue by apoorvyadav1111** [DiceDB/dice#747]
Hi team,

The current template for creating issues via `.github/ISSUE_TEMPLATE/report_command_bug.md` have incorrect folder name for the tests folder.

```You can find the tests under the `tests` directory of the [`dice`](https://github.com/dicedb/dice) repository```
Should be 
```You can find the tests under the `integration_tests` directory of the [`dice`](https://github.com/dicedb/dice) repository```
since we have migrate from the tests folder.

Thanks
Apoorv

**Comment by vinayak-gaikwad** [comment]
hey, i want to fix this, can you assigned me this?
