### ISSUE TITLE
Tests for command `INCR`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#75]
Currently, there are almost no unit tests for the `INCR` command. We need a comprehensive test suite for this command that also checks the correctness and completeness.

1. covers the correctness of single command
2. covers the correctness when multiple commands are fired
3. no commands are dropped abruptly
4. ensure we check for small, large, and massive inputs (if applicable)

**Comment by FuncGuy** [comment]
@arpitbbhayani  I would like to contribute for this feature

**Comment by Rits1272** [comment]
@arpitbbhayani can we close this issue, seems like test cases for this are already added here: https://github.com/DiceDB/dice/blob/master/tests/incr_test.go

**Comment by AshwinKul28** [comment]
Thanks @Rits1272 , Closing this.
