### ISSUE TITLE
Enforce value to be stored / returned as `json.marshal`  in `set`  cmd via Http protocol 

### ISSUE THREAD

**Issue by vinitparekh17** [DiceDB/dice#750]
## Steps to reproduce

```sh
curl --location 'http://localhost:8082/set' \
--header 'Content-Type: application/json' \
--header 'Cache-Control: no-cache' \
--data '{
    "key": "foo",
    "value": {
        "foo": {
            "bar": "fooBar"
        }
    }
}'


curl --location 'http://localhost:8082/get' \
--header 'Content-Type: application/json' \
--header 'Cache-Control: no-cache' \
--data '{
    "key": "foo"
}'
```

## Expected output

```
"{"foo":{"bar":"fooBar"}}"
```

## Observed output

```
"map[foo:map[bar:fooBar]]"
```
## Suggestion
Please ensure that the value is properly serialized using json.Marshal before being sent as a response in the HTTP protocol.

## Another Solution (Not Recommended, but Supported by Redis)
> Redis does allow storing JSON-like values using the SET command. If clients attempt to set a key with a JSON object directly, they will encounter an error due to invalid arguments.
>
> To store JSON values, clients must manually stringify the value before passing it to the SET command.
>
> If a client provides a JSON object without stringifying it, the server should return an error indicating invalid arguments. It's generally advisable to use a JSON.SET for handling JSON data.

- this should be expected from Dice via HTTP protocol

## Expectations for resolution

This issue will be considered resolved when the following things are done

1. changes in the [`dice`](https://github.com/dicedb/dice) code to meet the expected behavior
2. addition of relevant test case to ensure we catch the regression

You can find the tests under the `tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [setup DiceDB locally](https://github.com/dicedb/dice)
- [setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [setup DiceDB CLI](https://github.com/dicedb/dice)

**Comment by vinitparekh17** [comment]
assign me

**Comment by rishavvajpayee** [comment]
can i take this up ?

**Comment by TheMonkDev** [comment]
Hey, I am fairly new to this project and I want to take this opportunity to get into contributing to DiceDB. Can I take up this task and return with a PR?

**Comment by lovish2525** [comment]
In expected output we need a json response or a json string?
{
    "foo": {
        "bar": 1
    }
} 

or 

"{"foo":{"bar":"fooBar"}}"

**Comment by vinitparekh17** [comment]
> In expected response we need a json response or a json string?
> 
> ```
>  {
>      "foo": {
>          "bar": 1
>      }
>  } 
>  
> ```
> 
> or
> 
> "{"foo":{"bar":"fooBar"}}"

strigified response 2nd one

**Comment by lovish2525** [comment]
@vinitparekh17  Is it fine if the stringified version has escape characters in response?
eg - "{\"foo\":{\"bar\":1}}"

**Comment by lovish2525** [comment]
Created a PR here - https://github.com/DiceDB/dice/pull/757/files

**Comment by vinitparekh17** [comment]
cc: @lucifercr07
