### ISSUE TITLE
Lack of ARM64 support?

### ISSUE THREAD

**Issue by pog5** [DiceDB/dice#762]
There is no docker image for arm64, pulling it on an arm64 machine just runs the amd64 binary, causing it to fail due to an exec format error.

```js
go version go1.23.1 linux/arm64
AlmaLinux 9.4 hexcontainer.aarch64 #1 SMP PREEMPT_DYNAMIC Tue Nov 7 20:09:26 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

Cloning the current repo tree and running DiceDB via `go run main.go` gives me the following output:
```go
# github.com/dicedb/dice/internal/eval
internal/eval/eval_linux_arm64.go:28:5: undefined: config
internal/eval/eval_linux_arm64.go:29:3: nil is not used
```

Does this mean that DiceDB currently doesn't support arm64? If yes, will it support arm64 in the future? :)

**Comment by JyotinderSingh** [comment]
Looks like there are bugs in the linux_arm64 file. We will need to fix it. A lot of the maintainers currently do not use linux arm64 machines so it is a little hard for us to actively maintain it. Would appreciate any fixes!

**Comment by jayantpranjal0** [comment]
Hii, I would like to work on this. Can this be assgined to me?
