### ISSUE TITLE
Inconsistent `{DECR}`: Error message for out-of-range OR non-number values differs from Redis error message

### ISSUE THREAD

**Issue by mghildiy** [DiceDB/dice#763]
## Steps to reproduce

SET mykey "234293482390480948029348230948"
DECR mykey
SET mykey "Hello"
DECR mykey

## Expected output

The expected output when the above set of commands when run on Redis

```
(error) value is not an integer or out of range
```

## Observed output

The observed output when the above set of commands when run on DiceDB

```
(error) ERROR WRONGTYPE Operation against a key holding the wrong kind of value
```

The steps to run the test cases are mentioned in the README of the [dice-tests repository](https://github.com/AshwinKul28/dice-tests).

## Expectations for resolution

This issue will be considered resolved when the following things are done

1. changes in the [`dice`](https://github.com/dicedb/dice) code to meet the expected behavior
2. Successful run of the tcl test behavior

You can find the tests under the `tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [setup DiceDB locally](https://github.com/dicedb/dice)
- [setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [setup DiceDB CLI](https://github.com/dicedb/dice)

**Comment by mghildiy** [comment]
This issue has been raised based on findings for [issue](https://github.com/DiceDB/docs/issues/111).

**Comment by ashutoshdhande** [comment]
@mghildiy , are your expected and observed cases referring to the same scenario? I ran the same scenario as you, but encountered the same error for both (which is expected).
![image](https://github.com/user-attachments/assets/4702071a-996b-4977-9b76-286f687a0cd1)

**Comment by mghildiy** [comment]
> @mghildiy , are your expected and observed cases referring to the same scenario? I ran the same scenario as you, but encountered the same error for both (which is expected). ![image](https://private-user-images.githubusercontent.com/50861363/371751340-4702071a-996b-4977-9b76-286f687a0cd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MjExNTUsIm5iZiI6MTcyNzUyMDg1NSwicGF0aCI6Ii81MDg2MTM2My8zNzE3NTEzNDAtNDcwMjA3MWEtOTk2Yi00OTc3LTliNzYtMjg2ZjY4N2EwY2QxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDEwNTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MmI5ZmY5N2Y5YWI3NjE4NmM3Mjg0ZjVlYmQ1MjRmOTRlNmE2ZGYwMThlMjFlOGY0NTExODE0MjBjOTdhZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.akc1ktxi2CihP8DlsLh036QchiFoY0pQOHJ0moMjgvg)

Error message needs to be same as redis.

**Comment by adityaa-p** [comment]
@mghildiy The current error message is the same as redis only. Can you please recheck?

**Comment by mghildiy** [comment]
For Redis:

<img width="434" alt="Screenshot 2024-09-29 at 7 42 31 AM" src="https://github.com/user-attachments/assets/bb2edb5a-b480-4b12-958d-92fadd8f8b60">

For dice:

<img width="574" alt="Screenshot 2024-09-29 at 7 41 02 AM" src="https://github.com/user-attachments/assets/8932137f-7cab-49be-83fc-aade3833c6b5">

I am running latest docker versions for both.

**Comment by apoorvyadav1111** [comment]
Hi @mghildiy , I tried running latest dice db code using go and I am getting following: 
![image](https://github.com/user-attachments/assets/2c03120a-08fb-4da8-bf42-5080ae1a5c90)

**Comment by mghildiy** [comment]
Master branch exhibits same bheaviour as redis while my findings were based on latest dokcer image.
I am closing this ticket.
