### ISSUE TITLE
Audit and make documentation for command `JSON.ARRLEN` consistent

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#782]
The documentation of the command `[JSON.ARRLEN](https://dicedb.io/commands/jsonarrlen/)` present in [the docs](https://github.com/DiceDB/dice/tree/master/docs/src/content/docs/commands) could have become stale. We need your help to ensure that the documentation is complete, correct, and consistent.  Completing this issue will give you much-needed exposure to how the command is implemented and the different parameters it accepts. Hence, this is a great way to build a good understanding of the project and its functionality. While still making a significant contribution. Here's what you need to do:

1. Go through the [documentation of the command](https://dicedb.io/commands/jsonarrlen/) and run all the examples, making sure they all work as expected
2. If the same command is present in Redis, then the expected output of the DiceDB command is the same as the Redis output
3. If the command is not in Redis, then as per your judgment, [raise an issue with this template](https://github.com/DiceDB/dice/issues/new?assignees=&labels=&projects=&template=report_command_bug.md&title=Inconsistent+%60%7BCMD%7D%60%3A+%3CDescribe+the+error+in+one+concise+line%3E) or fix the documentation and raise a pull request.
4. The documentation should contain the following sections in the following order
 * short and concise introduction paragraph about the command covering what it does
 * Syntax
 * Parameters: List all the parameters the command accepts, and ignore the section if there are no parameters
 * Return values: List all possible return values and under what condition
 * Behaviour: Describe the behavior of the command, what it does, how it does it, some internal specifics if any
 * Errors: List all possible errors the command can throw and under what condition
 * Examples: List all possible examples of the command and the expected output. Assume CLI implementation

Note: The title of the sections should be the exact strings mentioned above, like "Examples", "Return values", etc.
Note: The description of the command in Frontmatter of the command.md file is the first paragraph (introduction) of the command.

Go through the [DiceDB/dice](https://github.com/dicedb/dice) repository and explore the command implementation
 * to understand all possible return values
 * to understand all possible error values and conditions
 * to understand different parameters the command accepts

Please use the documentation of the [SET](https://dicedb.io/commands/set/) command as the reference point and structure the
documentation of this command in a very similar way, including the following points
 * if you see any "Conclusion" section, remove it
 * the headers (h1, h2, h3) should be appropriately used
 * the CLI prompt should be `127.0.0.1:7379>` and not anything else
 * Use markdown tables for parameters and return values (ref SET command documentation)
 * wrap any command or paramter in backticks (`) to highlight them
 * the section header should be capitalize as used in the SET command documentation

If you find any inconsistencies, please fix the documentation and raise the PR.
The core idea of this exercise is to ensure that the documentation is consistent, correct, and complete.

Make sure you comment on the other issues you created (if any) as a comment on this issue and also any PR (if any) that you created.
Thank you for picking this up and contributing to the DiceDB. It means a ton.

**Comment by surya0180** [comment]
@arpitbbhayani @JyotinderSingh. I would like to document this command as well. Please assign this to me

**Comment by lucifercr07** [comment]
@surya0180 assigned, thanks for contributing.

**Comment by surya0180** [comment]
Hi @lucifercr07 @JyotinderSingh @apoorvyadav1111. I was going through `JSON.ARRLEN` command and compared the outputs in both `redis-cli` and `dice-cli`. Almost all usecases are not giving the expected outputs. I am sharing some screenshots for your reference.

Total 4 mismatches found. I am not clear which are intended and which are issues. Do let me know what can be done here. 

Thanks !

Here are the keys with 2 different JSONs

* JSON with object in root
![image](https://github.com/user-attachments/assets/8923104b-dd7f-4bc8-900b-b2d4a7daed80)

* JSON with array in root
![image](https://github.com/user-attachments/assets/cc88a128-ad18-4368-a543-0b7f92cf4529)



## Mismatch 1
* Redis
![image](https://github.com/user-attachments/assets/7d29339f-8ded-45d7-9be4-a96f012bf66a)
* Dice
![image](https://github.com/user-attachments/assets/bbb3c9a2-0fd6-4eee-823b-3c7bfbebbaa7)

## Mismatch 2
* Redis
![image](https://github.com/user-attachments/assets/2fb8b0a8-77af-4e2b-b9ea-554dc01ec244)
* Dice
![image](https://github.com/user-attachments/assets/326e680d-53b4-42d7-9c91-5c5f27c15ccd)

## Mismatch 3
* Redis
![image](https://github.com/user-attachments/assets/dd0f8796-91f6-4d2f-97a3-6761302bd6bb)
* Dice
![image](https://github.com/user-attachments/assets/032b7dc4-25ed-4544-9faa-691f439a493e)

## Mismatch 4
* Redis
![image](https://github.com/user-attachments/assets/ffbd3ed6-7b94-444a-a630-bcd412c1cc43)
* Dice
![image](https://github.com/user-attachments/assets/95753d19-83dc-4718-a62f-207a40770269)

**Comment by surya0180** [comment]
> Hi @lucifercr07 @JyotinderSingh @apoorvyadav1111. I was going through `JSON.ARRLEN` command and compared the outputs in both `redis-cli` and `dice-cli`. Almost all usecases are not giving the expected outputs. I am sharing some screenshots for your reference.
> 
> Total 4 mismatches found. I am not clear which are intended and which are issues. Do let me know what can be done here.
> 
> Thanks !
> 
> Here are the keys with 2 different JSONs
> 
> * JSON with object in root
>   ![image](https://private-user-images.githubusercontent.com/56592197/373853468-8923104b-dd7f-4bc8-900b-b2d4a7daed80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxODQ3NDAsIm5iZiI6MTcyODE4NDQ0MCwicGF0aCI6Ii81NjU5MjE5Ny8zNzM4NTM0NjgtODkyMzEwNGItZGQ3Zi00YmM4LTkwMGItYjJkNGE3ZGFlZDgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDAzMTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZTU1YjA1ZWM3NjgwNzRhMWZhMWJmZDI3MzYwNDJjY2RiMjJmMzQ2YTRlNWExMjY3YzMyNzFlYmNiOTQ4NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r6AwPhmlS3ha-444IdegTJ_t4tVQZm_zjKY5s7DRNFw)
> * JSON with array in root
>   ![image](https://private-user-images.githubusercontent.com/56592197/373853486-cc88a128-ad18-4368-a543-0b7f92cf4529.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxODQ3NDAsIm5iZiI6MTcyODE4NDQ0MCwicGF0aCI6Ii81NjU5MjE5Ny8zNzM4NTM0ODYtY2M4OGExMjgtYWQxOC00MzY4LWE1NDMtMGI3ZjkyY2Y0NTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDAzMTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NzY4ODExNmZjNDhmMTJjZmUwZDVmYmY4MWY4NGFmMzFlYTU1NjMwZjJhZmVjMzMzMTM1MjFjY2VhMzZhMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RNSQ6NuPhHOlL0yEBCp494M_U0FgX87VEdGijNQam8M)
> 
> ## Mismatch 1
> * Redis
>   ![image](https://private-user-images.githubusercontent.com/56592197/373852803-7d29339f-8ded-45d7-9be4-a96f012bf66a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxODQ3NDAsIm5iZiI6MTcyODE4NDQ0MCwicGF0aCI6Ii81NjU5MjE5Ny8zNzM4NTI4MDMtN2QyOTMzOWYtOGRlZC00NWQ3LTliZTQtYTk2ZjAxMmJmNjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDAzMTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkYjRhZTU1ZjRlYjAwNzBjMDJlZGUyNTE0N2JiMjNkOTg0NTkyMzM2ZTVlYmIzMzJkZDBjMTQ4YTk5YmE1NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t1A6M8taKh9Zw2H9HCtWmfPyYvHYM3dS0iCFc5LNyHQ)
> * Dice
>   ![image](https://private-user-images.githubusercontent.com/56592197/373852821-bbb3c9a2-0fd6-4eee-823b-3c7bfbebbaa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxODQ3NDAsIm5iZiI6MTcyODE4NDQ0MCwicGF0aCI6Ii81NjU5MjE5Ny8zNzM4NTI4MjEtYmJiM2M5YTItMGZkNi00ZWVlLTgyM2ItM2M3YmZiZWJiYWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDAzMTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhYmI2MDEyZTk0ZmQwZWVkNmU0YTE2NmNlOTAzNjI0NDZhZmVlMGFkNTgyMzRiMGNhODVkZGU1MTZkYTM4MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6KfoG7q_nAIJxKbG_Ez_m57StFJEbjTDm-K1TDz2cYo)
> 
> ## Mismatch 2
> * Redis
>   ![image](https://private-user-images.githubusercontent.com/56592197/373852883-2fb8b0a8-77af-4e2b-b9ea-554dc01ec244.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxODQ3NDAsIm5iZiI6MTcyODE4NDQ0MCwicGF0aCI6Ii81NjU5MjE5Ny8zNzM4NTI4ODMtMmZiOGIwYTgtNzdhZi00ZTJiLWI5ZWEtNTU0ZGMwMWVjMjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDAzMTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkODYzN2ZmZGUxMGI5NzBhMjhjZjdiODg0OGYxZmY1NzY3NjVmNWFkZjAxZjJmZmZlNDA5MTJkM2ZmYTExNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NY2RpeBjpVop24xlieU8Bodoz85a_ZDf2eG2qY60i8E)
> * Dice
>   ![image](https://private-user-images.githubusercontent.com/56592197/373852891-326e680d-53b4-42d7-9c91-5c5f27c15ccd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxODQ3NDAsIm5iZiI6MTcyODE4NDQ0MCwicGF0aCI6Ii81NjU5MjE5Ny8zNzM4NTI4OTEtMzI2ZTY4MGQtNTNiNC00MmQ3LTljOTEtNWM1ZjI3YzE1Y2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDAzMTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjYTgwNWJjZmI4ZjkwNGM5ZjUyZTM4NjFkYTE1YzBiMDMwMTNmYWQwY2JhYzNmOGRlMjM5MWVlOTVjMTM3OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vS2JptK7Fvieo4NeMlgEOyNB6GME_whMkRvvqYrG1Yk)
> 
> ## Mismatch 3
> * Redis
>   ![image](https://private-user-images.githubusercontent.com/56592197/373852950-dd0f8796-91f6-4d2f-97a3-6761302bd6bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxODQ3NDAsIm5iZiI6MTcyODE4NDQ0MCwicGF0aCI6Ii81NjU5MjE5Ny8zNzM4NTI5NTAtZGQwZjg3OTYtOTFmNi00ZDJmLTk3YTMtNjc2MTMwMmJkNmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDAzMTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MDFmM2YyYjg0OTBmYmNkOWRmYzcxNWRkZDYwNjM5NjlkNjg4YzY4MjY1NWJhNTVmOTI3ODlhMjYxMTc1MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9nkp98nOMMFON58MdWTxpAajlasaQyyUWB5UOmJ0wKY)
> * Dice
>   ![image](https://private-user-images.githubusercontent.com/56592197/373852957-032b7dc4-25ed-4544-9faa-691f439a493e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxODQ3NDAsIm5iZiI6MTcyODE4NDQ0MCwicGF0aCI6Ii81NjU5MjE5Ny8zNzM4NTI5NTctMDMyYjdkYzQtMjVlZC00NTQ0LTlmYWEtNjkxZjQzOWE0OTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDAzMTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZDg3YjdjMWYyMDZkZWM4YzU5MTliOTAyOTY4MDJhMDkyYThhZTI4ZWY2MDA0YjA3NzBiYzI3YWU0OWI4MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1E8zbA56Udogawbthm4elMZaw-hfPATXlzzv7cA-s98)
> 
> ## Mismatch 4
> * Redis
>   ![image](https://private-user-images.githubusercontent.com/56592197/373853066-ffbd3ed6-7b94-444a-a630-bcd412c1cc43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxODQ3NDAsIm5iZiI6MTcyODE4NDQ0MCwicGF0aCI6Ii81NjU5MjE5Ny8zNzM4NTMwNjYtZmZiZDNlZDYtN2I5NC00NDRhLWE2MzAtYmNkNDEyYzFjYzQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDAzMTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZDU3OTgyYTY5NzQ1NjQwNzc0NTI0NThlNWZiNzAzNzY1MTE3NjhhMmQyZWMwOTgwZDQ2MTNiOTFkNmYzOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-X84eIu0C9XUlr2_jCPqRUPNT7TlF6LylcS-XQwujSY)
> * Dice
>   ![image](https://private-user-images.githubusercontent.com/56592197/373853073-95753d19-83dc-4718-a62f-207a40770269.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxODQ3NDAsIm5iZiI6MTcyODE4NDQ0MCwicGF0aCI6Ii81NjU5MjE5Ny8zNzM4NTMwNzMtOTU3NTNkMTktODNkYy00NzE4LWE2MmYtMjA3YTQwNzcwMjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDAzMTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ZDAzYmZiMjE4ZWE2MTNkY2QyYjM3ZDZiMGVhNDY2MzhiY2QyZWM2Njg0ZjI5MWUyZTAzYjA5MGIxNGZlNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.avapM55VTZ4KxmXqqTBcYmxMYmLvXPEDVpyUVTFc_LI)

UPDATE: I have opened issue #974 for this comment. I will be working on this.

**Comment by surya0180** [comment]
Fixed inconsistencies ( Excluding complex JSONPaths ). Will start documenting JSON.ARRLEN
