### ISSUE TITLE
Tests for comamnd `DISCARD`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#79]
Currently, there are almost no unit tests for the `DISCARD` command. We need a comprehensive test suite for this command that also checks the correctness and completeness.

1. covers the correctness of single command
2. covers the correctness when multiple commands are fired
3. no commands are dropped abruptly
4. ensure we check for small, large, and massive inputs (if applicable)

**Comment by arpitbbhayani** [comment]
![Screenshot 2024-02-24 011525](https://github.com/DiceDB/dice/assets/4745789/4b593803-f8f2-4e24-986d-75fa1c6705ce)

**Comment by gauravrp** [comment]
Hey Arpit
Would like to pick this up. Do you suggest this should be a good first issue?

**Comment by Rits1272** [comment]
@arpitbbhayani would like to take this up

**Comment by Rits1272** [comment]
@JyotinderSingh can we close this issue as well?
