### ISSUE TITLE
Audit and make documentation for command `PFMERGE` consistent

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#798]
The documentation of the command `[PFMERGE](https://dicedb.io/commands/pfmerge/)` present in [the docs](https://github.com/DiceDB/dice/tree/master/docs/src/content/docs/commands) could have become stale. We need your help to ensure that the documentation is complete, correct, and consistent.  Completing this issue will give you much-needed exposure to how the command is implemented and the different parameters it accepts. Hence, this is a great way to build a good understanding of the project and its functionality. While still making a significant contribution. Here's what you need to do:

1. Go through the [documentation of the command](https://dicedb.io/commands/pfmerge/) and run all the examples, making sure they all work as expected
2. If the same command is present in Redis, then the expected output of the DiceDB command is the same as the Redis output
3. If the command is not in Redis, then as per your judgment, [raise an issue with this template](https://github.com/DiceDB/dice/issues/new?assignees=&labels=&projects=&template=report_command_bug.md&title=Inconsistent+%60%7BCMD%7D%60%3A+%3CDescribe+the+error+in+one+concise+line%3E) or fix the documentation and raise a pull request.
4. The documentation should contain the following sections in the following order
 * short and concise introduction paragraph about the command covering what it does
 * Syntax
 * Parameters: List all the parameters the command accepts, and ignore the section if there are no parameters
 * Return values: List all possible return values and under what condition
 * Behaviour: Describe the behavior of the command, what it does, how it does it, some internal specifics if any
 * Errors: List all possible errors the command can throw and under what condition
 * Examples: List all possible examples of the command and the expected output. Assume CLI implementation

Note: The title of the sections should be the exact strings mentioned above, like "Examples", "Return values", etc.
Note: The description of the command in Frontmatter of the command.md file is the first paragraph (introduction) of the command.

Go through the [DiceDB/dice](https://github.com/dicedb/dice) repository and explore the command implementation
 * to understand all possible return values
 * to understand all possible error values and conditions
 * to understand different parameters the command accepts

Please use the documentation of the [SET](https://dicedb.io/commands/set/) command as the reference point and structure the
documentation of this command in a very similar way, including the following points
 * if you see any "Conclusion" section, remove it
 * the headers (h1, h2, h3) should be appropriately used
 * the CLI prompt should be `127.0.0.1:7379>` and not anything else
 * Use markdown tables for parameters and return values (ref SET command documentation)
 * wrap any command or paramter in backticks (`) to highlight them
 * the section header should be capitalize as used in the SET command documentation

If you find any inconsistencies, please fix the documentation and raise the PR.
The core idea of this exercise is to ensure that the documentation is consistent, correct, and complete.

Make sure you comment on the other issues you created (if any) as a comment on this issue and also any PR (if any) that you created.
Thank you for picking this up and contributing to the DiceDB. It means a ton.

**Comment by Kannav02** [comment]
Hey @arpitbbhayani 

Just to clarify some points before moving ahead

- Review existing documents
- Verify examples 
- Compare with Redis
- Explore the code
- Update the documentation

if these are all the requirements, I would love to contribute to this issue, thank you!

**Comment by arpitbbhayani** [comment]
@Kannav02 go for it. assigned. thanks for picking this up.

**Comment by Kannav02** [comment]
I will start working on this soon 
Just to be on the same page, does this issue have a deadline?
thank you!

**Comment by Kannav02** [comment]
Hey , Just a quick update on this

I am running through the demos for each and clicking snapshots for the command in both `Redis` and `DiceDB`, I will soon open a PR for the same, thanks

**Comment by Kannav02** [comment]
Hey @arpitbbhayani 

I was going through the instructions and I found a really interesting thing


so when I do the following command

```
PFMERGE dest_HLL user:1

```

where user:1 is not a HLL and is not even defined, so the key is essentially pointing to a (nil), it still creates the new HLL when I use the PFMERGE command

A snapshot for the same can be found here 

<img width="552" alt="Screenshot 2024-10-05 at 11 02 55 PM" src="https://github.com/user-attachments/assets/b7feaf4c-f342-48a6-86d8-231be2b96e4d">

I ran the same command in Redis as well, it also showed the same behavior

<img width="552" alt="Screenshot 2024-10-05 at 11 04 47 PM" src="https://github.com/user-attachments/assets/59c57409-f351-49e8-bbeb-f594772306e5">

is this the expected behavior of the command , should we include info about this in the documentation


thanks!

**Comment by Kannav02** [comment]
Hey @arpitbbhayani 

just a quick check 
you've told in the issue to use `Examples` as the heading to display the examples for the CLI usage
but in the `SET` documentation, `Example Usage` is being utilised

<img width="832" alt="Screenshot 2024-10-05 at 11 52 30 PM" src="https://github.com/user-attachments/assets/d5bad839-0279-42aa-995f-6997a906efb7">

should I still go ahead and make the change to `Examples`

thank you!
