### ISSUE TITLE
Tests for LRU

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#80]
Test the correctness of LRU implementation and write exhaustive test cases that cover the entire spectrum.

**Comment by himanishm07** [comment]
@arpitbbhayani Is it already assigned? Would like to pick it up.

**Comment by arpitbbhayani** [comment]
Go for it. Assigning it to you. Thanks a ton.

**Comment by jayantpranjal0** [comment]
Heyy, what's the progress on this issue if available.
