### ISSUE TITLE
Space efficient `QUEUEINT` implementation

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#86]
We need core Queue functionality that does O(1) insert, remove, and length operations. Instead of naively storing the integers, store the varints. Also, we should be able to grow the queue to any length.

More details: https://github.com/DiceDB/dice/wiki/QUEUEINT

**Comment by amityahav** [comment]
Hey is this still relevant? I would like to tackle this

**Comment by JyotinderSingh** [comment]
> Hey is this still relevant? I would like to tackle this

This is already implemented, closing this issue.
