### ISSUE TITLE
Inconsistent `TYPE`: Type returns encoding as complex type instead of simple

### ISSUE THREAD

**Issue by apoorvyadav1111** [DiceDB/dice#862]
## Steps to reproduce

<img width="213" alt="image" src="https://github.com/user-attachments/assets/7e3e0de5-c5d7-498a-8a38-fa74e527361b">

## Expected output

<img width="240" alt="image" src="https://github.com/user-attachments/assets/7baba815-dbbe-4223-b7bf-780ed8cb70a6">

The expected output when the above set of commands (maybe when run on Redis)

## Expectations for resolution

This issue will be considered resolved when the following things are done

1. changes in the [`dice`](https://github.com/dicedb/dice) code to meet the expected behavior
2. addition of relevant test case to ensure we catch the regression

You can find the tests under the `tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [setup DiceDB locally](https://github.com/dicedb/dice)
- [setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [setup DiceDB CLI](https://github.com/dicedb/dice)

Please assign this to me. 
Thanks

**Comment by rishavvajpayee** [comment]
hey anyone / you working on this @apoorvyadav1111 ?

**Comment by apoorvyadav1111** [comment]
Hu @rishavvajpayee , Yes, this is 2 line change, I am raising a PR just as we speak. Thanks
