### ISSUE TITLE
No tests available for `eval/hmap` 

### ISSUE THREAD

**Issue by ayushsatyam146** [DiceDB/dice#874]
There are no tests written for hashmap implementation. If it is supposed to be this way and test functionality is getting covered by some other tests then please ignore this issue and close it. Otherwise, I can take this up and add tests.

**Comment by JyotinderSingh** [comment]
The functionality is probably tested as a part of the overall integration and unit test suite for the actual hashmap commands.

However, it will be good to have a smaller more focussed suite for just the hashmap implementation.

Assigning it to you.
