### ISSUE TITLE
Disable list of commands from playground repositories

### ISSUE THREAD

**Issue by lucifercr07** [DiceDB/dice#897]
## Description

DiceDB Playground is an interactive platform that allows users to experiment with DiceDB commands in a live environment, similar to the Go Playground. Users will be able to submit and execute commands directly through a web interface. The initial implementation will focus on enabling users to search for and trigger commands.  
For more details about DiceDB playground you can check [here](https://docs.google.com/document/d/1M5XfuOwQsRcl6g_VBr-FCLy71cnqCp7ulgyt6MsfESU/edit?usp=sharing).  

To enhance the security of our application, we need to implement a blacklist for certain  commands that could potentially lead to data loss or unauthorized access. This blacklist should be enforced in both the backend and frontend components of our application.
Add following commands for blacklisting:
- `FLUSHALL`
- `FLUSHDB`
- `DUMP`
- `ABORT`
- `AUTH`
- `CONFIG`
- `SAVE`
- `BGSAVE`
- `BGREWRITEAOF`
- `RESTORE`
- `MULTI`
- `EXEC`
- `DISCARD`
- `QWATCH`
- `QUNWATCH`
- `LATENCY`
- `CLIENT`
- `SLEEP`
- `PERSIST`

**Note:** Implementation will be part of both DiceDB playground frontend [repo](https://github.com/DiceDB/playground-web) and backend [repo](https://github.com/DiceDB/playground-mono).

## Tasks

1. **Backend Implementation**:
	- Update service to restrict the blacklisted commands.
	- Implement middleware or a service layer to intercept and reject requests for blacklisted commands.
	- Ensure appropriate error responses are returned when blacklisted commands are attempted.
2. **Frontend Implementation**:
	- Block blacklisted commands in frontend, with error message as below:
	  `- `(error) ERR unknown command '<COMMAND_NAME>'
3. Test the implementation to ensure that blacklisted commands are correctly rejected with appropriate error messages.
4. Document the changes made in the README or relevant documentation files.
5. Add sufficient unit and integration test for the same

**Comment by yashbudhia** [comment]
hey can you assign this to me?

**Comment by yashbudhia** [comment]
Thanks for assigning, So i have to open pull requests in those repos right?

**Comment by lucifercr07** [comment]
> Thanks for assigning, So i have to open pull requests in those repos right?

Yes

**Comment by iRittikSharma** [comment]
@lucifercr07  I would like to work on this  issue could you please assign it to me

**Comment by lucifercr07** [comment]
Frontend changes merged as part of https://github.com/DiceDB/playground-web/pull/19

**Comment by yashbudhia** [comment]
I have also added blacklisted commands in the backend repo - https://github.com/DiceDB/playground-mono/pull/23

**Comment by lucifercr07** [comment]
Closing, merged as part of https://github.com/DiceDB/playground-mono/pull/23
