### ISSUE TITLE
Add support for Hyperloglog

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#9]

**Comment by Vsareen0** [comment]
Hey @arpitbbhayani , I would like to take this up. 

```
Resources: 

- https://redis.io/docs/latest/develop/data-types/probabilistic/hyperloglogs/
- http://antirez.com/news/75
```

Commands to add: `https://redis.io/docs/latest/commands/?group=hyperloglog`

Subsequently, opened small PR for picking this up easily.
1. #238 
2. #239
3. #240
4. #241
5. #242

**Comment by arpitbbhayani** [comment]
@Vsareen0 Go for it. Assigned.

**Comment by Vsareen0** [comment]
Still Working on this task, solidifying my understanding a bit more how redis uses it, before writing garbish want to make sure I know what I am writing.

**Comment by AshwinKul28** [comment]
@Vsareen0 Any updated/findings on this? 
cc - @JyotinderSingh

**Comment by Vsareen0** [comment]
Hey @AshwinKul28 , Thanks for asking ! This is already planned, just time was taken to understand things, will be working on this weekend.

**Comment by AshwinKul28** [comment]
Hey @Vsareen0 Sorry to bother you again, Do you have any updates on this? If you have any blockers let's discuss this over the discord. Thanks

**Comment by lucifercr07** [comment]
@Vsareen0 would like to pick this up, if you're not working on this actively.
cc: @JyotinderSingh @AshwinKul28

**Comment by JyotinderSingh** [comment]
> @Vsareen0 would like to pick this up, if you're not working on this actively.
> 
> cc: @JyotinderSingh @AshwinKul28 

Assigned

**Comment by AshwinKul28** [comment]
@lucifercr07 Please close the issue if the item is completely shipped. Thanks for this.
