### ISSUE TITLE
DiceDB doesn't create AOF file with required permission

### ISSUE THREAD

**Issue by keshavchand** [DiceDB/dice#90]
**Describe the bug**
dice-master.aof file created by DiceDB doesn't seem to have the required permission, if the file doesn't already exists. It therefore can't write to the file in its next run.
```shell
ls -al dice-master.aof 
---------- 1 chand chand 0 Nov  9 18:47 dice-master.aof
```
 In case file already exists (`touch dice-master.aof`) it doesn't change permissions. 

**To Reproduce**
1. Make sure dice-master.aof file doesn't exists
2. Run `go run main.go`
3. Shut down server
4. Run `ls -al dice-master.aof`

**Expected behavior**
File should be created with default permissions 0644 (rw-r-r).

**Additional context**
go version : go version go1.18.1 linux/amd64
running on wsl2

**Comment by arpitbbhayani** [comment]
@keshavchand do you want to take this up? I can right away assign.

**Comment by rohanverma94** [comment]
AOF implementation wrap-up for pending TODOs, coming in a while!

**Comment by gauravsarma1992** [comment]
Is this still open? I can take it up if it is.

**Comment by JyotinderSingh** [comment]
> Is this still open? I can take it up if it is.

Assigned
