### ISSUE TITLE
Inconsistent `SINTER`: support for single-key parameter

### ISSUE THREAD

**Issue by arushi-08** [DiceDB/dice#903]
## Steps to reproduce

```
127.0.0.1:7379> SADD set1 "a" "b" "c"
127.0.0.1:7379> SINTER set1
```

## Expected output

The expected output when the above command is run on Redis. Essentially returns all members of the set associated with given key (same as SMEMBERS cmd)

```
1) "a"
2) "b"
3) "c"
```

## Observed output

The observed output when the above command is run on DiceDB.

```
(error) ERROR wrong number of arguments for 'sinter' command
```

## Expectations for resolution

This issue will be considered resolved when the following things are done

1. changes in the [`dice`](https://github.com/dicedb/dice) code to meet the expected behavior
2. addition of relevant test case to ensure we catch the regression

You can find the tests under the `integration_tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [setup DiceDB locally](https://github.com/dicedb/dice)
- [setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [setup DiceDB CLI](https://github.com/dicedb/dice)

**Comment by siddharth-reddy-1607** [comment]
Hi. Can I take this up?
