### ISSUE TITLE
Inconsistent `MGET`: Command in Dice docs isn't matching while running it via `dicedb-cli`

### ISSUE THREAD

**Issue by shashi-sah2003** [DiceDB/dice#914]
This issue has been raised in accordance to fix issue #823 
## Steps to reproduce

 1. go to the dicedb-cli after running dicedb server
 2. on cli, SET key "value1"
 3. on cli, LPUSH key4 "value2"
 4. MGET key key4

## Expected output (given in [documentation of the command](https://dicedb.io/commands/mget/))
<img width="575" alt="image" src="https://github.com/user-attachments/assets/96550786-49b8-4dea-8d70-9d16bab77087">

This is the output that given in the dicedb documentation

```
{expected_output}
```

## Observed output

<img width="338" alt="image" src="https://github.com/user-attachments/assets/52aa4ed1-973f-4ca4-9282-42919afc2169">

This is the case when keys doesn't exist previously.

NOTE: on the redis-cli and dicedb-cli it's giving the same output for the above command. one thing I have observed is that let's say key4 isn't existence then LPUSH will make a list for key4 and store its value but if keys exists then it will throw the error immediately after executing the LPUSH command. I am attaching for a case also when keys exists.

![image](https://github.com/user-attachments/assets/1247591d-22ec-498e-b764-25ecce2a4981)

```
{observed_output}
```

## Expectations for resolution

This issue will be considered resolved when the following things are done

1. changes in the [`dice`](https://github.com/dicedb/dice) code to meet the expected behavior
6. addition of relevant test case to ensure we catch the regression

You can find the tests under the `integration_tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [setup DiceDB locally](https://github.com/dicedb/dice)
- [setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [setup DiceDB CLI](https://github.com/dicedb/dice)

**Comment by mohdammar128** [comment]
Hey @lucifercr07  can you assign this to me .I would like to work on it.

**Comment by lucifercr07** [comment]
This issue should be resolved once https://github.com/DiceDB/dice/issues/823 is fixed. Assigning it to the assignee of #823

**Comment by JyotinderSingh** [comment]
> Hi @shashi-sah2003. Is someone working on this issue? I would like work on this if no one else is assigned for this issue.

Assigned.
