### ISSUE TITLE
Error While Running DiceDb Docs Locally 

### ISSUE THREAD

**Issue by tarun-kavipurapu** [DiceDB/dice#919]
## Steps to reproduce

Run the Dice Db docs locally using 
```
npm run dev
```

## Error Screenshot
![image](https://github.com/user-attachments/assets/81ae5897-c6cf-4291-9b15-8a2893b1fcf4)

## Suggested Fix to Remove Error
- Remove the back ticks for  Echo in `Echo.md` file 

![image](https://github.com/user-attachments/assets/6e3ded2f-59c2-433e-b2f7-83e551801a2c)

**Comment by arushi-08** [comment]
#913 resolves this

**Comment by lucifercr07** [comment]
Closing, merged as part of #923
