### ISSUE TITLE
Hashmap "incrementFloatValue" overflow check not working

### ISSUE THREAD

**Issue by dograprabhav** [DiceDB/dice#921]
```
 (i > 0 && incr > 0 && i > math.MaxFloat64-incr) 
```
This returns false even though it should return true in the case i = math.MaxFloat64, incr = 1.0. This should ideally make the condition to be true but it still returns false.
There should be a test to check overflow in `TestHashMapIncrementFloatValue` method.

I can pick up these changes, can you assign this issue to me @lucifercr07 @JyotinderSingh @AshwinKul28 @arpitbbhayani

**Comment by JyotinderSingh** [comment]
Thanks for reporting this, assigned to you.
