### ISSUE TITLE
Conditionally run unit tests and integration tests on CI

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#925]
Currently unit tests and integration tests for the core server are executed even if no source code is changed. For instance, even if changes are made only to the `docs/` directory the tests are still being run - this leads to compute wastage.

We need to modify the GitHub workflows to run integration and unit tests only when actual code files are modified.

**Comment by sebzz2k2** [comment]
Hey @JyotinderSingh 
Can i pick it up. I can give this a try
Thankyou

**Comment by JyotinderSingh** [comment]
> Hey @JyotinderSingh 
> Can i pick it up. I can give this a try
> Thankyou 

Assigned.

**Comment by lucifercr07** [comment]
Closing, merged as part of https://github.com/DiceDB/dice/pull/928
