### ISSUE TITLE
Http Integration Tests: Create tests to support Hyperloglog

### ISSUE THREAD

**Issue by lucifercr07** [DiceDB/dice#929]
This issue involves creating the below test cases for HTTP as well:

Source: integration_tests/commands/async/

- hyperloglog_test.go

Steps:

- Create the corresponding tests for these commands in integration_tests/commands/http.
- Use set_test.go as a reference, and how to alter the input and output to match JSON structures from RESP.
- Run the tests and fix issues with command parsing in HTTP.

If you need to do anything custom to support HTTP, let @pratikpandey21 @lucifercr07 know.

**Comment by abrahamvineel** [comment]
@lucifercr07 can you please assign this to me? Just to clarify hyperlog tests need to be added under http right?

**Comment by rishavvajpayee** [comment]
Hey can i take this up. @lucifercr07

**Comment by siddharth-reddy-1607** [comment]
@lucifercr07, can I please take this up?

**Comment by hgupta12** [comment]
Hey @lucifercr07 I am already working on this as part of issue #740 . I have already implemented it in PR #873 .

**Comment by hgupta12** [comment]
Hey @lucifercr07 I am already working on this as part of issue #740 . I have already implemented it in PR #873 .

**Comment by abrahamvineel** [comment]
@lucifercr07 As @hgupta12 already has a PR you can assign this task to him. I will pick another one when it's available. Thanks

**Comment by lucifercr07** [comment]
Closing, merged as part of https://github.com/DiceDB/dice/pull/873
