### ISSUE TITLE
Inconsistent `LPUSH`: Command returns OK instead of Integer(length of list)

### ISSUE THREAD

**Issue by Aditya-Chowdhary** [DiceDB/dice#933]
## Steps to reproduce

```shell
127.0.0.1:7379> lpush mylist "test"
```

## Expected output

The expected output when the above set of commands (maybe when run on Redis)

```shell
127.0.0.1:6379> LPUSH mylist "test"
(integer) 1 
```

## Observed output

The observed output when the above set of commands when run on DiceDB

```
127.0.0.1:7379> lpush mylist "test"
OK
```

## Expectations for resolution

This issue will be considered resolved when the following things are done

1. changes in the [`dice`](https://github.com/dicedb/dice) code to meet the expected behavior
2. addition of relevant test case to ensure we catch the regression

You can find the tests under the `integration_tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [setup DiceDB locally](https://github.com/dicedb/dice)
- [setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [setup DiceDB CLI](https://github.com/dicedb/dice)

**Comment by Aditya-Chowdhary** [comment]
Hi, I worked on the doc issue for this command, so would like to contribute to this as well. Thank you.

**Comment by probablyArth** [comment]
https://github.com/DiceDB/dice/blob/887d693113e266c8525c75b103346ced5fbdf997/integration_tests/commands/async/deque_test.go#L86

according to the tests, this is the expected behaviour I think.

Though ideally it should return integer

**Comment by sanuj96** [comment]
Can I work on this?

**Comment by lucifercr07** [comment]
@Aditya-Chowdhary assigned, thanks for contributing.

**Comment by Aditya-Chowdhary** [comment]
Closing as duplicate PR has been merged.
