### ISSUE TITLE
Unhandled "Port Address already in use"

### ISSUE THREAD

**Issue by pranjal-verma** [DiceDB/dice#95]
**Describe the bug**
When running dice on a port that is already occupied by another process, dice simply exits without any error message or exit status.

**To Reproduce**
1. Run dice on a port that is already in use.
![Screenshot from 2022-11-11 00-40-23(1)](https://user-images.githubusercontent.com/42290488/201186729-c4138fa1-cf3c-4840-9490-9d4e6005530e.jpg)

**Expected behavior**
Dice exits with exit status 1 and an error message like "bind: Address already in use"

**Comment by ameyajoshi35** [comment]
@arpitbbhayani can I try this one to start with. looks like a simple log change.

**Comment by arpitbbhayani** [comment]
Go for it @ameyajoshi35

**Comment by rohanverma94** [comment]
@arpitbbhayani @ameyajoshi35 it would be good if there would be a **free port finder module** which can be developed as a pluggable solution. 

For instance, in development mode we can enable this module as there would be many instances where we would stop and restart the DB and but in production mode we can disable it.

**Comment by arpitbbhayani** [comment]
@rohanverma94 let's have a set of ports that we check if none of them are free we panic. Otherwise that port is assigned. Whatvsay?

**Comment by rohanverma94** [comment]
@arpitbbhayani yes this works, a must read regarding the problem - https://onlinehelp.opswat.com/centralmgmt/What_you_need_to_do_if_you_see_too_many_TIME_WAIT_sockets.html

**Comment by ameyajoshi35** [comment]
@arpitbbhayani @rohanverma94 
can you take a look at https://github.com/DiceDB/dice/pull/98
I was looking for a free port finder, we can add that as well but it picks up a random port. may be we can filter that as well.
But as arpit suggested to keep it simple, I have added just a couple of ports and if in case unavailable in debug mode, code will try to start up on set of ports.

**Comment by rohanverma94** [comment]
@ameyajoshi35 Well as @arpitbbhayani suggested you can further narrow down the search for free ports, you don't have to search on an infinite range. It would be more like doing a sequential port scan on a fixed range.

**Comment by sriramr98** [comment]
I realise that this thread has been idle for a while and this looks like a good first issue. Can I pick this up @arpitbbhayani ?

**Comment by reapedjuggler** [comment]
Hi, @arpitbbhayani @rohanverma94 shall I pick this up if it's still available ? 🚀

**Comment by ameyajoshi35** [comment]
feel free to pick this up as my PR is not ready yet.

**Comment by reapedjuggler** [comment]
Thank you for the heads up @ameyajoshi35

**Comment by reapedjuggler** [comment]
Hi, @arpitbbhayani @pranjal-verma @rohanverma94 Can you please check my PR and please review it once? #107
