### ISSUE TITLE
Java Client Driver for talking to DiceDB

### ISSUE THREAD

**Issue by KamaleshProjects** [DiceDB/dice#963]
Self Explanatory Title, I would like to contribute by building a Java based driver that can be plugged into Java applications to talk to a DiceDB Instance, similar to https://redis.io/docs/latest/develop/connect/clients/java/lettuce/ for Redis.

**Comment by shivamprasad99** [comment]
Hi @KamaleshProjects why can't the lettuce client simply connect to DiceDB instance instead of connecting to redis server instance?

**Comment by KamaleshProjects** [comment]
Hi @shivamprasad99 ,

My bad, I just saw that DiceDB is a drop in replacement for Redis, then all the redis clients would be compatible. Thanks.
