### ISSUE TITLE
Feature : Add Support for OBJECT ENCODING

### ISSUE THREAD

**Issue by sashpawar11** [DiceDB/dice#964]
This feature adds support to one of the commands reported on #934 i.e.
`OBJECT ENCODING <key>`

### Expected output
`Returns the internal encoding for the  object stored at <key> : eg - raw, embstr, etc.
`

More about the command - ['OBJECT'](https://dicedb.io/commands/object/)

**Comment by sashpawar11** [comment]
Hi @lucifercr07 , @JyotinderSingh - please assign out to me. Will be raising the PR by tomorrow EOD. Finishing up with writing some unit test cases.

**Comment by JyotinderSingh** [comment]
> Hi @lucifercr07 , @JyotinderSingh - please assign out to me. Will be raising the PR by tomorrow EOD. Finishing up with writing some unit test cases.

Done
