### ISSUE TITLE
Inconsistent `RPUSH`: Command returns OK instead of Integer(length of list)

### ISSUE THREAD

**Issue by Aditya-Chowdhary** [DiceDB/dice#972]
## Steps to reproduce

```
127.0.0.1:7379> RPUSH mylist 1000 2000
```

## Expected output

The expected output when the above set of commands (maybe when run on Redis)

```
127.0.0.1:6379> RPUSH mylist 1000 2000
(integer) 2
```

## Observed output

The observed output when the above set of commands when run on DiceDB

```
127.0.0.1:7379> RPUSH mylist 1000 2000
OK
```

## Expectations for resolution

This issue will be considered resolved when the following things are done

1. changes in the [`dice`](https://github.com/dicedb/dice) code to meet the expected behavior
2. addition of relevant test case to ensure we catch the regression

You can find the tests under the `integration_tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [setup DiceDB locally](https://github.com/dicedb/dice)
- [setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [setup DiceDB CLI](https://github.com/dicedb/dice)

**Comment by Aditya-Chowdhary** [comment]
Wasn't sure if I should include this in #933, so I have created a new issue for RPUSH separately.

**Comment by codeasashu** [comment]
Can I pick this up?

**Comment by lucifercr07** [comment]
Closing merged as part of https://github.com/DiceDB/dice/pull/969
