### ISSUE TITLE
add config file support for http and websocket protocol

### ISSUE THREAD

**Issue by vinitparekh17** [DiceDB/dice#991]
config file should support the following properties

EnableMultiThreading
EnableHTTP
HTTPPort
EnableWebsocket
WebsocketPort

**Comment by kaustubhdeokar** [comment]
Hi @vinitparekh17  can you please assign this issue to me ?

**Comment by vinitparekh17** [comment]
> Hi @vinitparekh17 can you please assign this issue to me ?

It is self assisted issue check my PR above

**Comment by vinitparekh17** [comment]
Resolved
