### ISSUE TITLE
Add support for `GET.UNWATCH` command

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#998]
`GET.WATCH` unsubscribes from a `GET.WATCH` subscription.

**Comment by nm123github** [comment]
Hey @JyotinderSingh, was planning to give this a try. Are `GET.WATCH`, `GET.UNWATCH` command's that can be called from the cli client? I get 
```
127.0.0.1:7379> GET.WATCH k1
(error) ERR unknown command 'GET.WATCH', with args beginning with: k1
```

**Comment by JyotinderSingh** [comment]
> Hey @JyotinderSingh, was planning to give this a try. Are `GET.WATCH`, `GET.UNWATCH` command's that can be called from the cli client? I get 
> 
> ```
> 
> 127.0.0.1:7379> GET.WATCH k1
> 
> (error) ERR unknown command 'GET.WATCH', with args beginning with: k1
> 
> ```

The CLI does not yet support these commands, however that should not stop you from being able to execute them (it only means that you wouldn't receive reactive updates from the server).
The reason why you're seeing this error is because you are not running the server in multithreaded mode.

**Comment by JyotinderSingh** [comment]
> Yes, worked when i executed in multithreaded mode. Few questions,
> 
> 
> 
> - My understanding of `GET.WATCH` is that its similar to [WATCH](https://redis.io/docs/latest/commands/watch/) in redis. Meaning if we're watching a variable being used inside a transaction, and if any other connected client changed its value the transaction (for the first client) wont succeed. Is that a correct understanding?
> 
> 
> 
> - To test this, i was trying to use transactions in multithreaded mode. Noticed a segmentation fault when i tried to EXEC a transaction (only in multithreaded mode). Is this still work in progress?
> 
> ```
> 
> panic: runtime error: invalid memory address or nil pointer dereference
> 
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x100e3b39]
> 
> 
> 
> goroutine 11 [running]:
> 
> github.com/dicedb/dice/internal/eval.ExecuteCommand(0xc00048a5d0, 0x0, 0xc0000b2100, 0x0, 0x0)
> 
> 	/Users/username/projects/dice/internal/eval/execute.go:51 +0x579
> 
> github.com/dicedb/dice/internal/shard.(*ShardThread).processRequest(0xc0000d61c0, 0xc0006bc340)
> 
> 	/Users/username/projects/dice/internal/shard/shard_thread.go:92 +0x45
> 
> ```

Transactions are not yet supported in multi threaded mode.

**Comment by psrvere** [comment]
@JyotinderSingh - please assign this to me.

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh - please assign this to me.

Done.

**Comment by psrvere** [comment]
Starting work on this from today.

**Comment by JyotinderSingh** [comment]
> Starting work on this from today.

Awesome, thanks for the update!

**Comment by psrvere** [comment]
Raised PR
